### ISSUE TITLE
Cross platform compatibility for JOSE JWT algorithm.

### ISSUE THREAD

**Issue by javavenkats5** [dvsekhvalnov/jose-jwt#100]
We have .net system which is using jose jwt RSA certificate algorithm (jose-jwt.dll  v1.9.2 ) for decryption of data at the server side.
My client application is java based using nimbus-jose-jwt.jar (v4.0) using the provided RSA certificate public key to encrypt the data. But the server side decryption is failing.
We also have another .net based client which uses the same dll library it is working fine. The algorithm and encryption method is same in client and server side.

Trying to understand if it is an issue with cross platform between java and .net. Please help on this we are blocked. Appreciate your quick help. 

Followed this example: https://connect2id.com/products/nimbus-jose-jwt/examples/jwt-with-rsa-encryption

Java client code:
` 
private String runCertificate(String ssn) throws Exception {

                              JWTClaimsSet jwtClaims = new JWTClaimsSet.Builder().jwtID(ssn).build();
                              JWEHeader header = new JWEHeader(JWEAlgorithm.RSA_OAEP, EncryptionMethod.A128CBC_HS256);

                              EncryptedJWT jwt = new EncryptedJWT(header, jwtClaims);
                              InputStream inStream = new FileInputStream("C:/temp/cert/test.cer");
                              CertificateFactory cf = CertificateFactory.getInstance("X.509");
                              X509Certificate cert = (X509Certificate) cf.generateCertificate(inStream);
                              JWEEncrypter encrypter = new RSAEncrypter((RSAPublicKey) cert.getPublicKey());
                              jwt.encrypt(encrypter);
                              String jwtString = jwt.serialize();
                              
                              return jwtString;

               } 
`
              

.Net Client code:

private static string EncryptedSSN(string SSN)
        {
            X509Certificate2 Certificate = null;
            string encrptedSSN = "";
            var Store = new X509Store(StoreLocation.CurrentUser); //For running in local machine
            Store.Open(OpenFlags.ReadOnly);
            var Certificates = Store.Certificates;
            string Certificatesubject = System.Configuration.ConfigurationManager.AppSettings["CertificateSubject"];
            foreach (var cert in Certificates)
            {
                if (cert.Subject.Contains(Certificatesubject))
                {
                    Certificate = cert;
                    break;
                }
            }

            if (Certificate != null)
            {
                RSA RsaKey = ((RSA)Certificate.PublicKey.Key);
                encrptedSSN = Jose.JWT.Encode(SSN, RsaKey, JweAlgorithm.RSA_OAEP, JweEncryption.A128CBC_HS256);
            }

            else
            {
                throw new ArgumentException("RSA Key Required");
            }
            return encrptedSSN;
        }

**Comment by dvsekhvalnov** [comment]
Hi @javavenkats5 ,

nimbus jwt library is in the list of libraries i'm using for cross testing against. It should be no issues with.

I'll need example of token you failed to validated along with keys if you don't mind for troubleshooting.

**Comment by javavenkats5** [comment]
encrypted ssn=123456789

with java client:

eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ.X8kcrDaJGRu2A4EpfC98K3-HGxgMdAMT6YKwik08iDZ5l6WXqTq90lTyAOF81zHuWyIl3v6puvW7Qt0KWK6EnoQG32EEllZwZjOz93ewEgQHvDMDHu0PzAHOreb3NMcuOrOBLwGEvtb7aStRs7MzqEmaZwLdwvX9rVoiXxe-wJSvXq8B3cHP-tbPJI1wl9VltHtLMBzhEI6Ey4hgH8295cnEf4RYWqMmuPEx5AhhCqs-nKLlTImPTmB3_FX8NINZEaCJiErNV_lvJFNVYQt-3_f6qU62aM7GHdr43oB-aWHjlb5FrcinbIKVR48lPEP9D6ksPtERCatOnUQx6fGTMA.CDb0OpWEBFbD7jWaJe9wgQ.6JyFbuq8F6ahgfW7Bkr82Q.Qb2T9LCjrW9BEyjQFAbDGw

with .Net Client:

eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ.B7mhB2DCEBPomEY_tFQwAXE77efCHRjuNsCAFXAHN-Iq83ygiT1C-JQ8sE65SSqIbNez4JS81QEPsjLEWHMF8WcTEcRit7ZOmTjDKGm7qjhnYLHuoeXzxiBPdpezIPDijQxnkzuwCtoxmSJ-Mw-gdDdCtelNiDyGxhTAFwUs4U_eOHqM4SvZU7P-4-EsgTRLKAWkVHGsJCkqRhR0o6HfR_m89ykDgC-iIeom3K2jYEUgzHxifzXeejhKTSI6H-65YmlVWApvul0voVx17TCrxTEgBCM1CnXNLV_5DXxBiiXZm0i5FvflXH3Yh2bCqwUtw3P0Z5PdqN-X8wnCye98nw.pzwot7uYXvNtuEpZi2Pe0g.7j3zI0-Yru8n5y8C2Z9dXQ.rpytytcjVbt036Z_2dR2lw

**Comment by dvsekhvalnov** [comment]
@javavenkats5 keys please? :)

**Comment by dvsekhvalnov** [comment]
Ok, sure thing. Please no production keys.

Generate test keys and add create new samples?

**Comment by javavenkats5** [comment]
@dvsekhvalnov shared test cert with your gmail id.

**Comment by dvsekhvalnov** [comment]
Hey @javavenkats5 , i have no problem decoding tokens you've emailed to me, here is sample:

```c#
 var tokenJava = "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAifQ.CfJmXHa0X9MUo0Bw1SlKHE8Bz1f6HwHXBI2ktfIC4MgfHP6-LCGgIf_NQnpccZ-LuSN7iddils7Sl0qbBH-3_5gHslDu9TQDkobRjL3ate5kgVu9Tev4PTGKHP-JkBb4HFxW_DDoyoTSh4Cr-iQ7XqZNNoQ_IM9DRdpCQsknCPcf0aOCXmrkjdZFYJu1hM7QnpttMD20kyKdIxvgap6h8209Drxc1DfLXX_cq4rDlnymZ1w6sUdXP1MlCjvO0JxWHFPuyfTXN3vApW6cHoWtA6G18duw5xJHggV-9iVnBVOkzh0X4XWuSw4YmaOYDX_B8dT458aAECV1MYG-Tf7X7Q.RlktRbvuwOMO_3ZoAko8FA.MYOxKiyB_fQWD05s2cwNbefXt8TTS9eCpI-3aYbuiO4.XhIvFrt5ndfsZPB0B0cUzg";
            var tokenNet = "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ.iHHlplvLzjCjTqSs0X1C39qWZurcv4yHjboFwPR37pNI9jSggsDb5_nqI9vGDqeiE8V7ueuchJFirD4QpmMnMx2Y6-QUJZUpxElgtQtrhOT5pSAc_eUzk4XvrJt-0fSOl9Z-HFeM140muKtEcN3pTi_ZiJM5dM1HdzvWEKLxHlParcwJXvJIw2vx1BBwNRp-K6nwFVz6icDNZab4akfo2orPUaE00WgBfLl6MGYMOgj16316KGcy0CWZOJK8lDFUgPfVSUT9HX5-qMm1K3bTwUHjqu3p8dWNLEry-3fEnIyTYR-bvyA2nW-hGGKB3DOQyxy45l-8ITxp06EIgZPZpw.Q5McLwPjZ3e6DBlrAc8gJA.fJ1Of-xruMkVr6gDOOledg._n4GQ2ZQGLkfJNaVvu3XYw";

            var x509 = new X509Certificate2(@"C:\projects\github\jose-jwt\UnitTests\issue-100.p12", "1");
            var privateKey = x509.GetRSAPrivateKey();

            var payloadJava = Jose.JWT.Decode(tokenJava, privateKey);
            var payloadNet = Jose.JWT.Decode(tokenNet, privateKey);

            Console.Out.WriteLine("java = " + payloadJava);
            Console.Out.WriteLine("net = " + payloadNet);
```

**Comment by javavenkats5** [comment]
@dvsekhvalnov , I just noticed an issue in the ouputs you mentioned, javatoken is decoded to a json string where as .net token is decoded to whole number. We expect whole number from both payloads.
Do you recommend any code change in java encryption method so that .net decode method produces the while number.

**Comment by dvsekhvalnov** [comment]
Sounds good, glad you made it :)
