### ISSUE TITLE
Decode issue with RSA encrypted token

### ISSUE THREAD

**Issue by itandy** [dvsekhvalnov/jose-jwt#101]
We previously built a JWT (with both encryption and signing using RSA keys) communication protocol using Java. Now we're trying to add support for .NET clients. We've successfully build the request, which is signed by client primary key and encrypted with server public key. The request can be processed by the server. But when processing the response from the server, the following exception is raised when trying to decrypt the response token:

> System.Security.Cryptography.CryptographicException: 'Key not valid for use in specified state.'

I traced the source code and found it happens in the Unwrap function inside RsaOaep245KeyManagement.cs. Seems the code is trying to create a new RsaKey object using my client private key but my key doesn't support export feature. And interestingly, this part of the code has a comment saying it should be removed in 3.x.

So anyone has experience how to overcome this?

Note: Our server is built using Nimbus JWT library. Encryption algorithm used is RSA_OAEP_256 while method is A128GCM. RSA keys are generated using OpenSSL.

**Comment by dvsekhvalnov** [comment]
Hi @itandy ,

just don't use `RSACryptoProvider` use `RSA` interface directly if you are on .NET 4.6 or higher. There are extensions to `X509Certificate2`: `GetRSAPrivateKey()` and `GetRSAPublicKey()` - that do not suffers from this problem.

If you stuck on .NET below 4.6 see here: https://github.com/dvsekhvalnov/jose-jwt#dealing-with-keys

**Comment by itandy** [comment]
Unfortunately I'm still on .NET4.

I'm actually using the method to specify "Microsoft Enhanced RSA and AES Cryptographic Provider" as CSP when generating the p12 file using openssl. This way, I'm able to load the private key and use it to sign the request token successfully.

My problem only happen when using the primary key to decrypt the response token. The other methods (re-import RSAParameters & Enforce correct CSP) seem to require the primary key as exportable which seems not appropriate for production.

**Comment by dvsekhvalnov** [comment]
Well if you can't/don't want to make private key exportable (which is
understandable) stick with CngKey directly.

That's what library doing internally - converts RSACryptoProvider to CngKey

**Comment by dvsekhvalnov** [comment]
@itandy , i think docs little bit misleading, you can freely use `CngKey` as key type when working with  .NET40 - .NET4.5 , not limited to `RSACryptoServiceProvider` only.

https://github.com/dvsekhvalnov/jose-jwt/blob/master/UnitTestsNet40/TestSuite.cs#L678

**Comment by dvsekhvalnov** [comment]
Closed due to inactivity, feel free to re-open if question still valid.
