### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by chessar** [dvsekhvalnov/jose-jwt#103]
Could not load file or assembly 'jose-jwt, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044).

**Comment by dvsekhvalnov** [comment]
Hi @chessar ,

we not providing strong-named version of library. 

In the past people had success with https://github.com/brutaldev/StrongNameSigner tool to make one.
Please see: #5 or #44.

If you need approval for making strong-named version out of jose-jwt v2.4.0.0 - feel free :)
