### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by YH8689** [dvsekhvalnov/jose-jwt#104]
HI,

I am using VS2015 ad having the following compilation error.
Would you be able to guide me on how to resolve the error.

1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\jws\netstandard1_4\EcdsaUsingSha.cs(32,39): .NETFramework,Version=v4.6.1 error CS7036: There is no argument given that corresponds to the required formal parameter 'count' of 'ECDsaCng.SignData(byte[], int, int)'
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\jws\netstandard1_4\EcdsaUsingSha.cs(42,39): .NETFramework,Version=v4.6.1 error CS1061: 'ECDsa' does not contain a definition for 'SignData' and no extension method 'SignData' accepting a first argument of type 'ECDsa' could be found (are you missing a using directive or an assembly reference?)
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\jws\netstandard1_4\EcdsaUsingSha.cs(65,39): .NETFramework,Version=v4.6.1 error CS7036: There is no argument given that corresponds to the required formal parameter 'signature' of 'ECDsaCng.VerifyData(byte[], int, int, byte[])'
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\jws\netstandard1_4\EcdsaUsingSha.cs(75,38): .NETFramework,Version=v4.6.1 error CS1061: 'ECDsa' does not contain a definition for 'VerifyData' and no extension method 'VerifyData' accepting a first argument of type 'ECDsa' could be found (are you missing a using directive or an assembly reference?)
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\crypto\AesGcm.cs(35,91): .NETFramework,Version=v4.6.1 warning CS0728: Possibly incorrect assignment to local 'authInfo' which is the argument to a using or lock statement. The Dispose call or unlocking will happen on the original value of the local.
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\crypto\AesGcm.cs(42,86): .NETFramework,Version=v4.6.1 warning CS0728: Possibly incorrect assignment to local 'authInfo' which is the argument to a using or lock statement. The Dispose call or unlocking will happen on the original value of the local.
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\crypto\AesGcm.cs(81,93): .NETFramework,Version=v4.6.1 warning CS0728: Possibly incorrect assignment to local 'authInfo' which is the argument to a using or lock statement. The Dispose call or unlocking will happen on the original value of the local.
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\crypto\AesGcm.cs(88,88): .NETFramework,Version=v4.6.1 warning CS0728: Possibly incorrect assignment to local 'authInfo' which is the argument to a using or lock statement. The Dispose call or unlocking will happen on the original value of the local.
1>D:\Customer\NTP\JWT\jose-jwt-master\jose-jwt\project.json(76,23): error NU1008: "netstandard1.4" is an unsupported framework.

**Comment by dvsekhvalnov** [comment]
Hi YH8689, 

it seems you trying to compile against some newer version of framework.  

What are you trying to do?

**Comment by dvsekhvalnov** [comment]
@YH8689 you can install compiled version from nuget: https://www.nuget.org/packages/jose-jwt/
or download .dll from releases page: https://github.com/dvsekhvalnov/jose-jwt/releases

If you really wish to compile it yourself i guess you need .net framework 6.4.1 and .net standard 1.2 on your dev machine.

**Comment by YH8689** [comment]
thank you.

**Comment by dvsekhvalnov** [comment]
Feel free to reopen if more related questions.
