### ISSUE TITLE
ECCurve support of EccKey.

### ISSUE THREAD

**Issue by daisukenishino** [dvsekhvalnov/jose-jwt#105]
Thank you for providing a nice class library.

Now, I want to generate JWS of ES256 on linux. However, your EccKey class only supported CngKey, so it could not be used on linux. Therefore, created an ECDSA certificate and accomplished this by using the GetECDsaPrivateKey and GetECDsaPublicKey extension methods.

- SampleProgram/Program.cs at master · OpenTouryoProject/SampleProgram
https://github.com/OpenTouryoProject/SampleProgram/blob/master/Other/jose_jwt_Sample/jose_jwt_Sample/Program.cs#L138

However, I think that the almost people maybe want to obtain the public key by JWK in this situation. For this reason, I think it would be wonderful if support to generate ECCurve from JWK was added to EccKey.

- JSON Web Key (JWK) > 3.1.  Example JWK
http://self-issued.info/docs/draft-jones-json-web-key-00.html#ExampleJWK

thank you for your consideration.

**Comment by dvsekhvalnov** [comment]
Hi @daisukenishino , 

yep, `GetECDsaPrivateKey\GetECDsaPublicKey` extensions are way to go on both linux and windows, as described in docs https://github.com/dvsekhvalnov/jose-jwt#es---family :) Those are more cross platform than CngKey, but still depends on concrete netcore implementation for underlying OS. 

Yeah that's the most popular request so fat i guess. Should give it some traction or alternate feel free to contribute, would be happy to accept PR. If you wanna do it, there is ticket with some more info and samples: https://github.com/dvsekhvalnov/jose-jwt/issues/10

**Comment by daisukenishino** [comment]
@dvsekhvalnov 

Thank you very much.
I will study to understand #10.

**Comment by dvsekhvalnov** [comment]
@daisukenishino see https://github.com/psteniusubi/jose-jwt/blob/master/jose-jwt/jwk/JwkEc.cs

it's .net 4.7 only, but probably we can release it for 4.7+ for now and see if somebody requires lower version later.

**Comment by daisukenishino** [comment]
@dvsekhvalnov 

Thank you very much.
I will implement it using the information given from you.

- https://github.com/psteniusubi/jose-jwt/blob/master/jose-jwt/jwk/JwkRsa.cs
‐ https://github.com/psteniusubi/jose-jwt/blob/master/jose-jwt/jwk/JwkEc.cs
‐ https://github.com/dvsekhvalnov/jose-jwt/blob/master/jose-jwt/Security/Cryptography/EccKey.cs#L89

**Comment by dvsekhvalnov** [comment]
@daisukenishino i'd verify ECCurve and ECParameters are really working on linux first.

If you'd like to contribute back to library please pay attention to my comments starting here: https://github.com/dvsekhvalnov/jose-jwt/issues/10#issuecomment-330848384

**Comment by daisukenishino** [comment]
@dvsekhvalnov 

I plan to develop an OIDC Server that runs on ASP.NET Core on linux.
https://github.com/OpenTouryoProject/MultiPurposeAuthSite

There is a needs to support JWS (ES 256) and JWE (RSAES-OAEP and AES GCM, etc.), because correspondence of FAPI part2 is also taken into consideration at that project.  At this time, the public key needs to be JWKed. For this reason, I think that the results can be reported to you eventually.

**Comment by dvsekhvalnov** [comment]
Cool, let me know when you have something :)

**Comment by daisukenishino** [comment]
## Result report
I implemented with reference to the code of psteniusubi.
As a result, it worked as expected.

### Evidence
```CMD
DigitalSignX509.Verify(ECDSA) > True
ECDSA JWK > {"kty":"EC","alg":"ES256","crv":"P-256","x":"qdS3bsts3UXi5p0G71GofUB9ls1fJz_z0dRQw9RZ99A","y":"hX6HISTIiDLt90VDEqGmsMj2kSlGLOcXgXSqz75EhV4","kid":"mdAGx-nGwwhNScer459MfN0GvMKD_N3IY5efKmQVLTE"}
DigitalSignX509.Verify(ECDSA JWK) > True
```

### Test code
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/CS/Frameworks/Tests/EncAndDecUtilCUI/Program.cs#L251

Process sequence:
+ Signed the data from ECDSA certificate of pfx.
+ The public key that was used for the signature is converted to JWK.
+ Convert the JWK to ECParameters.
+ ECDsaOpenSSL initialized by the ECParameters.
+ Verified the signature with the ECDsaOpenSSL.

### X509
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/files/resource/X509

### Libraries
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/CS/Frameworks/Infrastructure/Public/Security

**Comment by daisukenishino** [comment]
@dvsekhvalnov 

I used EccKey for mutual conversion between JWK and CngKey but it did not work well. Result of analysis, I found a behavior that seemed to be one problem. Specifically, I think that processing to extract X and Y parameters from EccKey has problem.

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/CS/Frameworks/Tests/EncAndDecUtilCUI/Program.cs#L385

#### Operates normally.
```CS
privateKeyOfCng = EccKey.New(x, y, d);
publicKeyOfCng = EccKey.New(x, y);
token = JWT.Encode(payload, privateKeyOfCng, JwsAlgorithm.ES256);
JWT.Decode(token, publicKeyOfCng);
```

#### Abnormal terminate.
```CS
privateKeyOfCng = EccKey.New(x, y, d);
EccKey temp = EccKey.Generate(privateKeyOfCng);
publicKeyOfCng = EccKey.New(temp.X, temp.Y);
token = JWT.Encode(payload, privateKeyOfCng, JwsAlgorithm.ES256);
JWT.Decode(token, publicKeyOfCng);
```

**Comment by dvsekhvalnov** [comment]
@daisukenishino , mind share exception?

**Comment by dvsekhvalnov** [comment]
@daisukenishino to be fair i'm following. Can you elaborate what you trying to do?

`EccKey.Generate(..)` - creates new key. It is used to generate ephemeral ec keys during key exchange. And yes every time you call it, it will generate entirely new key.

**Comment by daisukenishino** [comment]
>@daisukenishino to be fair i'm not following. Can you elaborate what you trying to do?

I wanted to implement mutual conversion between CngKey and JWK which works on net 452 or later.

>EccKey.Generate(..) - creates new key. It is used to generate ephemeral ec keys during key exchange. And yes every time you call it, it will generate entirely new key.

I had misunderstood the function of EccKey.Generate method.

If I use ECDsaCng.ExportParameters method, it can be processed from CNG.
But, this method returning ECParameters requires net47 or later.

However, this is a redundant requirement and the functions I wanted to use in my project are already implemented. In the range that I tested, your library will worked properly on linux with the excluded #45 and #62 and #91 problems about bcrypt.dll. I appreciate your cooperation.

**Comment by dvsekhvalnov** [comment]
Glad it working, feel free to reopen if you have more questions.

**Comment by daisukenishino** [comment]
Thank you for your concern.
I will ask you again if I have any questions.
