### ISSUE TITLE
Jose.JWT.Decode JweAlgorithm.RSA_OAEP_256, JweEncryption.A256GCM .net Core 2.0

### ISSUE THREAD

**Issue by matthias-jer2spy** [dvsekhvalnov/jose-jwt#106]
I am trying to decrypt a JWE return by a Mulesoft API with .Net Core 2.0 and Jose 2.4.0

I get the JWE, the stock in string. The private key and its password are also correct.

When I decode, I have an error System.Security.Cryptography.CryptographicException : 'Specified padding mode is not valid for this algorithm.'

But in the first part of jwe "eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0" in base64 => {"alg":"RSA-OAEP-256","enc":"A256GCM"}

`//get private key
TextReader decrypterPrivateReader = System.IO.File.OpenText(decrypterPrivateFile);
PemReader decrypterPrivatePemReader = new PemReader(decrypterPrivateReader, new PasswordFinder(decrypterPrivatePwd));
RsaPrivateCrtKeyParameters decrypterPrivateKey = (RsaPrivateCrtKeyParameters)((AsymmetricCipherKeyPair)decrypterPrivatePemReader.ReadObject()).Private;

RSAParameters decrypterPrivateParams = DotNetUtilities.ToRSAParameters(decrypterPrivateKey);
RSACryptoServiceProvider decrypterPrivateProvider = new RSACryptoServiceProvider();
decrypterPrivateProvider.ImportParameters(decrypterPrivateParams);

//decode token
return Jose.JWT.Decode(jwe, decrypterPrivateProvider, JweAlgorithm.RSA_OAEP_256, JweEncryption.A256GCM);`

Thanks all for your time

**Comment by dvsekhvalnov** [comment]
Hi @matthias-jer2spy ,

1. First try .Decode() without explicit algs, e.g. `Jose.JWT.Decode(jwe, decrypterPrivateProvider)`
2. If it doesn't help, i need example of token you trying to decode and keys to try myself.

Please make sure you don't post any keys that you are using in **production** or other confidential data, not to compromise.

**Comment by matthias-jer2spy** [comment]
hi @dvsekhvalnov Thanks for your responce. It's my bad. 

I just replaced RSACryptoServiceProvider by RSACng and it works. Thanks you are amazing

**Comment by matthias-jer2spy** [comment]
Just for informations, this sollution just work in windows system.

**Comment by dvsekhvalnov** [comment]
yeah, i think it is outlined in documentation :)
