### ISSUE TITLE
IsToken with encryption

### ISSUE THREAD

**Issue by generik0** [dvsekhvalnov/jose-jwt#110]
HI.
Thanks for making JWT so simple with the package ! :-)

Is there any good / easy way to find out if the token is a Token?

I.e. IsToken(JwsAlgorithm.RS256) ?

Thanks again ...

**Comment by dvsekhvalnov** [comment]
Hi @generik0 ,

Can you elaborate little bit? You want to check if arbitrary input string is jwt encoded? Or find out specific signing/encryption algo that was used for encoding? Or may be something else?

Thanks.

**Comment by generik0** [comment]
Hi @dvsekhvalnov 
You are so right. I was not specific enough.
I just want to check if a string input is encoded with a specific encryption.

Not caring about the signed or cert.

You see we use the tokenizer to encode som api keys we have in a settings database. The Db is secure, but this makes it even more secure...
But sometimes when debugging we want to manually add an api key, not encrypted.
For this reason, when decoding, it would be nice to check if the potentially encoded key in the DB actually is encoded. If it is, decide with the signing, if it isn’t, return as is..
Is this possible?

**Comment by dvsekhvalnov** [comment]
Well, i think you can try get headers and check if any alg was set:
```c#var headers = Jose.JWT.Headers(token);``` 
(https://github.com/dvsekhvalnov/jose-jwt#two-phase-validation)

You can also consider using `NONE` alg for this purpose (https://github.com/dvsekhvalnov/jose-jwt#creating-plaintext-unprotected-tokens). It that case your API key will be JWT, but not protected (plaintext) and you don't need any special handling for dev keys in that case.

**Comment by generik0** [comment]
I will try with the headers.
But we do want the encryption :-)
