### ISSUE TITLE
Time zone loss problem of serializing and deserializing time

### ISSUE THREAD

**Issue by dayhi** [dvsekhvalnov/jose-jwt#113]
For example: I am now in UTC/GMT +8.00 time zone, encrypt the current time, and then decrypt, there will be 8 hours less problem.

**Comment by dvsekhvalnov** [comment]
Hi @dayhi , 

would you mind to show some code to reproduce issue? Unit test would be ideally.

**Comment by dayhi** [comment]
```
/// <summary>
    /// 加密解密帮助类
    /// </summary>
    public class TokenHelper {

        //秘钥
        private static byte[] secretKey = { 1 };

        /// <summary>
        /// 加密
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public static string Encode (object obj) {
            return Jose.JWT.Encode (obj, secretKey, JwsAlgorithm.HS256);
        }

        /// <summary>
        /// 解密
        /// </summary>
        /// <param name="token"></param>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public static T Decode<T> (string token) {
            try {
                return Jose.JWT.Decode<T> (token, secretKey);
            } catch (System.Exception) {
                return default (T);
            }

        }
    }
```

```
public class TokenModel{
        public string name { get; set; }
        public DateTime time { get; set; }
    }
```

main code
```
var t=new TokenModel();
t.name="test";
t.time=DateTime.Now;
var tStr=TokenHelper.Encode(t);
var newT=TokenHelper.Decode<TokenModel>(tStr);
```

The newT object here will have less time zone than before.

**Comment by dvsekhvalnov** [comment]
Is it netcore or net framework? Or in other words are you using newtonsoft json mapper or built-in JavaScriptSerializer from System.Web.Script.Serialization ?

jose-jwt doesn't make any assumption about your payload or how you serialize it, it may be not be json at all. So in general it seems issues with json mapper configuration.

**Comment by dvsekhvalnov** [comment]
my guess you just get UTC time back? So if you change your test to:
```c#
var t=new TokenModel();
t.name="test";
t.time=DateTime.UtcNow;
var tStr=TokenHelper.Encode(t);
var newT=TokenHelper.Decode<TokenModel>(tStr);
```

it will pass now?

**Comment by dvsekhvalnov** [comment]
Hey @dayhi , checking if issue is resolved and can be closed?

**Comment by dayhi** [comment]
I am very sorry that I have not returned so long.Use net framework。I have not used this encryption method in the project for some reason, so I can't provide the test, sorry.
