### ISSUE TITLE
System.IndexOutOfRangeException : Index was outside the bounds of the array

### ISSUE THREAD

**Issue by amoissant** [dvsekhvalnov/jose-jwt#115]
Hello, 
We get this exception : 
`System.IndexOutOfRangeException : Index was outside the bounds of the array.`
When calling the following code : 
`JWT.Payload("null");`

Is it a bug or the the caller must validate token's format before calling JOSE ?

Anthony

**Comment by dvsekhvalnov** [comment]
Hi @amoissant ,

sorry somehow missed notification for your issue (

Yeah, sounds like fair improvement, `System.IndexOutOfRangeException` definitely ugly.

Wanna provide PR with a fix?

**Comment by amoissant** [comment]
Hi, it's in my todo list, will try to make a pull request soon.




Le lun. 3 juin 2019 à 21:31, dvsekhvalnov <notifications@github.com> a
écrit :

**Comment by dvsekhvalnov** [comment]
Looks good to me, merged !
