### ISSUE TITLE
Unable to Decode token on specific machine

### ISSUE THREAD

**Issue by s3ncha** [dvsekhvalnov/jose-jwt#116]
Hello,

I'm using  JweAlgorithm.DIR & JweEncryption.A128CBC_HS256 to generate token:

`string token = Jose.JWT.Encode(payload, keyy, JweAlgorithm.DIR, JweEncryption.A128CBC_HS256);`

Which I then decode on the same machine

`var  tkn = Jose.JWT.Decode<TestToken>(token, key);`

Everything works fine on my machine, but  when trying to decode on Windows Server 12R2
I'm getting following exception:

`You do not have rights to access this url: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. `

I'm using .net framework 4.6.2 with asp.net application on both machines, using the same key, but for some unable to Decode tokens generated on 2012r2 server.   Is there anything else I can check?

**Comment by dvsekhvalnov** [comment]
Hi @s3ncha ,

mind posting full source you use to decode token? Your error doesn't sound to be related to library at first glance. Probably something else going on.

**Comment by s3ncha** [comment]
thanks for responding @dvsekhvalnov 
This is pretty much it to be honest. I pass token to asp.net application and extract it via custom http module.

```
    public class TestToken
    {
        public string file { get; set; }
        public DateTime exp { get; set; }
        public int userid { get; set; }
        public string ip { get; set; }
     }

/// and the actual code
byte[] key = Storage.SharedKey;  
var tkn = HttpContext.Current.Request.Params["token"];
if (string.IsNullOrEmpty(tkn)) {
    throw new Exception("Security token is missing");
}
var token = Jose.JWT.Decode<TestToken>(tkn, key);
// this throws exception
```

Key is pre-shared with app that generates token and it works fine in dev environment. 
What algo is actually used with I specify `JweAlgorithm.DIR` ?

**Comment by dvsekhvalnov** [comment]
`DIR` - is direct, no key alg used, the pre-shared symmetric key used directly to encrypt/decrypt content.

I'd suggest do unit test or console application to remove asp.net and storage parts from equation. Just hardcode JWT token as string and your key as byte[] array and see if decode fail on your machine.

Something like:
```c#
   var token = "......your jwt here....";
   byte[] key = .......;

   var payload = Jose.JWT.Decode(token, key);
```

**Comment by dvsekhvalnov** [comment]
Also try to log `tkn` variable and feel free to past here, probably it somehow got corrupted?

**Comment by dvsekhvalnov** [comment]
Hi @s3ncha , just checking to see if you had any progress with your issue?

**Comment by s3ncha** [comment]
@dvsekhvalnov  sorry for keeping this open. I was away for a bit and will perform all tests today and let you know

**Comment by s3ncha** [comment]
@dvsekhvalnov my apologies, it works perfectly and they issue was not related to jose-jwt at all.
thank you for an awesome lib and support
