### ISSUE TITLE
FileVersion should be bumped to 2.5.0

### ISSUE THREAD

**Issue by hcornelison** [dvsekhvalnov/jose-jwt#122]
In jose-jwt/Properties/AssemblyInfo.cs, the file version properties should be bumped to 2.5.0 to match the 2.5.0 release of this library, correct?

**Comment by slorello89** [comment]
I'm not positive but I'm getting missing method exceptions when I try to use the 2.5.0 library - I'm fairly certain this is because the wrong assembly is being targeted. Perhaps a config parameter in the interim.

**Comment by slorello89** [comment]
submitted a pr #123 that should fix it - if the nuget package can't be amended it may be worth revving to 2.5.1 instead

**Comment by dvsekhvalnov** [comment]
thanks for mr !

yeah, i guess it needs new release.

**Comment by dvsekhvalnov** [comment]
closing, as we approaching v3.0
