### ISSUE TITLE
IterationCount for PBKDF2 is hardcoded

### ISSUE THREAD

**Issue by dhcgn** [dvsekhvalnov/jose-jwt#124]
It would be practical if the PBKDF2 iteration count would be overrideable.

https://github.com/dvsekhvalnov/jose-jwt/blob/e54de3bb706edf294053b4b86f0db47333d433ef/jose-jwt/jwa/Pbse2HmacShaKeyManagementWithAesKeyWrap.cs#L27

More Information: [JSON Web Algorithms (JWA)](https://tools.ietf.org/html/rfc7518#section-4.8.1.2)

>    The "p2c" (PBES2 count) Header Parameter contains the PBKDF2
>    iteration count, represented as a positive JSON integer.  This Header
>    Parameter MUST be present and MUST be understood and processed by
>    implementations when these algorithms are used.
> 
>    The iteration count adds computational expense, ideally compounded by
>    the possible range of keys introduced by the salt.  A minimum
>    iteration count of 1000 is RECOMMENDED.

**Comment by dvsekhvalnov** [comment]
Hi @dhcgn , thanks for ticket, yeah that's sound like reasonable enhancement to me.

Sorry i haven't noticed you ticket earlier, some how not getting proper notification from github anymore.

Do you want to submit PR or just open ticket? )

**Comment by archimed7592** [comment]
> Do you want to submit PR or just open ticket? )

Hi @dvsekhvalnov , I'd like to submit PR. How do I do that? I can't create a branch, I can't create a PR from my local branch... is there a way to do it myself or should you configure some permissions?

Patch is in attachment if that's what it takes: [0001-Fix-hardcoded-iterationsCount-issue-124.zip](https://github.com/dvsekhvalnov/jose-jwt/files/5455030/0001-Fix-hardcoded-iterationsCount-issue-124.zip)

**Comment by dvsekhvalnov** [comment]
Hi @archimed7592 , can you please make it Pull Request? So it is easier to review. Thank you.

**Comment by archimed7592** [comment]
@dvsekhvalnov , I figured it out - I had to fork your repo to create a PR.
Here it is: https://github.com/dvsekhvalnov/jose-jwt/pull/143

**Comment by dvsekhvalnov** [comment]
Thanks for PR guys ! 

Will release it soonish.

**Comment by dvsekhvalnov** [comment]
v2.6.1. released.

**Comment by dvsekhvalnov** [comment]
Thanks @archimed7592 , your fix was published.
