### ISSUE TITLE
[Suggestion] Potential safety risk

### ISSUE THREAD

**Issue by crclz** [dvsekhvalnov/jose-jwt#125]
While deserializing a token, if a field is not provided in token (due to payload schema change), the field will remain default value (Newtonsoft.Json's behavior). This is quite dangerous, which could give attacker chances.

Suppose I have my jwt payload class Payload.
```cs
class Payload
{
    public int UserId {get;set;}
}
```

Later I change my Payload class to
```cs
class Payload
{
    public int Id {get;set;} // UserId -> Id
}
```

Now, if the library deserialize a token issued before I changed Payload class, the payload data will be: {Id=0}.
The user will get someone else's identity.

The solution is tell json deserializer to be "strict" (I don't know how to do it), or use nullable fields (e.g. int?) in Payload class.

So I suggest adding some warnings in the readme document.

**Comment by dvsekhvalnov** [comment]
Hi @crclz , not bad idea, wanna submit PR?

**Comment by dvsekhvalnov** [comment]
Thanks for MR.
