### ISSUE TITLE
Question: How to generate a JWT token that is signed and encrypted

### ISSUE THREAD

**Issue by MartyBJones** [dvsekhvalnov/jose-jwt#126]
How do I generate a JWT token that is signed with my private key and then encrypted with a public key from an outside source?

I am able to create a token that is signed with no issues and I can create a token that is encrypted with no issues but not sure how to sign and encrypt a given token.

**Comment by dvsekhvalnov** [comment]
Hi @MartyBJones ,

can you elaborate little bit on your use-case? I can hardly imagine why you'd like to do both on same payload, though this question time to time pops up here.

- Signing - ensures that your payload was not tampered (modified)
- Encryption - ensures nobody can read payload except intended audience. It clear includes all properties from signing too (e.g. you will not be able to decrypt tampered payload).

You can do something like this if you really want:
```c#
string signed = JWT.Encode(payload, key, JwsAlgorithm.RS256);
string signedThenEncrypted =  JWT.Encode(signed, key , JweAlgorithm.RSA_OAEP, JweEncryption.A256GCM);
```

**Comment by MartyBJones** [comment]
I have the case where I am sending a JWT token to a third party.  We are
signing the token to make sure that it not tampered with but we also want
to encrypt the content so that it can't be viewed.

**Comment by dvsekhvalnov** [comment]
But encryption gives same anti-tampering protection :)

Is sample code answers your question?

**Comment by MartyBJones** [comment]
This is a third party service I am interfacing with so it is not my rules
for how they implement.  This does answer my question though.

**Comment by dvsekhvalnov** [comment]
Glad it working, closing for now.
