### ISSUE TITLE
Encode Decode with JWK

### ISSUE THREAD

**Issue by cpb089** [dvsekhvalnov/jose-jwt#128]
Hi,

Currently in order to encode and decode from JWK, I am converting the JWK to RSA(took it from             https://github.com/dvsekhvalnov/jose-jwt/issues/92#issuecomment-387982902) and then use the RSA key. This seems to be working in .net core 2, but converting JWK to RSA in .net core 3 prompts an error during runtime. Can you please suggest if there is an alternative to encode decode with a JWK?

![image](https://user-images.githubusercontent.com/8961621/79540937-3e297280-8089-11ea-9b3a-6ba4587bbfcb.png)

`private RSA GetRSAKeyfromJWK(JwkKey jwk)
        {
            byte[] p = Base64Url.Decode(jwk.p);
            byte[] q = Base64Url.Decode(jwk.q);
            byte[] d = Base64Url.Decode(jwk.d);
            byte[] e = Base64Url.Decode(jwk.e);
            byte[] qi = Base64Url.Decode(jwk.qi);
            byte[] dq = Base64Url.Decode(jwk.dq);
            byte[] dp = Base64Url.Decode(jwk.dp);
            byte[] n = Base64Url.Decode(jwk.n);

            RSA rsaKey = RSA.Create();
            RSAParameters keyParams = new RSAParameters
            {
                D = d,
                DP = dp,
                DQ = dq,
                Exponent = e,
                InverseQ = qi,
                Modulus = n,
                P = p,
                Q = q
            };

            rsaKey.ImportParameters(keyParams);

            return rsaKey;
        }`

**Comment by dvsekhvalnov** [comment]
Hi @cpb089 , 
it looks like either `e` or `n` are null or empty? Can you trace what those params actually are at runtime?

**Comment by cpb089** [comment]
hi @dvsekhvalnov ,

If i switch back my code to run in .net core 2 it works as it should. The problem is when switching my solution to .net core 3.

![image](https://user-images.githubusercontent.com/8961621/79542100-5601f600-808b-11ea-8d76-a5c05a369796.png)

**Comment by dvsekhvalnov** [comment]
Honestly i've never tried that conversion snippet with .net core 3 So it's hard for me to comment what may be broken.

I can give it a shot but it will take a while to set things up.

**Comment by dvsekhvalnov** [comment]
v4.0.0 released.
