### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by MatthiasJost** [dvsekhvalnov/jose-jwt#13]
Are there plans to support .NET Core. I know there are still in the beta phase, but for my project this would be a criteria, because we want to use .NET Core once all our dependencies are compatible with it.

**Comment by dvsekhvalnov** [comment]
Well, it can be interesting. I haven't thought about it yet actually. Even don't know at the moment what crypto primitives available for the platform.

Do you may be have an idea what it will take to support .net core? Would like to see it as separate standalone project?

Also i have PCL version here: https://github.com/dvsekhvalnov/jose-rt  not sure, can it fit your needs today?

**Comment by MatthiasJost** [comment]
As soon as all your dependecies are "Core Compatible" you can add both DNX references to your project. You might want to checkout the Preview template of the ASP.NET web pages in Visual Studio 2015 (ASP.NET). I think .NET Core is not yet finished but especially for Web Applications it will become crucial. Since the whole migrating to vNext in my opinion makes not that much sense when sticking to the full framework .NET Core for example has no more dependency to System.Web which makes the whole pipline a lot more streamlined and also host agnostic. Microsofts JWT Library is already compatible to it. But I found your library a lot more intuitive. I do not know if that helps anyhow but I guess they will need those "crypto primitives" too, so they are probably already available. I think it should be one project. See the project structure of an ASP.NET project. I do not know really if this RT version can help or is probably the base for this. Maybe someone else can give you a more specific answer on this. But I think it is time to look at it: The release of .NET Core is expected Q1 2016 (see: https://github.com/aspnet/Home/wiki/Roadmap). We already have Beta 7 now.

**Comment by dvsekhvalnov** [comment]
Yeah, the more i think about it, there more it make sense. So, answering your questions - yes, let's say i plan to support .NET core. Though i can't give any timeline at this point :)

So, i'll try to play around .net core to familiarize myself with latest changes.

Do you know if it is possible to have both .net framework (4.5.2 for instance) along with .net core on same box or it should be separate environment?

**Comment by MatthiasJost** [comment]
It can be in the same "box" or project. With vNext projects you can have both DNX 4.5.1 and DNX Core 5.0 referenced. They are then both defined in project.json (it is really completly deifferent than in previous Visual Studio versions).

**Comment by dvsekhvalnov** [comment]
Somehow got "hello world" working :)

Well, okay, let me play little bit with simple things to get feeling of new runtime and then i come back with some plan to support it.

**Comment by MatthiasJost** [comment]
Ohter libraries like like MongoDB driver do not yet support it too, but I guess that will change when the release candidate of DNX Core is here until then I need to use DNX 4.5.1 anyway.

**Comment by dvsekhvalnov** [comment]
Hey @MatthiasJost , decided to post little update. So i played little bit with netcore, nuget packaging, e.t.c. got it working on both win and osx.  

And i think i'll start v2.0 branch and try to re-create project to target both dnx451and dnxcore50 and then i should have list of things to update.

**Comment by MatthiasJost** [comment]
Sounds perfect @dvsekhvalnov. We are happy to hear that.

**Comment by dvsekhvalnov** [comment]
Wow. Finally get everything compiling and converted couple simple tests to xUnit. 100+ tests to go :)

**Comment by dvsekhvalnov** [comment]
@MatthiasJost pushed initial v2.0-netcore branch. It's compiling and passing all tests on CLR. Still need to adjust quite a lot of coreclr things. But if you want to try CLR - checkout appropriate branch.

**Comment by MatthiasJost** [comment]
@dvsekhvalnov sounds great. At the moment we cannot use CoreCLR anyway, not all libraries are adapting that fast :+1: It guess that will change soon, since RC1 is already out. But we are using your library in our project for a JWT based login mechanism. I like it since it is so easy to use and understand. Would it help the project if we do one or another test with it?

**Comment by leastprivilege** [comment]
Microsoft's JWT library is currently in a really bad state and it's looking worse the closer they get to their release date. They have issues like backwards comapt, trying to do SAML and JWT (and other things) and probably too many stakeholders etc.

It would be great to have a pure JWT focused library that works on the CLR and CoreCLR - I wouldn't mind if the CoreCLR version would have less features to start with.

I'd love to replace the MS JWT lib in IdentityServer v.next - but we need CoreCLR support (soon).

**Comment by dvsekhvalnov** [comment]
@MatthiasJost  sure go with testing. Appreciate it.

I don't think it make sense to publish package to nuget at this point. But you can checkout sources from v2.0-netcore branch and build. It should build jose-jwt  v2.0.0 .nupkg 

I'll start working on at least getting tests to compile on CoreCLR and then can start adding commented stuff back.

**Comment by leastprivilege** [comment]
How about you focus on the most commonly needed features first - that would be probably signing only - and support for HS256 and RS256. and then go from there.

**Comment by MatthiasJost** [comment]
Maybe there are just a few underlying issues and then everything else is solved then as a consequence. Like dependencies from System.Web or something? But I guess that is the case for ASP.NET applications. I would be surprised if there were a lot of incompatibilities beside of dependencies itself. Or are there other difficulties?

**Comment by dvsekhvalnov** [comment]
I'll start with signing for sure.  The issue right now is that something changed in keys management APIs and under coreclr it's not compiling. Need to address it first.

**Comment by kellermanrivero** [comment]
Signing is working actually. I downloaded the code, compile and test it and signing is working. Encryption isn't working, throw not implemented exceptions, maybe because some cryptographic classes are not present in coreclr yet (like ManagedAes).

**Comment by dvsekhvalnov** [comment]
Yep, i added bunch of not implemented exceptions to the places where there were no direct replacements in coreclr.  I believe there should be slightly different APIs from Microsoft as replacements but had no time end of year to address it.

If somebody wants to contribute - i'll appreciate :)

**Comment by dvsekhvalnov** [comment]
Hey folks, resurrected RS-256/384/512 and PS-256/384/512 signing algorithms for NET Core. As a key expects RSA instance (usually RSACng for netcore)

@MatthiasJost  what do you think if we drop dnx451 support and instead require dnx46/dnxcore50?  It looks API is much more aligned between two and will require less conditional code.

Also having different key types for different algorithms starting to be a mess. I have an idea to unify everything by expected CngKey instances.

**Comment by MatthiasJost** [comment]
@dvsekhvalnov Right now we are still using dnx451. Are there many changes? We use beta 8 library of ASP.NET. I need to upgrade this as well to release candidate. So however. For such a library the broader the compatibility is, the better. I am not sure what this would mean for compatibility to older .NET frameworks (pre VNext area). It will take a long time until everyone is in the "DNX/vNext world". But I consider upgrading in the next weeks to dnx46. As well as upgrading to the latest release candidate of ASP.NET.

**Comment by dvsekhvalnov** [comment]
Well, there is still 1.9 branch which is .NET Framework only and compatible with 4.0 and beyond.
So, v2.0 can support new dnx46 and netcore.  Just thoughts.

Ok, let's see how many differences will be in the encryption stuff.

**Comment by dvsekhvalnov** [comment]
Resurrected ES-256/384/512.  i think all signing (JWS) is so far supported for netcore. Will work little bit on updating and restructuring docs for v2.0

**Comment by dvsekhvalnov** [comment]
Resurrected DIR key management. AES-HMAC and AES-GCM encryption.

**Comment by dvsekhvalnov** [comment]
Resurrected RSA-OAEP-256, RSA-OAEP, RSA-PKCS1-V1_5 key management with AES-HMAC and AES-GCM encryption.

44 failed tests to go

**Comment by senwen** [comment]
@dvsekhvalnov, how is the port to dnxcore50 coming? MS JWT support for core is in a really bad state and I don't see them supporting encryption anytime soon. Thanks for your contribution!

**Comment by dvsekhvalnov** [comment]
Hi @senwen, and @MatthiasJost ,  

all JWS (signing) algorithms are supported for dnxcore50 right now. I'm slowly working on encryption, check this thread below, i'm posting updates here.

Haven't updated docs and publish to nuget.org yet, but if you want to try it out i've uploaded .nupkg to github, it is here: https://github.com/dvsekhvalnov/jose-jwt/raw/v2.0-netcore/jose-jwt.2.0.0.nupkg

Or you can build project yourself from v2.0-netcore branch.

Would appreciate any feedback so far if you try it.

**Comment by frapid** [comment]
I was wondering if a nuget package for .net core was already uploaded. Thank you.

**Comment by dvsekhvalnov** [comment]
Hi @frapid , i haven't published to nuget.org yet. Was hoping somebody can test it before. But looks nobody interested.

I can push to nuget.org if it is easier to try.

**Comment by MatthiasJost** [comment]
We planned to test it. We did not have the time yet. But we want to make a smaller test within the next days.

**Comment by frapid** [comment]
@dvsekhvalnov, that's a great idea. I will give it a try and submit feedback if the library is available in nuget.

**Comment by dvsekhvalnov** [comment]
ok, i'll push to nuget.org these week, no worries.

**Comment by senwen** [comment]
@dvsekhvalnov,
We've been using it without issues on RC1. It does not work on RC2 but we expected that since the compiler directives are branching on dnx451 and dnxcore50. We also stayed away from the encryption algos that were not implemented/ported yet. Thanks

**Comment by dvsekhvalnov** [comment]
Hi @senwen , can you give details on what's broken on RC2?

**Comment by frapid** [comment]
@dvsekhvalnov, thanks. Excited!!! Can't wait any longer!!!

**Comment by dvsekhvalnov** [comment]
okay, updated docs one more time.

want to do dry run before pushing on something other than windows (OSX probably).

**Comment by adimkov** [comment]
Hi, I am going to make a test with Jose JWT in March Insiders Preview of Visual Studio Code (I am in the team with MatthiasJost)

**Comment by dvsekhvalnov** [comment]
Hi @adimkov, thanks. Do you want to be on nuget.org or you can test local .nupkg?

**Comment by dvsekhvalnov** [comment]
I'm slightly concerned that current users of 1.9.x versions won't be able to upgrade to 2.0 via nuget. Because library is no longer target .NET Framework projects.

Should we consider creating new nuget package or it's ok? Anybody have thoughts on it?

**Comment by MatthiasJost** [comment]
Easy accessibility (nuget) of all "tastes" or versions of your library will dramatically improve the use of it in the wild. 
Everything that was here before "DNX" will continue to exist in most companies for years if not a decade.

**Comment by adimkov** [comment]
Hi @dvsekhvalnov, It would be more convenient to use a package from nuget.org.

**Comment by adimkov** [comment]
Hi @dvsekhvalnov. I tried to use jose-jwt.2.0.0.nupkg file from Github.com and it fails with this error:

`Errors in C:\Source\git\rc2\cli-samples\HelloMvc\project.json
    Package jose-jwt 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package jose-jwt 2.0.0 supports:
      - dnx451 (DNX,Version=v4.5.1)
      - dnxcore50 (DNXCore,Version=v5.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.`

**Comment by dvsekhvalnov** [comment]
@adimkov , what is netcoreapp1.0?

**Comment by dvsekhvalnov** [comment]
@MatthiasJost , i tend to agree with that. But it sounds packaging dnx451, dnxcore50 and net40 together getting slightly more complicated.. i wish there are clear docs on this.

**Comment by MatthiasJost** [comment]
Look at this video exactly at this position, it shows you where and what we downloaded:
https://www.youtube.com/watch?v=fkzeOqSNtwQ&feature=youtu.be&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&t=929 (Asp.net Community Standup)

**Comment by MatthiasJost** [comment]
@dvsekhvalnov You could ask this question in ASP.NET Community standup. They do sometimes FAQ (https://live.asp.net/). But docs for RC2 migration are announced by them.

**Comment by adimkov** [comment]
@dvsekhvalnov, Platform mapping names are changed. So for .NET framework 2 to 4.6, the name would be net20 – net46 and for .NET Core application, it would be netcoreapp. And that’s why you see netcoreapp present in framework section. And within this, you will also see “imports” section which has value like portable-net45+wp80+win8+wpa81+dnxcore50. And the description says that it allows packages supporting these frameworks to be installed in this target, regardless of compatibility rules.
Source: http://www.talkingdotnet.com/first-look-asp-net-core-1-rc2-project/

**Comment by dvsekhvalnov** [comment]
Ok, thanks guys, let me read all links you've posted and see if it helps.

@adimkov can you push your test netcoreapp solution somewhere so i can try it?

**Comment by frapid** [comment]
@dvsekhvalnov, I am trying to migrate a fairly complex project to .NET Core. Now, there are just 2 compile errors in my project. I am eagerly waiting to reference and test `jose-jwt` nuget package so that the compile errors would be gone. :)

I would like to try this out and submit feedbacks as I progress.

**Comment by dvsekhvalnov** [comment]
Ok, managed to get net40 back to project. Let's see what's happening with RC2.

**Comment by senwen** [comment]
@dvsekhvalnov,
Sorry I've been away for a few days. There has been some major renaming by the ASP.NET for RC2 as others have pointed out. It affects the compiler directives in jose-jwt since currently it is looking for dnx451 and dnxcore50 only. You will now need to account for other monikers as well. Our internal project has other nuget packages we are using such as Swashbuckle so we are holding off on RC2 migrations until all packages support RC2.

**Comment by dvsekhvalnov** [comment]
Ok, guys, help me understand (all news are so controversial):  RC2 is basically deprecating dnx and dnxcore in favor of new platform ids? So no need to support it in library anymore?

Also did i get it right that DNVM tool is also retired and RC2 should be installed separately (not an upgrade)?

**Comment by MatthiasJost** [comment]
"For RC2 we will move ASP.NET Core 1.0 to be based on the new cross-platform .NET Core command line toolchain."

If you look here: https://github.com/aspnet/dnx (DNX Repository)

They clearly say "retired".

> replace DNX, DNU – these tools just go away
> some portions of source code have been copied
> like DNX and DNU – tools designed to be used by humans
[...]
> _version handling DNVM like tool? DNVM still under considerations. Main question is how tool like DNVM will find it’s place to switch between toolchains._

Source: http://bleedingnedge.com/2016/02/04/new-toolchain-dotnet-cli/

So Situation seemed not yet clear at the moment they wrote this article. I have no information that is more recent. Maybe you would find it in the Community Standup Meetings on Youtube.

**Comment by adimkov** [comment]
@dvsekhvalnov I pushed sample to GitHub repository https://github.com/adimkov/Samples
You can try it.

**Comment by dvsekhvalnov** [comment]
Thanks @adimkov , what Visual Studio this project is?  Can't open with mine VS2015 Community.

I think i've installed RC2 for now, trying to get any idea what VS version supports tooling (if any) and how to target new NETCore RC2

**Comment by adimkov** [comment]
@dvsekhvalnov, Now there are some problems with this. Visual Studio at the moment (to my knowledge) does not support the RC2. To work with this type of project, you must use the [VS Code Insider Preview](https://code.visualstudio.com/Download#insiders). The project, which I pushed in the repository, was created using VS Code.

**Comment by MatthiasJost** [comment]
The "Visual Studio tooling" for new "dotnet" CLI is planned to be available in mid June. Meanwhile you can use command line (dotnet SDK) or Visual Studio Code (which also uses this SDK).

**Comment by dvsekhvalnov** [comment]
wow, so inconsistent. Ok, trying VS Code.

**Comment by MatthiasJost** [comment]
Hehe yes. Visual Studio Code is not even similar to Visual Studio (only by the name).

**Comment by senwen** [comment]
@dvsekhvalnov , tooling for Visual Studio and RC2 Preview has been released - https://www.microsoft.com/net/core#windows
 
I got my local fork working in Visual Studio now. Previously I had to use DNU/DNIX (rc1) and DOTNET (rc2) command line.

**Comment by dvsekhvalnov** [comment]
@senwen thanks, i'll try to update my VS once again

**Comment by dvsekhvalnov** [comment]
@adimkov , @MatthiasJost  it looks i updated for **netcoreapp1.0** target. At least was able to run simple console app with it.

I've uploaded .nupkg here: https://github.com/dvsekhvalnov/jose-jwt/blob/master/jose-jwt.2.0.0.nupkg

Or if you clone **v2-netcore** branch, you should be able to build it with dotnet cli:

1. cd jose-jwt
2. dotnet restore
3. dotnet pack -c Release

Looking how to add unit tests for netcoreapp target

**Comment by senwen** [comment]
@dvsekhvalnov ,
I've been using these two packages for unit tests on dotnet core.
    "xunit": "2.1.0-*",
    "dotnet-test-xunit": "1.0.0-rc2-*"

You'll need https://www.myget.org/F/coreclr-xunit/api/v3/index.json feed for dotnet-test-xunit.

Also moq port for dotnet core is useful:
    "moq.netcore": "4.4.0-beta8"

**Comment by leastprivilege** [comment]
https://xunit.github.io/docs/getting-started-dotnet-core.html

**Comment by kukjevov** [comment]
Hi i`ve tested on .net core version 2.0.0 of your library and it works exactly as i need it :), just great.

Thank you very much :)

**Comment by dvsekhvalnov** [comment]
Ok, anybody else? Another +1 for .netcoreapp1.0 ?

**Comment by murilocurti** [comment]
+1 !
Can you publish it on nuget.org as a pre-release?

**Comment by a3nick** [comment]
+1!

**Comment by dvsekhvalnov** [comment]
Ok, working on this guys. Thanks.

**Comment by escamoteur** [comment]
Would be really great!

**Comment by dvsekhvalnov** [comment]
On it. Preparing for initial nuget release.

**Comment by psibernetic** [comment]
Any news on this @dvsekhvalnov ? I'm pumped to use the codebase, going to port a SaaS solution to core, this is the next to last library I need! Thanks for your hardwork!

**Comment by dvsekhvalnov** [comment]
Hey, yeah actually `v2-netcore` branch in good shape (still not all algos, but anyway), restored .net4 compatibility and unit tests.

The one thing that's i'm not sure if library should target `netcoreapp1.0` or `netstandard1.3`.  Currently `netcoreapp1.0`, but it looks it is more for apps than libraries. Documentation is so unclear ( 

So, my plan is to play little bit around `netstandard` targeting and finally push it out to nuget.org

**Comment by psibernetic** [comment]
It is definitely the netstandard1.3 for libs.

**Comment by sandersaares** [comment]
Yes, netstandard is the way to go. The [.NET Core Slack channel](http://tattoocoder.com/aspnet-slack-sign-up/) tends to be very helpful in figuring out this sort of thing - I can recommend it as a useful resource for getting to know the new .NET universe.

**Comment by dvsekhvalnov** [comment]
Ok, .netstandard1.4 will it be. Sorry 1.3 missing ECDSA classes (

Anybody is still interested in dnx451 or dnxcore50 targeting? Want to remove them completely.

**Comment by MatthiasJost** [comment]
We are still interested in .NET Core. But I do not know what this means in terms of target names.

**Comment by kukjevov** [comment]
Well you can safely remove dnx451 and dnxcore50, if somebody still uses .NET RC1 he will upgrade soon, but i doubt that there is somebody who did not upgraded. And for users using RC2 or RTM those targets has no meaning. I think you can remove them.

**Comment by psibernetic** [comment]
1.3 is hard to target, no worries @dvsekhvalnov.

**Comment by brightertools** [comment]
Hi, is there any time line on .net core support?

**Comment by dvsekhvalnov** [comment]
hi @brightertools , most likely will push to nuget first version next week. Almost there.

**Comment by mredman** [comment]
That will be great...

I have recently looked at Auth0, which mentioned your library, After you update, do you know if I will I be able to generate RS256 tokens to connect to their ManagementApi?  

Thanks, for the update.

**Comment by dvsekhvalnov** [comment]
RS256 - definitely.

Some key management algos for encryption are not yet supported or missing
in framework.

**Comment by dvsekhvalnov** [comment]
Ok, merged stuff to master. Coming close.

**Comment by dvsekhvalnov** [comment]
Hey guys, i finally pushed package to nuget.org: https://www.nuget.org/packages/jose-jwt/

But it looks `dotnet restore` doesn't want to fetch the package. Though VS can perfectly do it and after it available to local `.nuget` cache.

Can somebody verify? (or better shed some light on what i did wrong with publishing)

**Comment by psibernetic** [comment]
May just take a minute to update the remote stores.

**Comment by psibernetic** [comment]
Probably need to determine actual dependencies too.

![image](https://cloud.githubusercontent.com/assets/621605/17309488/b5e765e0-5804-11e6-917c-541c590c9ee1.png)

**Comment by dvsekhvalnov** [comment]
@psibernetic , didn't get it. What's wrong with NETStandard.LIbrary 1.6 ?

**Comment by psibernetic** [comment]
It is recommended when publishing to determine which pieces of NETStandard.Library your library actually uses (derived from project.lock.json) and reference those specifically. Matching the Pay To Play model.

**Comment by dvsekhvalnov** [comment]
Is it the reason, why `dotnet restore` can stop working?

**Comment by psibernetic** [comment]
Sorry, no, that wasn't clear!

**Comment by dvsekhvalnov** [comment]
Ok, so can somebody try to install package via `dotnet restore` and tell if it is working or failing?

**Comment by psibernetic** [comment]
It works for me v2.0.1

![image](https://cloud.githubusercontent.com/assets/621605/17309723/cb9a3614-5805-11e6-91f2-fefdf90bec43.png)

**Comment by dvsekhvalnov** [comment]
Is it Visual Studio?

It's working for me in VS as well. But was not working if i did just `dotnet restore` from command line. May be i need to get clean VM..

**Comment by psibernetic** [comment]
That was in VS CODE dotnet restore.

**Comment by dvsekhvalnov** [comment]
Ok. I actually got it working with OSX version.

But waiting for couple more people to confirm it is working :)

**Comment by senwen** [comment]
@dvsekhvalnov , we restored 2.0.1 successfully on Windows, Mac and Ubuntu inside Docker container and passed our CI-CD unit and integration tests. Thanks!

**Comment by daMupfel** [comment]
Working for me in osx as well. Tested directly from command line.

**Comment by dvsekhvalnov** [comment]
Cool, thanks all.

Ok, i'll keep this issue open while working on adding more algos for netcore version. 

If anybody experience troubles let me know.

**Comment by mredman** [comment]
Thanks for the update @dvsekhvalnov, this is working for me in VS.

**Comment by kukjevov** [comment]
Thanks, working great in VS and with dotnet restore :).

**Comment by psibernetic** [comment]
This has been working well for 2 months now, should probably close this issue and enjoy your success! @dvsekhvalnov As we found on the linux support issue #45, separate issues for algorithm support would make that clearer, or at least just link to them. Just my 2 cents, but thanks for your work on this.

**Comment by dvsekhvalnov** [comment]
Yeah, i'll split this one into multiple smaller issues to address what is not yet supported.

Thanks for feedback !

**Comment by dvsekhvalnov** [comment]
Finally closing in favor of #45 and #46
