### ISSUE TITLE
Any new release Plan for .net standard 2.0 or plus. (.net core 3.1 without newtonsoft)

### ISSUE THREAD

**Issue by KamranShahid** [dvsekhvalnov/jose-jwt#130]
Any new release Plan for .net standard 2.0 or plus. (.net core 3.1 without newtonsoft)?

**Comment by dvsekhvalnov** [comment]
Hi @KamranShahid , 
kind of planning to take a look this year, but no strict ETA at this point. 

What an issues with newtonsoft?

**Comment by KamranShahid** [comment]
not much of any issue in newtosnsoft. from .net core 3.1 i am just using builtin system.text.json for all the work.

**Comment by dvsekhvalnov** [comment]
Ah, okay i see,  there were no native json support in .net core 2 so that's why it coming with newtonsoft json by default.

Yeah perfectly make sense to me to drop another dependency.

**Comment by themedes** [comment]
Is there any plans to do this any time soon? its been nearly a year since this was raised and it would be good to move my project into latest .net

**Comment by dvsekhvalnov** [comment]
Hi @themedes, v3 is supporting latest .netcore v3. We going to drop mandatory dependency of newtonsoft probaly in v3.2

v3.1 will be Jwe Json serialization support release.

Are you looking for some other feature request?

**Comment by themedes** [comment]
> Hi @themedes, v3 is supporting latest .netcore v3. We going to drop mandatory dependency of newtonsoft probaly in v3.2
> 
> v3.1 will be Jwe Json serialization support release.
> 
> Are you looking for some other feature request?

Awesome thanks i missed that!

**Comment by olivier-spinelli** [comment]
Hello, 
I'm very interested in a System.Text.Json only solution (too many compatibility/version issues with the Json.net in the past). Is there a branch from which I may start and (hopefully) submit one or more PR on this subject?

And many thanks for your work!

**Comment by dvsekhvalnov** [comment]
Hi @olivier-spinelli , 

feel free to open PR if interested :)

`master` currently little bit unstable as trying to prepare JWE Json serialization support for release. But Json serialization seems to be isolated enough. At worst i'll can manually port changes over.

**Comment by dvsekhvalnov** [comment]
@robmen thank you for your contribution !

All please find v3.2 on nuget with `System.Text.Json` support (also CC: @isenmann)
