### ISSUE TITLE
Confused due to the exception 

### ISSUE THREAD

**Issue by Wadeed123** [dvsekhvalnov/jose-jwt#131]
So i am implementing tokenization for a client, my rest api is being consumed by the client and and they are sending a token in their request for some reason my api is unable to decode that token we used a shared certificate for encryption and decryption. My api is in C# using jose-jwt while client might be having a java application. The exception i am getting is mentioned below:
JWT header: {"alg":"RSA-OAEP-256","enc":"A256GCM"}

System.Security.Cryptography.CryptographicException: NCrypt.Decrypt() (plaintext buffer size) failed with status code:2148073511
   at Jose.RsaOaep.Decrypt(Byte[] cipherText, CngKey key, CngAlgorithm hash) 

can someone please elaborate this exception can not find any explanation.

**Comment by dvsekhvalnov** [comment]
Hi @Wadeed123 , 

library can't decrypt your token. May be invalid format/padding or whatever else.

To troubleshoot feel free to post sample token and decryption key. Please make sure this is not **production** key before sharing.

Also if you can share java side code that producing token can be helpful as well (at least what library you are using to produce token).

**Comment by Wadeed123** [comment]
Thank you for the response @dvsekhvalnov,
Yup i cannot share the key or even token as it consist of personal data.
The Java library they are using : [import com.nimbusds.jose.*;].

**Comment by dvsekhvalnov** [comment]
Probably you can generate test keys and provide sample token with it without PII data?

We do cross-compatibility tests with https://connect2id.com/products/nimbus-jose-jwt  so it all should work with your case.

It's really hard to diagnose without any samples. As an idea may something happening during token transmission and it gets corrupted or re-encoded (base64, e.t.c.) ?

**Comment by Wadeed123** [comment]
Let me see what is possibly.
for and idea if it is getting re-encoded so before decryption i have to apply base 64 decoding and pass the resultant the string as to the decode function.
Will try this and update the thread.

Any idea of ChilKat.JWE is it different from JOSE-JWT ?

**Comment by dvsekhvalnov** [comment]
Can't comment on ChilKat, have never tried it.

**Comment by KamranShahid** [comment]
> Let me see what is possibly.
> for an idea if it is getting re-encoded so before decryption i have to apply base 64 decoding and pass the resultant string to the decode function.
> Will try this and update the thread.
> 
> Any idea of ChilKat.JWE is it different from JOSE-JWT ?

I think it is paid library.

**Comment by Wadeed123** [comment]
Closing issue, apparently the client ended up sharing the wrong Key pair that was causing the problem.  Exception was a bit vague but nonetheless it was issue at our end.

Thank you for bearing with me.
Kudos to @dvsekhvalnov.
