### ISSUE TITLE
Creating JWS with empty "" payloads

### ISSUE THREAD

**Issue by OwlScowl** [dvsekhvalnov/jose-jwt#136]
Hello,

I'm confronted to an API that uses JWS on their GET requests meaning no body.

There is a check in the JWT.Encode method preventing this behavior. Could the check for an empty payload be removed ?

It seems to be a rather recent developement  (~1 year) that can be seen in this rfc https://tools.ietf.org/id/draft-ietf-acme-acme-16.html#rfc.section.6.3.

I'm currently using .NET standard 4.6.2 with jose 2.5.0

Thanks for the work,

**Comment by dvsekhvalnov** [comment]
Hi @OwlScowl ,

are you asking for detached payload (it is supported https://github.com/dvsekhvalnov/jose-jwt/#unencoded-and-detached-content-aka-rfc-7797) or how would you expect it work? 

In a sense if you don't provide body, what you expect signature to be based off? Just headers?

**Comment by OwlScowl** [comment]
Hello @dvsekhvalnov,

Yes the signature is based solely on the headers.

I'm integrating a API that uses JWS signature with detached payload. This works flawlessly with POST since there are bodies, but it has a few GET/DELETE requests with blank payloads.

With curl, these requests would look like this:

curl -X DELETE
  https://myapi.com
  -H 'Signature: xxxxxxxx..xxxxxxxxxxxx'

Thanks for taking the time to answer,

**Comment by dvsekhvalnov** [comment]
Hm.. ok, let me check how others jwt implementations addressing it (empty payload) that i'm usually cross-test against.  Seems important to be compatible here.

**Comment by OwlScowl** [comment]
I've looked at it before creating this issue, to be sure I wasn't the only one with this demand. This library creates an extra parameter allowing, or not, blank payloads. It is false by default.

https://github.com/nov/json-jwt/issues/69

**Comment by dvsekhvalnov** [comment]
ok, interesting. Let me dig others too :) Will get back to you.

**Comment by dvsekhvalnov** [comment]
@OwlScowl , checked other libs - looks like all supporting it as valid use case. So don't see reasons why not to update jose-jwt too. Will make a fix.

**Comment by OwlScowl** [comment]
For other people having the same issues, you can create an empty payload in bytes

```
  var emptypayload = Encoding.UTF8.GetBytes(string.Empty);
  newJws = JWT.EncodeBytes(emptypayload, ecdsapriv, JwsAlgorithm.ES256, headers.data, null, new JwtOptions { DetachPayload = true });
```

**Comment by dvsekhvalnov** [comment]
That reminds me i need to make a release 🤦

**Comment by dvsekhvalnov** [comment]
Released: 
https://github.com/dvsekhvalnov/jose-jwt/releases/tag/v2.6.0
https://www.nuget.org/packages/jose-jwt/2.6.0

@OwlScowl check it out and sorry for delay.
