### ISSUE TITLE
Invalid signature 

### ISSUE THREAD

**Issue by ahvahsky2008** [dvsekhvalnov/jose-jwt#138]
I try convert this code to jose-jwt [github gist](https://github.com/bitzlato/api-auth-examples/blob/625f16a3682d775e65466e0cd0d4f1b94787fe43/csharp/TokenDemo/Program.cs)

**jwt.io** says that my token is invalid. Why so?

```
string PrivKey = "{" +
    "\"kty\":\"EC\",\"alg\":\"ES256\",\"crv\":\"P-256\"," +
    "\"x\":\"pSH0jvbtVZiseTpJZk0_yfudEIv86uwjeH_gr1qmOGA\"," +
    "\"y\":\"eGdC9EIGmhCheM_T8vhS4Qwk7RfaPRBxF3W5omgBc_M\"," +
    "\"d\":\"DuSjR5eZBp5S-9HNKA8kRQFA_3Akkept-dTbwFoq_3w\"" +
    "}";

var js = new JavaScriptSerializer();
var jwk = js.Deserialize<IDictionary<string, string>>(PrivKey);


byte[] x = Base64Url.Decode(jwk["x"]);
byte[] y = Base64Url.Decode(jwk["y"]);
byte[] d = Base64Url.Decode(jwk["d"]);

var payload = new Dictionary<string, object>()
    {
        { "email", "bitzlato.demo@gmail.com" },
    };

var privateKey = EccKey.New(x, y, d);

string token = Jose.JWT.Encode(payload, privateKey, JwsAlgorithm.ES256);

HttpClientHandler handler = new HttpClientHandler()
{
    Proxy = new WebProxy("http://127.0.0.1:8888"),
    UseProxy = true,


};
var httpClient = new HttpClient(handler);

httpClient.DefaultRequestHeaders.Authorization =
    new AuthenticationHeaderValue("Bearer", token);

var who = Task.Run(async () => await
    httpClient.GetStringAsync("https://demo.bitzlato.com/api/auth/whoami")
).GetAwaiter().GetResult();

```

**Comment by OwlScowl** [comment]
It's working for me. I can't upload a screenshot however0

You have to check the JWT against a public key (in this case a public key is just a private key with fewer informations)
To get the public key, just remove the d element and you'll get signature verified as well, but you can use the private key as well.

If you read what's written in the private key verification text box:
`Private Key. Enter it in plain text only if you want to generate a new token. The key never leaves your browser.
It basically says to only use this text box if you want to generate the token. Were you using this box perhaps ?

**Comment by ahvahsky2008** [comment]
> It's working for me. I can't upload a screenshot however0
> 
> You have to check the JWT against a public key (in this case a public key is just a private key with fewer informations)
> To get the public key, just remove the d element and you'll get signature verified as well, but you can use the private key as well.
> 
> If you read what's written in the private key verification text box:
> `Private Key. Enter it in plain text only if you want to generate a new token. The key never leaves your browser. `It basically says to only use this text box if you want to generate the token. Were you using this box perhaps ?

globally - i want repeat token generation and it with params to rest api. 
server receive **JWT** generated token correctly. But generated with jose-jwt  - it says `{"error":"Unauthorized","message":"An error occurred while attempting to decode the Jwt: Malformed payload"}`

**Comment by OwlScowl** [comment]
I'm guessing you are using this example https://github.com/bitzlato/api-auth-examples/blob/develop/csharp/TokenDemo/Program.cs

If you are, you are missing all these informations in the payload: 
```
                Algorithm = SignatureAlgorithm.EcdsaSha256,
                IssuedAt = DateTime.UtcNow,
                Audience = "usr",
                JwtId = Rnd.Next().ToString("X"),
                // Optionally set kid if you've got more than one key. Provide the correct int value.
                // see: https://tools.ietf.org/html/rfc7515#section-4.1.4
                KeyId = 2.ToString()
```

Create a Dictionnary<string, object>() with all these informations and encode the jwt like this

`var newJws = JWT.Encode(payload, privkey, JwsAlgorithm.ES256, headers);
`
I couldn't find an english documentation of the API, but it should say what information is required to make a call

**Comment by dvsekhvalnov** [comment]
Hi @ahvahsky2008 , 

i don't have any issue with your code, it producing perfectly valid signature, doubled checked with couple others jws implementations.

**Comment by dvsekhvalnov** [comment]
closed due to inactivity, feel free to re-open if still an issue.
