### ISSUE TITLE
Validate without decoding

### ISSUE THREAD

**Issue by alex-jitbit** [dvsekhvalnov/jose-jwt#139]
Currently I have to use `try-catch` to know if the token signature is valid or not. That's not very good design (basing logic on exceptions is bad practice).

Is there a way to simply validate a token?

**Comment by dvsekhvalnov** [comment]
Hi @alex-jitbit , 

what do you mean by validating without decoding? 

For signed tokens - you not decoding anything, nothing prevents you to grab payload that is plain text.
For encrypted tokens - well, it doesn't make any sense without decoding.

**Comment by alex-jitbit** [comment]
I meant, validate the signature only, and that's it. How do I tell if the token is valid?

**Comment by dvsekhvalnov** [comment]
```c#
string payload = Jose.JWT.Decode(token, key);
```

will essentially do signature verification on signed tokens and return you payload :) one liner :)

After that your mileage may vary based on type of payload. For instance if you dealing with JWT tokens you normally will parse payload and apply additional validation logic on claims (check valid time range, audience, issuer, whatever else). 

To answer original question about changing signature or introducing new method (`bool IsValid(...)`). It's probably too trivial wrapper to include in library. 

From library perspective i'd prefer keep interface uniform across both signing, encryption and compression, as `IsValid()` doesn't make any sense within encryption context.

**Comment by dvsekhvalnov** [comment]
closed due to inactivity, feel free to re-open.
