### ISSUE TITLE
Why managed crypto implementations instead of CSP or CNG?

### ISSUE THREAD

**Issue by SteveSyfuhs** [dvsekhvalnov/jose-jwt#14]
I noticed there's a few places where XXXManaged implementations are being used instead of CSP or CNG. Is there a particular reason for that? Would it be reasonable to switch those out to use CSP or CNG? I've got a fork where I've been testing these changes: https://github.com/dvsekhvalnov/jose-jwt/compare/master...SteveSyfuhs:feature/convert-to-provider

E.g.

https://github.com/dvsekhvalnov/jose-jwt/blob/a77bc9bec23964cceb58fe2b581250672ab9667b/JWT/jwe/AesCbcHmacEncryption.cs
https://github.com/dvsekhvalnov/jose-jwt/blob/a77bc9bec23964cceb58fe2b581250672ab9667b/JWT/crypto/AesKeyWrap.cs
https://github.com/dvsekhvalnov/jose-jwt/blob/a77bc9bec23964cceb58fe2b581250672ab9667b/JWT/jws/RsaUsingSha.cs

**Comment by dvsekhvalnov** [comment]
Hi @SteveSyfuhs,

well really no special reason, probably it was easier or just historically happened. 

Is there are any benefits that you see in switching implementations? E.g. faster, more secure, more portable, e.t.c.?

**Comment by SteveSyfuhs** [comment]
Switching to CSP or CNG would provide a performance boost since it'll use native code and it would allow the code to run in FIPS-compliant mode. It does limit portability relatively speaking, but the BCrypt and NCrypt P/Invoke are already the limiting factor for that.

**Comment by dvsekhvalnov** [comment]
Okay, sounds reasonable too me. As long as all unit tests are passing submit a merge request, i'll merge it.

**Comment by dvsekhvalnov** [comment]
@SteveSyfuhs , wanted to check with you. Are you going to submit merge request or expecting me to fix changes you mention? 

Thanks.

**Comment by dvsekhvalnov** [comment]
v2.1 released to nuget.org
