### ISSUE TITLE
ECDsa does not work as key for JWT.Encode

### ISSUE THREAD

**Issue by ardove** [dvsekhvalnov/jose-jwt#140]
Using some code which looks like the following, you end up with an exception which mandates that the key must be of type CngKey. The documentation clearly states that the key may be of type CngKey OR ECDsa. Sending an instance of an ECDsa hydrated using the following code does NOT work.

Am I missing something or is the documentation incorrect?
  
```
var base64Key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEENgj/ekevMS8A7DIFSeCSRs2EyYvmWi5tPflzr0Js9tMcMnfXkyW9jBeN4+k+hxoDq+riyKBy87e6WQ/VRpxUg==";
var keyBytes = Convert.FromBase64String(base64Key);
var decryptionKey = ECDsa.Create();
decryptionKey.ImportSubjectPublicKeyInfo(keyBytes, out int _);

var sensitivePayload = "super secret text";
Jose.JWT.Encode(dataToBeEncrypted, key, JweAlgorithm.ECDH_ES_A256KW, JweEncryption.A256CBC_HS512);
```

**Comment by ardove** [comment]
Ok, I answered my own question, I think. The key needs to be imported used ECDsa but converted to a CngKey before it can be used for encoding data. 

```
var ecdsa = ECDsa.Create();
ecdsa .ImportSubjectPublicKeyInfo(encryptionKeyBytes, out int _);

var keyParams = decryptionKey.ExportParameters(false);
encryptionKey = EccKey.New(keyParams.Q.X, keyParams.Q.Y, keyParams.D, CngKeyUsages.KeyAgreement);
```

This actually throws an exception, but i'm okay with the behavior because you wouldn't normally use this for encryption since it's really a signature algorithm. Carry on.

**Comment by dvsekhvalnov** [comment]
Hi @ardove  

ECDH + AES KeyWrap only supports `CngKey` type of key.
https://github.com/dvsekhvalnov/jose-jwt#ecdh-es-and-ecdh-es-with-aes-key-wrap-key-management-family-of-algorithms

You probably mixed it up with ES256 signing that supports both types of keys if you running on .net4.6+ or .netstandard 1.4

**Comment by ardove** [comment]
Yeah, that's exactly what I did. Thanks!
