### ISSUE TITLE
Sha512 Typo

### ISSUE THREAD

**Issue by JohnS-dev** [dvsekhvalnov/jose-jwt#144]
https://github.com/dvsekhvalnov/jose-jwt/blob/4925258f5053fdc6551c0033c16594ca799ac817/jose-jwt/jws/EcdsaUsingSha.cs#L66

**Comment by dvsekhvalnov** [comment]
Hi @JohnS-dev, can you elaborate on it little bit? What makes you think there is typo and what kind of typo?

**Comment by JohnS-dev** [comment]
Should it be 512 instead of 521?

**Comment by dvsekhvalnov** [comment]
No, according to spec:
```
For ECDSA P-521 SHA-512, R and S will be **521** bits each, resulting in a 132-octet sequence. 
```

https://tools.ietf.org/html/rfc7518


Are you experiencing any compatibility issues with other implementations?
