### ISSUE TITLE
Question: Is there a reason for using static readonly instead of const?

### ISSUE THREAD

**Issue by csrakowski** [dvsekhvalnov/jose-jwt#145]
Hi,
I was wondering if there is a specific reason some fields on the BCrypt class are `static readonly` instead of `const`, eg: [`BCrypt.BCRYPT_OBJECT_LENGTH`](https://github.com/dvsekhvalnov/jose-jwt/blob/master/jose-jwt/native/BCrypt.cs#L14)?

**Comment by dvsekhvalnov** [comment]
Hi @csrakowski , probably no. Is it causing any issues?

**Comment by csrakowski** [comment]
Hi @dvsekhvalnov,

No, no issues.
I was just browsing the code and Visual Studio came with the suggestion to consider switching it to `const`, which is a good suggestion.
Theoretically there may be a small performance improvement if the compiler inlines it, but since the actual encryption still takes most of the time, that will probably not be noticable.

I have a branch prepared with the change, so I could open a pull request if you want to take a look at it?

**Comment by dvsekhvalnov** [comment]
Sure thing @csrakowski , PRs always welcome :)

**Comment by dvsekhvalnov** [comment]
Thanks man. Will release as part of 2.6.1

**Comment by csrakowski** [comment]
Cool, thank you as well :-)

**Comment by dvsekhvalnov** [comment]
v2.6.1 released.
