### ISSUE TITLE
Outdated Encryption Algorithm?

### ISSUE THREAD

**Issue by phillipells** [dvsekhvalnov/jose-jwt#152]
Hi so we were using your library for generating tokens and we noticed an issue pop up. Our tokens were suddenly being generated with no payloads when using this encryption scheme: JweEncryption.A128CBC_HS256

```
public void Encrypt_DIR_A128CBC_HS256()
{​​​​
 byte[] aes256Key = new byte[] {​​​​​ 164, 60, 194, 0, 161, 189, 41, 38, 130, 89, 141, 164, 45, 170, 159, 209, 69, 137, 243, 216, 191, 131, 47, 250, 32, 107, 231, 117, 37, 158, 225, 234 }​​​​​;
// //given
 string json =
 @"{​​​​​""exp"":1389189552,""sub"":""alice"",""nbf"":1389188952,""aud"":[""https:\/\/app-one.com"",""https:\/\/app-two.com""],""iss"":""https:\/\/openid.net"",""jti"":""e543edf6-edf0-4348-8940-c4e28614d463"",""iat"":1389188952}​​​​​";

 // //when
 string token = Jose.JWT.Encode(json, aes256Key, JweAlgorithm.DIR, JweEncryption.A128CBC_HS256);
 // //then
 Console.Out.WriteLine("DIR_A128CBC_HS256 = {​​​​​0}​​​​​", token);
 }​​​​​
```
Your example in your documentation would also fail:
```
ar payload = new Dictionary<string, object>()
{
    { "sub", "mr.x@contoso.com" },
    { "exp", 1300819380 }
};

var secretKey = new byte[]{164,60,194,0,161,189,41,38,130,89,141,164,45,170,159,209,69,137,243,216,191,131,47,250,32,107,231,117,37,158,225,234};

string token = Jose.JWT.Encode(payload, secretKey, JweAlgorithm.DIR, JweEncryption.A128CBC_HS256);
```

Switching to another encryption scheme seems to solve our problems, but I wasn't sure if you were aware of something changing with the underlying microsoft cryptography libraries.

**Comment by dvsekhvalnov** [comment]
Hi @phillipells ,

mind posting output you getting (e.g. serialized token) ?

I've tried on .net4.7 and .netcore 3 (all windows 10, latest patches) and getting as expected (also unit tests are passing just fine):

```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..UWJBv3BAW3PGzUz-2DD9HA.Y-GcUNrqmPYcy6O4molHUl9krux8EZJTtsEDQbk9Zv221Ee3hhnx0m_YZvi4jWhaspYSeQ7iGLdCAbR1ZHILz5fQnSOUn7nVh7533-4fEJ8T9e8DPxDrUhmXFFUBYLo07R8GfvFX3s6khEl7Nt319DWWbANSykZqywnzQttB-yh8cBuCoII2xnILT7g9V_GlrrYpcN2splsy7z4xBM3AG0dRDYjdpvCxptPxt62P2e-2WlK3MeYzrjXjA5Cx7u7v8kW8S5jXfQNZWU83zew_I3FUUoVtzjfwANqj45v-PVSy2OtWfTpu7Y4QjOwdcSIL.Pk45Dxpjvh3a-44OCKW4Dg 
```

**Comment by phillipells** [comment]
Hi @dvsekhvalnov,

First off, I'm sorry for wasting your time on this. Just did some and it was a combination of things on our end. 
1. I misunderstood the different in format between a JWT and JWE
2. Someone had committed a breaking change in our system related to user identity that led to this

Again sorry for wasting your time. Closing the issue

**Comment by dvsekhvalnov** [comment]
No worries :)
