### ISSUE TITLE
Jose.InvalidAlgorithmException JWA algorithm is not supported: http://www.w3.org/2001/04/xmlenc#rsa-oaep

### ISSUE THREAD

**Issue by hiteshsalian** [dvsekhvalnov/jose-jwt#161]
Hi,
We are facing issue while decrypting/decoding the JWE token issued by Microsoft's default token implementation . i.e. JwtSecurityTokenHandler.CreateEncodedJwt(securityTokenDescriptor)

**1) Tried using Jose.JWE.Decrypt()method**
**_var token = Jose.JWE.Decrypt(encryptedToken, privateKey);_**

**Exception Details**
```
Jose.InvalidAlgorithmException: JWA algorithm is not supported: http://www.w3.org/2001/04/xmlenc#rsa-oaep.
   at Jose.JwtSettings.JwaAlgorithmFromHeader(String headerValue)
   at Jose.JWE.Decrypt(String jwe, Object key, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings)

```
**2) Tried using Jose.JWT.Decode() method**
**_var token = Jose.JWT.Decode(encryptedToken, privateKey);_**

**Exception Details**
```
Jose.InvalidAlgorithmException: JWA algorithm is not supported: http://www.w3.org/2001/04/xmlenc#rsa-oaep.
   at Jose.JwtSettings.JwaAlgorithmFromHeader(String headerValue)
   at Jose.JWE.Decrypt(String jwe, Object key, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings)
   at Jose.JWT.DecodeBytes(String token, Object key, Nullable`1 expectedJwsAlg, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings, Byte[] payload)
   at Jose.JWT.Decode(String token, Object key, JweAlgorithm alg, JweEncryption enc, JwtSettings settings)
```
   
**As per code, Jose.JWT's JweAlgorithm does not support Microsoft's RsaOaepKeyWrap algorithm**

Please provide your suggestion to resolve this issue.

Thank you.

**Comment by dvsekhvalnov** [comment]
Hi @hiteshsalian , 

mm, mind posting example token?

`http://www.w3.org/2001/04/xmlenc#rsa-oaep` sounds like XML Encryption, not JSON Web Encryption.

**Comment by hiteshsalian** [comment]
Hi @dvsekhvalnov 


**Sample Token :** eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGVuYyNyc2Etb2FlcCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJraWQiOiJBNDBCRDlDRjY1RDkwNENDOURGRTZFRjdEQjcyMTE4NTQ3OEM1RUVEIiwidHlwIjoiSldUIn0.ZaZXVI4HLfJKnRugeufY9Gl_Ts7p7ZN_FtLJvJ-13kzkHr4coMDuqeyjEyEr1zgWlOCDs3vKqqmIjbCbrz7POQAo_1T5Xb_GZONAAkpzUpwI1syWs2nJkiBm4FsyAsU4MBGp_pbCjzlN2hVa--a7tnEZ1pY-p68j9GAMAddJgCHM-SDvXFAv47PovZEsV_4Laz26Mlit4OiPaDtt4GKfEmc3pLJfGDW44Z3gvpXTdjubch-CCZB-2u5sC8wbNUZDz2OynpwXwDOw6lp5_G4nh8WdN4MzKTUTzLvcFL-K060IEw3CxQZbNPRcvOPXEhfEGtF8jV9KQCK5PCQZtZEszRPqnGyVw-mLuNsgqU4KLTLiIovx_sUUM6FI5NThuPhkwHjhpL19vRxR0w5Nc49t9iYXDd0i9thTtTqS8d_ogxPFk12BKCLx7D-aUCW9LsRyVq2uHSkKZeayma3T4Dzbhl-lu-x9yjhvnasPORFfUDbcZKySaTOBBTuTdHq8p3iX.wbou47z6kQi0JeUV-IuDzQ.FdSBM8PvqrMFQWuw68HLltPM_wUNT-S4giZlu4_40PM1CntpAkE03tRD_y0d2mgQTBiNUC7YKXJikzDWU1TNrMatM0YyZQERDur4pBf19d1gAgwZOtgKEzyd9ui8gax8kL4X-caWxi5dXCrnQT8fhX1ForHReXPlVaUFtdSdFGUoMWs6bFW6PEnwVukW1jHZ_HvlNiME3HUxzgkB8pjIqPX8sYXaZJw5rv_etiWn1zeF8BdEt9tnKhuuGKEXlWtUYjPkiH98afbbmUyULlCfwjZfZnsTZEBe4llCIMI7AflCkUPQVgIcyqCZy10yYiJyuFYC_B3MGGNjwBcGXWWtuSeMWF0xw4xUHPgGkY6A9WqTvZD4CuWgP3VMbWFve9WN.BlDpLSM3Wdwgic54McbEwQ

Thank you,
Hitesh

**Comment by dvsekhvalnov** [comment]
@hiteshsalian , your headers contains clearly weird value for `alg`:

```
{
  "alg": "http://www.w3.org/2001/04/xmlenc#rsa-oaep",  // SHOULD BE JUST: RSA-OAEP
  "enc": "A128CBC-HS256",
  "kid": "..........",
  "typ": "JWT"
}
```

Consider changing producer side of things to follow spec: https://datatracker.ietf.org/doc/html/rfc7518#section-4.1 ?

**Comment by hiteshsalian** [comment]
@dvsekhvalnov 

Appreciate your help here. We will change the producer side.

I believe Microsoft library is assigning the "alg" by default.

I found link on usage for additional header.
https://openid.net/specs/draft-jones-json-web-encryption-02.html#W3C.CR-xmlenc-core1-20110303 
(check section 9.2)

Thank You

**Comment by dvsekhvalnov** [comment]
Well, you clearly can put any value to 'alg' header, but most libraries out there will not understand beyond JWA spec.

Feel free to close ticket if all resolved :)

**Comment by hiteshsalian** [comment]
Thank you.  Will close this ticket
