### ISSUE TITLE
Signed and Encrypted message couldn't decrypted

### ISSUE THREAD

**Issue by venkatpoluri** [dvsekhvalnov/jose-jwt#162]
Hello Dvsekhvalnov,
I'm doing the sign and encrypt the data with predefined keys but couldn't decrypt it in C#.
**Could you please help me with what went wrong with signing and encryption?**

I'm using the below keys for signing/ encryption and decrypt/ verify.

### Platform: Windows 10 /.Net Core 3.1

{
  "clientSign": {
    "kty": "EC",
    "d": "zmnSC_P5Xzefte7vkdINXLAN2LeBgC0S5QTcPO2mI5vo62chc_zHAYhcobGPQGNJ",
    "use": "sig",
    "crv": "P-384",
    "x": "G4JWlybVRkliYWLLFdXDj0CjMjnkXeyiunzQswR3izK-jxvMIYdjVB52Rty5yZN9",
    "y": "JndKKF7RQf97idkaLPLsv_jkZPBw-MJFogDqri87vvnpAEf1qyHnQTmK_gAhLAgo",
    "alg": "ES384"
  },
  "clientDecrypt": {
    "kty": "EC",
    "d": "Irx1Kg78ZY4xZPH_sNMWIe8ifpSB_6f9HZ-JRJiVMae0b_bitAC7Wld03t6KzCdB",
    "use": "enc",
    "crv": "P-384",
    "x": "f-qS0J9HcmWeU2zmDYnjCMwcsEw9ozb0_XE5y2hi2NKUJEyTgeMuWynBpexlhXbS",
    "y": "22-bZgbttgc4G5lXBsoVMMV5-TYg41FjJY2uGtlJp-MSfJ2agzouRjpzrCihXi7z",
    "alg": "ECDH-ES+A256KW"
  },
  "serverSign": {
    "kty": "EC",
    "d": "BYfl8to6zRfjjm7jFYtY5i_BwR2jXspsv1HDN0OLIaz-tUiACKZBeRruaLzBrHXJ",
    "use": "sig",
    "crv": "P-384",
    "x": "pM8gcPvgdKrKaxQmIC7Q67AvV7KteWqU5I4X83ErVinZnAgeT1KwfhCYssD3YNvK",
    "y": "SVsvfEm3CVu2WjOho2frL7LnaXeOQHC1JT856bOH-Vp3E-4_1j2Kp9KHJJf7Qn1v",
    "alg": "ES384"
  },
  "serverDecrypt": {
    "d": "3UScww8iqdRaBeTraC61WCFoO3fisO9A0p49P_GI6BuZO26-WUyElUWoKyhkcbeI",
    "kty": "EC",
    "use": "enc",
    "crv": "P-384",
    "x": "s8uFX_D-Ow5Q6UoRs6tFDBDkpdpcsueSl7-oyPpBFdgY6Co9L2AZknuqA4vDSKe4",
    "y": "IffoB24bdS2nk699nXMB4cVe7LgLdinCKNGgrgcPHlPXnqfdJ7T5DLucLLJP0DQA",
    "alg": "ECDH-ES+A256KW"
  }
}

**Comment by dvsekhvalnov** [comment]
Hi @venkatpoluri , 

is this ticket same or related to #163? Or some other issue?

**Comment by dvsekhvalnov** [comment]
closed due to inactivity, feel free to re-open
