### ISSUE TITLE
Decrypt using ECDH-ES+A256KW with A256CBC-HS512

### ISSUE THREAD

**Issue by charliexinhuan** [dvsekhvalnov/jose-jwt#164]
Hi, it seems decryption using ECDH-ES+A256KW with A256CBC-HS512 is not supported in jose? Thanks.

**Comment by charliexinhuan** [comment]
I'm getting this error: {"JWS algorithm is not supported: ECDH-ES+A256KW"}

**Comment by dvsekhvalnov** [comment]
Hi @charliexinhuan , 

it should be working just fine. Any chances you may running into https://github.com/dvsekhvalnov/jose-jwt#notes ?

If you post more details (like error message may be) i can try to help more.

**Comment by charliexinhuan** [comment]
![image](https://user-images.githubusercontent.com/36948119/127834410-861897ae-aa16-4243-a29f-1d66fb9979cd.png)

Hi @dvsekhvalnov ,

Please see the attached image. There is no further error message being shown other than "AesKeyWrap integrity check failed."

**Comment by dvsekhvalnov** [comment]
This usually means you passing in tampered message. What's inside your `myResponse` var?

**Comment by charliexinhuan** [comment]
It's the jwe token string returned by third party. The problem is the message was not tampered.

**Comment by dvsekhvalnov** [comment]
well, if you can post its value and some key to decrypt it here, i can try to run it myself to check.

**Comment by charliexinhuan** [comment]
Hi @dvsekhvalnov, can i also check for the decrypt function, the second parameter's key should be the requestor encryption private key am i right?

**Comment by dvsekhvalnov** [comment]
@charliexinhuan when you do encryption:
 - you encrypting with public key of **recipient**
 - and decrypting with private key of **recipient**

because you want only recipient of token to be able to decrypt it and nobody else. So you typically not using **requestor** keys (unless you using pre-shared symmetric keys)

**Comment by charliexinhuan** [comment]
Does jose-jwt supports 5 part structured token encryption and decryption?

**Comment by charliexinhuan** [comment]
To add on for the keys:
1. recipient decryption key - ECDH-ES+A256KW and A256CBC_HS512
2. sender signature key - ECDSA_P256

it seems like when i trying to validate the signature by using the decode function, i'm getting the following error:
{"Keys used with the ECDiffieHellmanCng algorithm must have an algorithm group of ECDiffieHellman." & vbCrLf & "Parameter name: key"}

**Comment by dvsekhvalnov** [comment]
@charliexinhuan jose-jwt supports 5 part token (called encrypted token).

I'm slightly lost, you mentioning multiple keys now. What is 'sender signature key' ?

Probably it will easier to troubleshoot if you share some code or sample token and sample keys to decode.

**Comment by charliexinhuan** [comment]
Hi, i'm able to do the decryption now. It seems like there is really a bug in Microsoft CNG that key cannot be more than 256 bit. Thanks for the help
