### ISSUE TITLE
Jose.JWT.Decode<dynamic> stopped working after dropping Newtonsoft

### ISSUE THREAD

**Issue by alex-jitbit** [dvsekhvalnov/jose-jwt#165]
This is because of known limitations of System.Text.Json that will be fixed in .NET 6 Preview 7

Please either revert the change (because this is a breaking change - code that worked before has stopped working) or include a workaround

**Comment by dvsekhvalnov** [comment]
Hi @alex-jitbit , 

parsing to object model obviously was library design mistake back in a past, too many issues with it. I need to consider dropping it altogether.

But nothing really prevents you to use Newtonsoft.Json library if you prefer, here is relevant documentation link: https://github.com/dvsekhvalnov/jose-jwt#customizing-json---object-parsing--mapping

Reference implementation is still around if you want to copy it or adjust to your own needs:  https://github.com/dvsekhvalnov/jose-jwt/blob/master/jose-jwt/json/NewtonsoftMapper.cs

then just register it with:

```c#
Jose.JWT.DefaultSettings.JsonMapper = new YourNewtonsoftVersion();
```
Let me know if other questions.
