### ISSUE TITLE
Unable to Decrypt JWE using algorithm A128CBC-HS256 in  .Net core

### ISSUE THREAD

**Issue by Ravi-Rajan** [dvsekhvalnov/jose-jwt#166]
Hello Dvsekhvalnov,
I'm doing the JWT encryption with predefined keys and converted into JWE in the middleware but couldn't decrypt it in backend C# service. Whereas I can make this work using **java**. Could you please share the equivalent **C# code** for the below snippet?

public static String decryptJWE(String jweToken, String base64EncodedCryptoKey) throws Exception {

  try {
	  String JWK_FORMAT_A128CBC = "{\"kty\":\"oct\",\"k\":\"%s\",\"alg\":\"A128CBC-HS256\"}";
	  String jwk = String.format(JWK_FORMAT_A128CBC, base64EncodedCryptoKey);
	  OctetSequenceKey octKey = OctetSequenceKey.parse(jwk);
	  JWEObject jweObject = JWEObject.parse(jweToken);
	  jweObject.decrypt(new DirectDecrypter(octKey));
	  Payload payload = jweObject.getPayload();
	  return payload.toString();
  } catch (JOSEException | ParseException e) {
	  throw new Exception("Token decryption failed:", e);
  }
} 

Sample value of base64EncodedCryptoKey = "**Jno3wKnprOt7MMxE7wq_OGKFcHFVeRsx8TwvPlCkHJY**";

I have tried below C# code but it throwing error such as 'AES-CBC with HMAC algorithm expected key of size 256 bits, but was given 344 bits'

var bytes = Encoding.ASCII.GetBytes(key);
Jose.JWE.Decrypt(jweToken, bytes, JweAlgorithm.DIR, JweEncryption.A128CBC_HS256);

**Comment by dvsekhvalnov** [comment]
Hi @Ravi-Rajan ,

guess you want (instead of ASCII):

```c#
var key = Convert.FromBase64String(base64EncodedCryptoKey);
```
?

If you can post your `jweToken` sample i can try to run it.

**Comment by Ravi-Rajan** [comment]
Hi Dvsekhvalnov,

Thanks for checking up on this. Below given the jweToken sample which I'm trying to convert as original jwt token provided by OKTA.

String jweToken = "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIiwiY3R5IjoiSldUIn0..YJbMJRChez1-3uWtkMuDDA.-dM6VZOvSNmdEPa5iJMVH-5h3k4RznsHiEonD82zYKnXx-bd1zrECe5qzgFEAJrulwgjVWPuI5dsPrNEGQo_H1iRdrsWm3URoEgdwYU2eoEmJ5bBD9Tq1HtBu4XW5RCEuVHZwhGZ13_jsYuvjothRYvLeMYwUfeqAg6bXTQyy_K_pBA0HUOpy7rVV5cYwI9AGZ5sv5CbNL_8rQiBI-svaRBC-sdR-NWUhpLIgAuxUjyA-6ANcbPgcBxePRMS1COLFQuLRMXv6O7P9BIAaamxn8Rbpa15x6N2EEXcosFcljNutBWrFWyaODhLOQ3xYSZu8IpSLzwRRmSljzXtvbusFYLa18X7U1qsbAhpH6lV0qi3kj_mp6NP80jRWPRekGBpEprd5YvFeyuA3RhjO2TXYAOpxfOKMzyYJK-B-wgjr4k4cfAZVijPWLKYIsRpUqB0QSyG4yPlVlG1GV0qllhcKMAdX-yG34OyqI-v81yoORHaOIHznZGj-qYuBk-xnLsTAeEYgTJv5FznVOit5-xgTvJVplTxvwJlZRn6wIcKqyhx6oZCCilsdSmY00quDhtg99rqzxf9PqOLHUoBXGx-ppHbpvG4j-o1BsLp0vnAlPo1joOxfwuXO60H_0SGt2UBLmjAv1SV_xXPrJdo6BAMpwqDairvcx1x5_pPw4JRW-oJ1M7a14SuRzFcFycpk_r3zgcnwN7dXOau0Po9nbfI3LOGaIB4GQBaWKaoJTydMuoamO0cibJZDaIpV1OHkwNZK5QuKNhbJWmVes3G9rws4aIxmfd8HGUQW59l2J4_PhRuvW9WpngUw0H8VX8C6IijzJMoU-jpKV11wuL0lyHlR3epFFmBpaGJejXR4pgc54Z9d3ZRqNAakKXyfCohy0HlksyI4RzhPtwccI1juvVNqcAuxYJmrbHIKmGJENvq_IoGyXZfA1xqT_-moIl1pXeh48Lpb_cBXisJ0mZk7ieQfvLi6aE2QDmuxtuyg3mFMHptL92d2Lo_KhBVEejVgFiHHYfRReFf1Ygunt_t7Aq38tzRkMfAezM3ItO_a3S6XkGFLnzzTVSKnUx8o-xaJAuJ5ePgFdXLxSn6Vx9vIENwwg.eZT75yrr_7EQgDN44P1myw";

**Comment by dvsekhvalnov** [comment]
Hi @Ravi-Rajan , snippet below works just fine to me:

```c#
            String jweToken = "eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIiwiY3R5IjoiSldUIn0..YJbMJRChez1-3uWtkMuDDA.-dM6VZOvSNmdEPa5iJMVH-5h3k4RznsHiEonD82zYKnXx-bd1zrECe5qzgFEAJrulwgjVWPuI5dsPrNEGQo_H1iRdrsWm3URoEgdwYU2eoEmJ5bBD9Tq1HtBu4XW5RCEuVHZwhGZ13_jsYuvjothRYvLeMYwUfeqAg6bXTQyy_K_pBA0HUOpy7rVV5cYwI9AGZ5sv5CbNL_8rQiBI-svaRBC-sdR-NWUhpLIgAuxUjyA-6ANcbPgcBxePRMS1COLFQuLRMXv6O7P9BIAaamxn8Rbpa15x6N2EEXcosFcljNutBWrFWyaODhLOQ3xYSZu8IpSLzwRRmSljzXtvbusFYLa18X7U1qsbAhpH6lV0qi3kj_mp6NP80jRWPRekGBpEprd5YvFeyuA3RhjO2TXYAOpxfOKMzyYJK-B-wgjr4k4cfAZVijPWLKYIsRpUqB0QSyG4yPlVlG1GV0qllhcKMAdX-yG34OyqI-v81yoORHaOIHznZGj-qYuBk-xnLsTAeEYgTJv5FznVOit5-xgTvJVplTxvwJlZRn6wIcKqyhx6oZCCilsdSmY00quDhtg99rqzxf9PqOLHUoBXGx-ppHbpvG4j-o1BsLp0vnAlPo1joOxfwuXO60H_0SGt2UBLmjAv1SV_xXPrJdo6BAMpwqDairvcx1x5_pPw4JRW-oJ1M7a14SuRzFcFycpk_r3zgcnwN7dXOau0Po9nbfI3LOGaIB4GQBaWKaoJTydMuoamO0cibJZDaIpV1OHkwNZK5QuKNhbJWmVes3G9rws4aIxmfd8HGUQW59l2J4_PhRuvW9WpngUw0H8VX8C6IijzJMoU-jpKV11wuL0lyHlR3epFFmBpaGJejXR4pgc54Z9d3ZRqNAakKXyfCohy0HlksyI4RzhPtwccI1juvVNqcAuxYJmrbHIKmGJENvq_IoGyXZfA1xqT_-moIl1pXeh48Lpb_cBXisJ0mZk7ieQfvLi6aE2QDmuxtuyg3mFMHptL92d2Lo_KhBVEejVgFiHHYfRReFf1Ygunt_t7Aq38tzRkMfAezM3ItO_a3S6XkGFLnzzTVSKnUx8o-xaJAuJ5ePgFdXLxSn6Vx9vIENwwg.eZT75yrr_7EQgDN44P1myw";
            var key = Jose.Base64Url.Decode("Jno3wKnprOt7MMxE7wq_OGKFcHFVeRsx8TwvPlCkHJY");

            String payload = Jose.JWT.Decode(jweToken, key);

            Console.Out.WriteLine("payload = {0}", payload);

```

**Comment by Ravi-Rajan** [comment]
Hi @dvsekhvalnov,

You are absolutely correct. All the time I was trying the wrong method for decoding. I appreciate the quick response. Thanks!!!

**Comment by dvsekhvalnov** [comment]
Glad it working :) Feel free to re-open if more questions.
