### ISSUE TITLE
Windows Cryptography Next Generation (CNG) is not supported on this platform.

### ISSUE THREAD

**Issue by cakriwut** [dvsekhvalnov/jose-jwt#167]
I am building an app for docker linux container.
During the runtime EccKy.New(x,y,d, CngKeyUsages.KeyAgreement) throws exception

System.PlatformNotSupportedException: Windows Cryptography Next Generation (CNG) is not supported on this platform.

--
Is there fix for this issue?

**Comment by dvsekhvalnov** [comment]
Hi @cakriwut , 

this means your platform (Linux i guess) doesn't provide CNG drivers, those are usually only available in Windows.

But the answer depends on what you trying to do actually.  If you trying to load Elliptic Curve key there are other way to do it:

```c#
var privateKey=new X509Certificate2("ecc-key.p12", "password").GetECDsaPrivateKey();
```

for instance.

**Comment by cakriwut** [comment]
To close this discussion, finally this is what I did:
1. Use Jering.Javascript.NodeJS , to execute node-jose instead of jose-jwt.
2. Include nodejs and node-jose in the build image.
