### ISSUE TITLE
Installing nuget package to project adds the LICENSE file to the project

### ISSUE THREAD

**Issue by coryflucas** [dvsekhvalnov/jose-jwt#17]
Installing the package shouldn't add your LICENSE file to the target project.  You can specify the package license via the licenseUrl and could set requireLicenseAcceptance to true to force a user to accept the license when installing.

**Comment by dvsekhvalnov** [comment]
@coryflucas hm.. confused. I think nuget spec doing exactly what you said right now.  Is there is some extra LICENSE file? Do suggest to remove it?

Pull request can be nice, btw :)

**Comment by dvsekhvalnov** [comment]
Thanks @coryflucas, i'll publish new package to nuget and close issue after.

**Comment by dvsekhvalnov** [comment]
published v1.9.1 over nuget
