### ISSUE TITLE
JWS algorithm is not supported: dir

### ISSUE THREAD

**Issue by DanielVernall** [dvsekhvalnov/jose-jwt#172]
I have JWEs created by one application using jose-jwt version 2.4.0.0, using a shared symmetric key like so:

token = JWT.Encode(payload, secretKey, JweAlgorithm.DIR, JweEncryption.A256CBC_HS512)

I can decrypt and decode these tokens fine in the same application using:

json = JWT.Decode(token, secretKey)

But when trying to decode the tokens in another application using the exact same jose-jwt version, in fact using a reference to the exact same dll when building. 

json = JWT.Decode(token, secretKey)

Produces an exception with the message: "JWS algorithm is not supported: dir"

The headers produced for my tokens are all:
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIn0

which decodes to: 
{"alg":"dir","enc":"A256CBC-HS512"}

So I can't see why the decoder is throwing an exception for these tokens in one application, but not another.
Both applications are written in VB.NET in case you are wondering.

**Comment by DanielVernall** [comment]
Apologies, I was writing a simple JWE decryptor app for testing purposes using WinForms and didn't realise part of the token was being truncated due to the default maximum length in the input box. Because the final segment was cut off, DecodeBytes() expected a standard JWS instead of JWE and produced the InvalidAlgorithmException as it, quite rightly, does not accept the direct algorithm for JWS format tokens.

**Comment by dvsekhvalnov** [comment]
No worries, glad it working :)
