### ISSUE TITLE
Using an HTTPS JWKS endpoint

### ISSUE THREAD

**Issue by saswademayur** [dvsekhvalnov/jose-jwt#174]
**Using an HTTPS JWKS endpoint**

Need to have a inbuilt way to resolve keys from an issuer who publish its public keys as a JSON Web Key Set at an HTTPS endpoint. 
The consumer of the JWT can then periodically retrieve the keys from the host authenticated and secured endpoint for further use.

A similar API is already available in jose4j library used for JAVA programming. below is the link to documentation of that library,

https://bitbucket.org/b_c/jose4j/wiki/JWT%20Examples#markdown-header-using-an-https-jwks-endpoint

**Comment by dvsekhvalnov** [comment]
@saswademayur  Please see example #3 here:  https://github.com/dvsekhvalnov/jose-jwt#examples

**Comment by dvsekhvalnov** [comment]
v4.0.0 released.
