### ISSUE TITLE
The assembly

### ISSUE THREAD

**Issue by jjballesteros69** [dvsekhvalnov/jose-jwt#175]
Hello, I've found this nuget awsome, but.....

Why it is not properly signed?

When I compile the assembly that is using this nuget, i got the compilation message:

"warning CS8002: Referenced assembly 'jose-jwt, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name."

And obviously when I run the application that uses it, it throws an exception.

In advance, thanks for the answer

**Comment by dvsekhvalnov** [comment]
Hi @jjballesteros69 , 

it is actually in README: https://github.com/dvsekhvalnov/jose-jwt/blob/15a255092511e5f5867075279cc11063fecae92a/README.md#strong-named-assembly 

:)

**Comment by dvsekhvalnov** [comment]
closed due to inactivity
