### ISSUE TITLE
ECDH-ES and ECDH-ES+A128KW, ECDH-ES+A192KW, ECDH-ES+A256KW key generation

### ISSUE THREAD

**Issue by weirdyang** [dvsekhvalnov/jose-jwt#178]
> ECDH-ES and ECDH-ES+A128KW, ECDH-ES+A192KW, ECDH-ES+A256KW key management requires CngKey (usually public) or Jwk of type EC elliptic curve key of corresponding length.
> 
> Normally existing CngKey can be loaded via CngKey.Open(..) method from Key Storage Provider. But if you want to use raw key material (x,y) and d, jose-jwt provides convenient helper EccKey.New(x,y,usage:CngKeyUsages.KeyAgreement) or use Jwk instead.

I'm trying to create a EC key similar to below:

```
{
    "kty": "EC",
    "use": "sig",
    "kid": "sig-2021-01-15T12:09:06Z",
    "crv": "P-256",
    "x": "Tjm2thouQXSUJSrKDyMfVGe6ZQRWqCr0UgeSbNKiNi8",
    "y": "8BuGGu519a5xczbArHq1_iVJjGGBSlV5m_FGBJmiFtE"
}
```

Based on the documentation:
I can do something like this:
```
var publicKey = new Jwk(
    crv: "P-256",
    x: "BHId3zoDv6pDgOUh8rKdloUZ0YumRTcaVDCppUPoYgk",
    y: "g3QIDhaWEksYtZ9OWjNHn9a6-i_P9o5_NrdISP0VWDU"
);
```

How do I obtain the x and y ? I'm stuck at this step:

```
var edna = X509.GetECDsaPublicKey() as ECDsaCng;
if(edna != null)
{
    var cngKey = edna.Key;
    var jwks = new Jwk(cngKey, isPrivate: false);
    jwks.Kty = "EC";
    jwks.KeyId = "default-key";
    jwks.Crv = "P-256";
}

```
How do I use the CNGKey to derive the x and y? Thanks.

**Comment by weirdyang** [comment]
Ahh thanks! So the x and y are automatically generated?

**Comment by dvsekhvalnov** [comment]
Yep, if you loading it from existing Cng or ECDsa or other .net type key - it will fully populate Jwk fields (x,y, crv, kty, e.t.c.)

**Comment by weirdyang** [comment]
Sorry one last question, will this be the way to generate JWTs signed by the JWK?

`var myToken = Jose.JWT.endcode(payload, jwk); `

**Comment by dvsekhvalnov** [comment]
Hey, probably it's too much code for such simple thing. `Jwk` itself is a signing key, no additional magic needed to use it. You don't need to serialize it or put to JsonWebKeySet. You can just use it as is.

Checkout example 3 here https://github.com/dvsekhvalnov/jose-jwt#es---family

**Comment by weirdyang** [comment]
Thanks again. My confusion comes from this:
![image](https://user-images.githubusercontent.com/25576022/162895459-e3848181-8f43-45be-a741-c4ad9593f9c6.png)
I'm trying learn how to create the JWKs required to complete the login flow outlined in the [docs](https://api.singpass.gov.sg/library/login/business/implementation-technical-requirements).

Get public key in json format:
``
 var edna = X509.GetECDsaPublicKey();
if(edna != null)
{
    Jwk jwk = new Jwk(edna, isPrivate: false);
    jwk.KeyId = "default-key";

    // or serialize to JSON string as at the beginning of your question
    string json = jwk.ToJson(Jose.JWT.DefaultSettings.JsonMapper);
}
```

Get private key to sign:
``
 var edna = X509.GetECDsaPrivateKey();
if(edna != null)
{
    Jwk jwk = new Jwk(edna, isPrivate: tue);
    jwk.KeyId = "default-key";

    string clientAssertion=Jose.JWT.Encode(payload, privateKey, JwsAlgorithm.ES256);
}
```

Get private key to decrypt:
``
 var edna = X509.GetECDsaPrivateKey();
if(edna != null)
{
    Jwk jwk = new Jwk(edna, isPrivate: tue);
    jwk.KeyId = "default-key";

    string payload = Jose.JWT.Decode(token, privateKey);
}
```

**Comment by dvsekhvalnov** [comment]
So it sounds like you want to serialize your signing/encryption key to JSON, that's pretty easy as well:

``` cs
   var edna = X509.GetECDsaPublicKey();

   // build Jwk from ECDsa key
   Jwk jwk = new Jwk(edna);
   jwk.KeyId = "what-ever"; // can set KeyId if needed

   // Build Json Web Key Set
   JwkSet keySet = new JwkSet(jwk, may_be_other_keys_you_want_too);

  // Now can convert it to JSON and send to partner or return it from REST Endpoint
  string keysetJson = keySet.ToJson(Jose.JWT.DefaultSettings.JsonMapper);
  
```

**Comment by weirdyang** [comment]
Thanks.

I've managed to generate it from a private key, but the `x`, `y` and `d` does not match with the JWK generated with `node-jose`, is that expected?

`node-jose`

```
{
  kty: 'EC',
  kid: 'signing-keys',
  use: 'sig',
  alg: 'ES256',
  crv: 'P-256',
  x: 'TU7MnKXI-77yn1udb7tANpIYCk2n-Aju9cULUj4MniI',
  y: 'JgDt25h32C9f0-KWL5gf--k2HLpCF9P0dOd3ka1OySg',
  d: 'xdWCy1pkykd7xcBoruk1JTWTA6dow8-urF_sj8DM8i4'
}
```

`jose-jwt`
```
{
  "kty": "EC",
  "kid": "my-sign",
  "crv": "P-256",
  "x": "BYNI0nykkvuybU20hCak4zbtp0T63GKqP2Jp7PJ1We4",
  "y": "olAIKfd9295UuZ5WNt8zdpPsosivgVFq7lsQw458XNM",
  "d": "oZm8gXSe_Gk28iIykMp8duRhC4ym6qVoXC7XQQuA6z4"
}
```
```

**Comment by dvsekhvalnov** [comment]
1. Yes, `d` is private ECC param.
2. You can just drop `d` - and it will be public params only. Or load only public part from PEM file. Do you have a code to share?

**Comment by weirdyang** [comment]
Hi,

Thanks again.

I've managed to figure out most of it with your help!

Here's my code; 

https://github.com/weirdyang/jwk-singpass/blob/cd747e2532b2665cf051ead9a957d422e070a521/KeyGen/Program.cs#L50

I'm at the moment trying to figure out how to decrypt a JWE in the JWS. I've attached a link to my code for your reference. Is that the right method?
The `id_token` will be encrypted based on the public key I sent over, and then signed.

https://stg-id.singpass.gov.sg/docs/authorization/api#_jwt_claims_2

**Comment by dvsekhvalnov** [comment]
@weirdyang link to your code gives me 404 error, probably it's private repo.

**Comment by weirdyang** [comment]
My bad;
I'm at the moment trying to figure out how to decrypt a JWE in the JWS. I've attached a link to my code for your reference. Is that the right method?
The id_token will be encrypted based on the public key I sent over, and then signed.

I am trying to simulate it by encrypting it myself, but I cant seem to decrypt it.
`Jose.IntegrityException: 'AesKeyWrap integrity check failed.'`
https://github.com/weirdyang/jwks-net-core/blob/0062ae000fd3c1173de86d315fe70f8a84e171a6/KeyGen/Program.cs#L58

**Comment by dvsekhvalnov** [comment]
Well, you don't need to use `JWE`, this one is for https://datatracker.ietf.org/doc/html/rfc7516 , probably not what you looking for (though no harm). `Jose.JWT.Decode(..)` will do decryption just fine with single line of code.

Also your `sgpPublicKey` is JwkSet not a single key, you need to grab specific key out of it before passing to it to decode call here: https://github.com/weirdyang/jwks-net-core/blob/0062ae000fd3c1173de86d315fe70f8a84e171a6/KeyGen/Program.cs#L63


So, i'd say something like:
``` cs
   var results = JWT.Decode(encryptedIdToken, encJwk);
   var sgpKeySet = JwkSet.FromJson(singpassKeys, Jose.JWT.DefaultSettings.JsonMapper);
   var pubKey = // select key you need from sgpKeySet with Linq or whatever else
   var claims = JWT.Decode(results, pubKey);
```

**Comment by weirdyang** [comment]
Thanks again!
