### ISSUE TITLE
AesKeyWrap integrity check failed for ECDH-ES+A256KW alg

### ISSUE THREAD

**Issue by Nizam-tch** [dvsekhvalnov/jose-jwt#186]
Hi @dvsekhvalnov,
The below code throws 'AesKeyWrap integrity check failed' exception while decrypt the 'idToken'. im using 'P-521' curve for enc keys. 

JsonTextReader reader = new JsonTextReader(new StringReader(EncryptionKey));
            var jwk = JsonSerializer.CreateDefault().Deserialize<JWK>(reader);
            var publicECCKey = EccKey.New(Base64Url.Decode(jwk.x), Base64Url.Decode(jwk.y), Base64Url.Decode(jwk.d), usage: CngKeyUsages.KeyAgreement);

            //---get the decrypted token
            string token = Jose.JWT.Decode(IdToken, publicECCKey, JweAlgorithm.ECDH_ES_A128KW, JweEncryption.A256CBC_HS512);

![image](https://user-images.githubusercontent.com/107637435/174117320-ba1102aa-983c-4e7e-ae56-8b079e5b867c.png)

**Comment by dvsekhvalnov** [comment]
Hi @Nizam-tch , 

https://github.com/dvsekhvalnov/jose-jwt#notes , see second. Is it your case?

**Comment by Nizam-tch** [comment]
Hi @dvsekhvalnov  
Thank you for your prompt response
Currently, https://[mkjwk.org](https://mkjwk.org/)/ is not accessible. 
I'll generate the key with P-256 and try again

**Comment by rakeshfern** [comment]
Is this solved am facing same issue

**Comment by rakeshfern** [comment]
what changes resolved this issue @dvsekhvalnov  and @Nizam-tch

**Comment by rakeshfern** [comment]
![image](https://user-images.githubusercontent.com/51435101/230923635-3fc999f2-5d0b-4f0d-8850-125273bf1718.png)
This is my code for decryption,
var privateKey = new Jwk(
"P-521",
"AD2J_17wpqY7wVi9ag-P5X13OL6asPqaOHMNQi0ek3aE2SNOiOdTBAADEApVsZLzf5zS4XM6qttvEaRIOOJyeG9e",
"AONkenNl5HXzZ6LRPXW0e1-kH5ZnLxl2cZeWh49B551L_hWE4IHZbrrI5sk1d3t8bFUtnFNgOSNRbQIPW54Knc-r",
"AC9azvDLPpwr53MuzUj1Zgwdmhdg9ytE_nknqAwvQMi1b03bH9_Vlhn-dXDVQzHSgur8bpMCMAXgvzJ-zohQ3ahx"
        );

 

      
 

           // JwtSettings settings = new JwtSettings().RegisterJwe(JweEncryption.A256CBC_HS512, encAlg);
            var toks = JWT.Decode(token.id_token, privateKey,JweAlgorithm.ECDH_ES_A256KW, JweEncryption.A256CBC_HS512, new JwtSettings().RegisterJweAlias("A256CBC-HS512_ALIAS", JweEncryption.A256CBC_HS512));

**Comment by dvsekhvalnov** [comment]
Hello @rakeshfern , 

what kind of problem you are facing?

Also please check notes: https://github.com/dvsekhvalnov/jose-jwt#notes

**Comment by rakeshfern** [comment]
AESWrapIntegrity Error @dvsekhvalnov 
but now i changed the curve to p-256 it worked.
Thanks for the prompt reply.

**Comment by dvsekhvalnov** [comment]
Ok folks, i'll close this one out, sounds like everybody just happy with P-256, blame Microsoft otherwise :)
