### ISSUE TITLE
Decode a JSON Web Token (JWT) of JWE alg RSA_OAEP

### ISSUE THREAD

**Issue by Marrryy** [dvsekhvalnov/jose-jwt#187]
Hi, 

I use this function to decode 

string token = "eyJhbGci.....";
var privateKey=new X509Certificate2("my-key.p12", "password").GetRSAPrivateKey();
string json = Jose.JWT.Decode(token,privateKey);

this function give error message Algorithm 'AesGcm' is not supported on this platform.

I realize that the header of the token JWT is  { "alg": "RSA-OAEP", "enc": "A256GCM", "kid": <domain name> }

I have tried using 
string json = Jose.JWT.Decode(token,privateKey, Jose.JweAlgorithm.RSA_OAEP, Jose.JweEncryption.A256GCM);

but the result is same..

Can anyone help me or reconfirm that Jose-JWT is not support RSA-OAEP? 

Thank you in advance

**Comment by dvsekhvalnov** [comment]
Hi @Marrryy , 

so what platform you are running on and what library version?

**Comment by Marrryy** [comment]
Hi @dvsekhvalnov ,

For what i see on .config files, it was <package id="jose-jwt" version="3.2.0" targetFramework="net48" /> .

Actually in my target framework is .NET 6.0 and I already download the latest v4.0

Is it triggering  "Algorithm 'AesGcm' is not supported on this platform" because I using mac OS ?

Thank you

**Comment by Marrryy** [comment]
Hi All, 

Thank you for your reply.

yes it is only affect in mac OS. I have use other Windows OS,  it's good. Sorry for trouble.

**Comment by dvsekhvalnov** [comment]
@Marrryy , on MacOS you end up with .netcore. 

If you need AES-GCM you need version of .netcore that implements NETSTANDARD2_1, see here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1
