### ISSUE TITLE
Typo in Jwk.NameToCurve

### ISSUE THREAD

**Issue by zzyzy** [dvsekhvalnov/jose-jwt#188]
Hello,

It appears there's a typo for the method Jwk.NameToCurve when converting from "P-384" string to ECCurve.

https://github.com/dvsekhvalnov/jose-jwt/blob/4391fa0069abac4d5e7e035845be38914206eb10/jose-jwt/jwk/Jwk.cs#L538

**Comment by dvsekhvalnov** [comment]
Thanks @zzyzy !

Fix obviously looks good to me :) Can we add unit tests? i've posted comments in PR.

**Comment by dvsekhvalnov** [comment]
released to nuget.org
