### ISSUE TITLE
How to use a JWK as a public key and encrypt a JWE using it

### ISSUE THREAD

**Issue by shaiArn** [dvsekhvalnov/jose-jwt#205]
Hi @dvsekhvalnov, thank you for this helpful library.

I'm getting JWK, and I need to use it to encrypt a JWE.
After creating the JWK with `Jwk.FromJson()`, I want to use it as a public key for encrypting a JWE.
If I understand correctly the encryption key in the `JWE.Encrypt()` method is the following argument: `IEnumerable<JweRecipient> recipients`

Is there a way to convert JWK to the needed type?

**Comment by dvsekhvalnov** [comment]
Hi @shaiArn , 

`recipients` is list of recipients for RFC 7516 JSON encoding. You specify a key per recipient, you can find examples within https://github.com/dvsekhvalnov/jose-jwt#encrypting-using-json-serialization (see second code snippet).

You don't need to convert `Jwk` to anything else, just pass it as key argument.
