### ISSUE TITLE
JWK Format KeyType = oct

### ISSUE THREAD

**Issue by andezapriansyah** [dvsekhvalnov/jose-jwt#210]
Hello @dvsekhvalnov ,
how to make a jwk so that it can be included in the JWT. Encode ini .net core?
i used code `var secretKey = new Jwk(secret);` Still an error occurs in the jwk key,

jwk format i expected like this :
{"kty":"oct","k":"Fdh9u8rINxfivbria1JKVT1u232VQBZYKx1HGAGPABa"}

**Comment by dvsekhvalnov** [comment]
Hey @andezapriansyah , 

you can serialize key to `IDictionary` for instance and then include as `extraHeaders` to encode:
https://github.com/dvsekhvalnov/jose-jwt#reading-jwk
https://github.com/dvsekhvalnov/jose-jwt#adding-extra-headers

something like:

```c#
var secretKey = new Jwk(secret);
var headers = new Dictionary<string, object>()
{
     { "key", secretKey.ToDictionary() },
};

string token = Jose.JWT.Encode(payload, ...... , extraHeaders: headers);
```

or if you can serialize JWK to json string directly: yourkey.ToJson(JWT.DefaultSettings.JsonMapper);

**Comment by andezapriansyah** [comment]
the secret must be a byte[] ?
that I have is a string

i tried to change it from string to byte but got an error :
`AesKeyWrap management algorithm expected key of size 256 bits, but was given 344 bits`

this is my code:
`string secret = "QvIP2QTvOk4O0rYx4a9In1WMB9P4KIxzULdVtZceScu";
 byte[] secretKey = Encoding.UTF8.GetBytes(secret);
 string token = JWT.Encode(payloads, secretKey, JweAlgorithm.A256KW, JweEncryption.A256CBC_HS512, JweCompression.DEF);`

**Comment by andezapriansyah** [comment]
thanks a lot, it's working.  with code like this :
```
Jwk publicKey = Jwk.FromDictionary(new Dictionary<string, object>()
{
    {"kty", "oct"},
    {"k", "[secret]"}
});
```

**Comment by dvsekhvalnov** [comment]
ok ) feel free to close if no more questions.
