### ISSUE TITLE
Support arbitrary payload

### ISSUE THREAD

**Issue by sandersaares** [dvsekhvalnov/jose-jwt#22]
The assumption in the API currently seems to be that the payload is a JSON object (either serialized by jose-jwt or by the caller). This is more restrictive than the actual JOSE specifications, which allow any arbitrary data to be processed.

It would be desirable to use jose-jwt with arbitrary data (e.g. in the form of a `byte[]` API).

**Comment by dvsekhvalnov** [comment]
It's not, it operates on arbitrary string. Is this what are you looking for?

```C#
            string token = Jose.JWT.Encode("Hey, i'm not JSON at all.", PubKey(), JweAlgorithm.RSA_OAEP_256, JweEncryption.A128GCM);

            Console.Out.WriteLine("token = {0}", token);

            string payload = Jose.JWT.Decode(token, PrivKey());

            Console.Out.WriteLine("payload = {0}", payload);
```

**Comment by sandersaares** [comment]
Okay, but a string cannot contain arbitrary data - this is a stricter limitation than what is present in the JOSE specifications. What I want to encode/decode is byte[] - not all combinations of bytes are valid strings, so I cannot use string.

**Comment by dvsekhvalnov** [comment]
Well, you can encode your binary to string, let's by using base64 encoding.

Ok, regardless, can yo give use-case when you need binary data to be encrypted via jose?  The reason i'm asking:

- most implementation for other languages are centered around strings (need to double check, may be something changed or i missed in the past)
- need to cross-verify binary data with other libraries, otherwise it become only lib-specific feature.

**Comment by sandersaares** [comment]
In my use cases, I am not working with any textual data, so adding e.g. base64 encoding is just a needless layer that increases the size of the data for no actual benefit. An example of what sort of data I want to encrypt and sign: 8 randomly generated bytes (an encryption key).

The JOSE specifications define the payload as an arbitrary sequence of bytes, so even if other libraries do not support this usage, I still think it would be beneficial for jose-jwt to work against the specifications, not other libraries. There are plenty of bad JOSE libraries in the world, which only support a tiny subset of features/algorithms - I think this is no reason to limit jose-jwt.

**Comment by sandersaares** [comment]
@dvsekhvalnov are you able to provide feedback on whether you plan to merge the relevant PR and/or include this feature?

For reference, here is a node.js sample of signed binary data (uses the *jws* package):

```
let jws = require("jws");
let payload = Buffer.from("TkJyotZe8NFpgdfnmgINqg==", "base64");

console.log(payload);

let token = jws.sign({
	"header": {
		"alg": "HS256"
	},
	"payload": payload,
	"secret": "secret key"
});

console.log(token);
```

**Comment by dvsekhvalnov** [comment]
Sorry forgot. Yeah make sense to me. So can you:

1. add encode/decode/ecncrypt/decrypt unit tests for binary payload (not only `PayloadBytes` which didn't really perform decoging) . Ideally if you cross test with node.js or other implementation which supports binary payload

2. add something to docs

**Comment by sandersaares** [comment]
Great! I have performed the requested additions and updated the pull request. Please let me know if you would like anything additional to be included in this package.

For the tests, I only added a few (in comparison to the large set that already exists), as the vast majority of the functionality is already tested by the non-byte[] methods, so no point in duplicating test code for that. Let me know if you think something more should be included in the extended scope.

**Comment by dvsekhvalnov** [comment]
looks good. i'll re-publish update nuget package little bit later. wanted to add same support to golang version and crosstest little bit more.

**Comment by sandersaares** [comment]
@dvsekhvalnov do you have an estimate on when you plan to release a version that includes this on NuGet? I am just wondering whether it makes sense for me to wait for this to be on nuget.org before publishing next version of my project or (if it will take some time) whether I should just include a custom built DLL for now.

**Comment by dvsekhvalnov** [comment]
Sorry, @sandersaares , i totally forgot. Will do over weekend. (kick me on monday if i'm not :)

**Comment by dvsekhvalnov** [comment]
Pushed v1.9.3 to nuget.org with binary payload support
