### ISSUE TITLE
Kinda weird code in the library

### ISSUE THREAD

**Issue by Smoovsky** [dvsekhvalnov/jose-jwt#224]
[Code](https://github.com/dvsekhvalnov/jose-jwt/blob/cb426b83e1e2010cdb7b9c062532ce1b27905f71/jose-jwt/jwk/JwkSet.cs#L68-L80) 

Both ```mapper```s are null by default, but a null reference exception will be thrown for sure if they are null.

**Comment by Smoovsky** [comment]
I made a PR #225 . Thanks.

**Comment by dvsekhvalnov** [comment]
Yeah, indeed, let me think why i did it :)
