### ISSUE TITLE
Get Public key from File

### ISSUE THREAD

**Issue by Mr-Mohammad** [dvsekhvalnov/jose-jwt#228]
hi 
I want to open public key from File in (public-key.pem) project root and Encode with public key Algorithm : ECDH ES A256KW - Encryption method: A256GCM I'm using C# please help me

**Comment by dvsekhvalnov** [comment]
Hi @Mr-Mohammad , something along those line if you are on modern version of .net:

```c#
var eccPem = File.ReadAllText("public-key.pem");

var key = ECDsa.Create();
key.ImportFromPem(eccPem);

Jose.JWT.Encode(payload, key, ....);
```

**Comment by Mr-Mohammad** [comment]
This is my code:
          var payload = new
            {
                sub = "mr.x@yahoo.com",
                exp = 1300819380
            };
            var publickey = File.ReadAllText("public-key.pem");
            var key = ECDsa.Create();

            key.ImportFromPem(publickey);

            var res=Jose.JWT.Encode(payload, key, JweAlgorithm.ECDH_ES_A256KW,JweEncryption.A256GCM);

            Console.WriteLine(res);

**Error in run time for this line:**
            var res=Jose.JWT.Encode(payload, key, JweAlgorithm.ECDH_ES_A256KW,JweEncryption.A256GCM);

**Error :** 
System.ArgumentException
  HResult=0x80070057
  Message=EcdhKeyManagement alg expects key to be of CngKey or Jwk types with kty='EC'.
  Source=jose-jwt
  StackTrace:
   at Jose.EcdhKeyManagement.NewKey(Int32 keyLength, Object key, IDictionary`2 header)
   at Jose.EcdhKeyManagement.WrapNewKey(Int32 cekSizeBits, Object key, IDictionary`2 header)
   at Jose.EcdhKeyManagementWithAesKeyWrap.WrapKey(Byte[] cek, Object key, IDictionary`2 header)
   at Jose.EcdhKeyManagementWithAesKeyWrap.WrapNewKey(Int32 cekSizeBits, Object key, IDictionary`2 header)
   at Jose.JWE.EncryptBytes(Byte[] plaintext, IEnumerable`1 recipients, JweEncryption enc, Byte[] aad, SerializationMode mode, Nullable`1 compression, IDictionary`2 extraProtectedHeaders, IDictionary`2 unprotectedHeaders, JwtSettings settings)

**Comment by dvsekhvalnov** [comment]
@Mr-Mohammad what's you runtime version of .net?

**Comment by Mr-Mohammad** [comment]
@dvsekhvalnov 
.net 6.0
jose-jwt : 4.1.0

**Comment by dvsekhvalnov** [comment]
Ah, sorry @Mr-Mohammad i gave wrong advice. Was thinking you want to do digital signature, not an encryption.

For encryption you will need either `CngKey` or JWK. Microsoft not providing an easy way to parse .pem other than to `ECDsa` keys (which is not what you want for encryption).

So my best advise will to convert .pem into JWK somehow.

**Comment by Mr-Mohammad** [comment]
@dvsekhvalnov 
i'm using this code For Convert .Pem to Jwk
            string publicKeyPem = @"-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3LB3nOlUybXt/lI6hi8YS/SVmo2b
TKioHGChnOgbM38FyFcJv/z0ziRNvzDaUNj7MLckeYewqZGB//A/mox71A==
-----END PUBLIC KEY-----";
            RSA rsa = RSA.Create();
            rsa.ImportFromPem(publicKeyPem);

            // Convert the public key to JWK format
            JsonWebKey jwk = JsonWebKeyConverter.ConvertFromRSASecurityKey(new RsaSecurityKey(rsa));

But it gives an error
error :
System.Security.Cryptography.CryptographicException: 'Key is not a valid public or private key.'

**Comment by dvsekhvalnov** [comment]
Hey @Mr-Mohammad , no that's definitely not the code to read PEM file. 

Why don't you try to convert pem to jwk before hand? you can test it out here for instance: https://irrte.ch/jwt-js-decode/pem2jwk.html

**Comment by Mr-Mohammad** [comment]
I tried to convert  pem to jwk but it was not successful and gave an error

This site cannot convert my public key to jwk
https://irrte.ch/jwt-js-decode/pem2jwk.html

**Comment by dvsekhvalnov** [comment]
ohh.. how about this https://hub.docker.com/r/danedmunds/pem-to-jwk/ ?

**Comment by dvsekhvalnov** [comment]
Hey @Mr-Mohammad , just checking if last link helped?
