### ISSUE TITLE
Windows Cryptography Next Generation (CNG) is not supported on this platform.

### ISSUE THREAD

**Issue by vinaykasireddy** [dvsekhvalnov/jose-jwt#230]
We are getting the following issue when we try to run the code in Linux OS. This is not a problem when the run the same in windows.

Is this nuget package OS dependant? Please advise.

Our application is running on .NET 6 and is referring 4.1.0 version of this nuget package.

> "Windows Cryptography Next Generation (CNG) is not supported on this platform."

![image](https://github.com/dvsekhvalnov/jose-jwt/assets/2632995/4f28b6de-1e48-499c-84cd-dc856b25e2bd)
![image](https://github.com/dvsekhvalnov/jose-jwt/assets/2632995/a726694c-a70a-4525-9a45-5e8b482fd105)

_**ERROR**_

![image](https://github.com/dvsekhvalnov/jose-jwt/assets/2632995/05309007-8068-49cc-b552-fc50da410bbe)

**Comment by dvsekhvalnov** [comment]
Well, some crypto primitives in .net core are not supported (at least was
not in a past) on Linux.

I'm out of laptop for next couple weeks, so can't check exact details, but
most likely you are running into this.

**Comment by dvsekhvalnov** [comment]
Hi @vinaykasireddy , well i'm back if you want me to check something. 

As i mentioned previously ECDH key management have some limited support on Linux due to the fact some crypto was not provided by .net framework.

**Comment by digaomatias** [comment]
I've forked this project and I'm working on making it work on Linux. 
@dvsekhvalnov I'll reach out to you sometime to see if you would like to discuss the changes and have a PR. 
It seems we can make it work by replacing CngKey for ECDiffieHellman. But we need to discuss whether we replace it or if we try to have both implementations in place. 
I'm working on replacing CngKey due to the fact it's probably not gonna be supported in .Net Core.

**Comment by dvsekhvalnov** [comment]
Hi @digaomatias, PRs always welcome :)

If you want to discuss technical design decisions upfront - also fine, let me know.

Also please checkout https://github.com/dvsekhvalnov/jose-jwt/issues/219 , some related work may be.

**Comment by dvsekhvalnov** [comment]
v5.0.0 released to nuget.org

https://github.com/dvsekhvalnov/jose-jwt/releases/tag/v5.0.0
