### ISSUE TITLE
JSON Web Encryption

### ISSUE THREAD

**Issue by KiarashS** [dvsekhvalnov/jose-jwt#24]
Dear,

How we must implement and use JWE ([JSON Web Encryption](https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40)) and encrypt JWT (JSON Wen Token) tokens?

Thanks.

**Comment by dvsekhvalnov** [comment]
Hi @KiarashS , 

checkout docs: https://github.com/dvsekhvalnov/jose-jwt/#creating-encrypted-tokens

**Comment by dvsekhvalnov** [comment]
Hi @KiarashS, do you still have open questions?

**Comment by KiarashS** [comment]
So, with this method based on below link we can encrypt (no signature) tokens?

https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40

**Comment by dvsekhvalnov** [comment]
Yep. Exactly, `jose-jwt` supports full spec.

**Comment by KiarashS** [comment]
No problem.
I have a question, how we can encrypt (no signature) jwt tokens based on [this link](https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40)?

Thanks

**Comment by dvsekhvalnov** [comment]
Well, i'm not really familiar with JSON Web Encryption spec itself. But if you are looking for JWE compact serialized token, you can create one by:

```C#
string token = Jose.JWT.Encode(payload, publicKey, JweAlgorithm.RSA_OAEP, JweEncryption.A256GCM);
```

adjust key management and encryption algs based on your needs.

**Comment by dvsekhvalnov** [comment]
@KiarashS , closing for now, let me know if you have further questions.
