### ISSUE TITLE
BCryptDecrypt error!

### ISSUE THREAD

**Issue by joaorstavares** [dvsekhvalnov/jose-jwt#240]
Hi

I'm trying to use the nuget package, however when decrypting a message and calling:
`status = BCrypt.BCryptDecrypt(hKey, cipherText, cipherText.Length, ref authInfo, ivData, ivData.Length, plainText, plainText.Length, ref plainTextSize, 0x0);`

Visual Studio gives me error saying that BCrypt does not contain a definition for BCryptDecrypt.

Isn't this because BCryptDecrypt is declared as internal and not as public, like BCryptEncrypt is?

I'm kinda new at this.

Kind Regards,
João Tavares.

**Comment by joaorstavares** [comment]
I think BCryptSetAlgorithmProperty has the same issue, has I get the same error from VS.

**Comment by dvsekhvalnov** [comment]
Hi @joaorstavares , confused, library is not asking to use `BCryptDecrypt` anywhere.

How did you get there? And what issues are you experiencing with library itself?

**Comment by joaorstavares** [comment]
I'm talking about the code in jose-jwt>crypto>AesGcm.cs

**Comment by joaorstavares** [comment]
I'm trying to decrypt a message in a .NET Framework project.

Since I cannot use System.Cryptography in it, I tried jose-jwt NuGet Package.

**Comment by dvsekhvalnov** [comment]
@joaorstavares, still not follow :(

`jose-jwt` is heavily relies on System.Cryptography, if you can't use it by some reason, library will not help much here, it can't work without.

**Comment by dvsekhvalnov** [comment]
closed due to inactivity, feel free to re-open if more questions.
