### ISSUE TITLE
nimbus-jose-jwt change from JSON Smart to GSon upgrade has breaking changes on serialization and desrialization for jsonObject

### ISSUE THREAD

**Issue by far768** [dvsekhvalnov/jose-jwt#241]
**Issue Description**:
When generating JWTtoken,
Before upgrading to version 9.24+, serialization and de-serialization of a 'JSONObject' containing a class object with a field of type 'Map<String, List<String>>' worked correctly. This was because the getter method was being called during serialization, ensuring proper handling of the data. However, after upgrading to version 9.24+, issues arose where serialization is performed directly on the field type, neglecting to use the getter method for serialization.

**Steps to Reproduce:**
1. Define a class with a field of type `Map<String, List<String>>`.
2. Ensure the class has appropriate getter and setter methods for the field (In my case it is manipulated to have List<String> type for handling client side use case).
3. Serialize an instance of this class using `JSONObject`.
4. Deserialize the JSON object back into an instance of the class.

**Expected Behavior:**
- The getter method for the field should be invoked during serialization, ensuring correct handling of the data.

**Actual Behavior:**
- Serialization occurs directly on the field type, bypassing the getter method.

**Additional Information:**
- This issue started occurring after upgrading to version 9.24+.
- JSON to Gson change has the impact. tried using TypeAdapterFactory class to use custom TypeAdapter but that is not getting invoked/used by gson on execution.

**Tech stack:**
- Java Version: 17+
- Library/Tool Version: Spring 3+

**Comment by far768** [comment]
Note : using EncryptedJWT for token encryption and that process the serialization of claims taking place.

**Comment by dvsekhvalnov** [comment]
Hi @far768 , guess you've posted issue to wrong project?

I'm not a guy behind `nimbus` (though do cross compatibility tests against it).

**Comment by far768** [comment]
yup, realized later, thanks @dvsekhvalnov for correcting.

got the resolution [here](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/540/change-from-json-smart-to-gson-upgrade-has). 

closing this.
