### ISSUE TITLE
Need adding support for RSA_OAEP_512 support in encryption 

### ISSUE THREAD

**Issue by Marks1** [dvsekhvalnov/jose-jwt#245]
HI there

when i use JWT.Encode() to encrypt payload, i set JweAlgorithm, but i can only set it to JweAlgorithm.RSA_OAEP_256, since RSA_OAEP_512 is more secure, do we have plan to support in the future? 

thanks

**Comment by dvsekhvalnov** [comment]
Hi @Marks1 , yeah can consider this. 

It will require .net 4.6+ according to docs: https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaencryptionpadding.oaepsha512

Any library you'd like to interop with? Need to find some for cross-validation.

**Comment by dvsekhvalnov** [comment]
Generated some test cases from Nimbus library, want to pick it up for next release.

**Comment by dvsekhvalnov** [comment]
RSA_OAEP_384 and 512 support have been merged into `master`.

**Comment by dvsekhvalnov** [comment]
v5.1.0 released to nuget.

**Comment by Marks1** [comment]
Thanks @dvsekhvalnov
