### ISSUE TITLE
Can I Use Jose-Jwt Inside TokenValidationParameters

### ISSUE THREAD

**Issue by josh-monreal** [dvsekhvalnov/jose-jwt#247]
I have a .NET 6.0 application which needs to decrypt a JWE that is encrypted using the **A256GCM** algorithm. Is it possible to use the jose-jwt library to create a SecurityKey that can decrypt it?

```
X509Certificate2 pfxCertificate = Cryptography.GetCertificate(certThumbprint, StoreLocation.CurrentUser);
RSA privateKey = pfxCertificate.GetRSAPrivateKey();
RsaSecurityKey tokenDecryptionKey = new RsaSecurityKey(privateKey); 

var handler = new JsonWebTokenHandler();
var result = handler.ValidateToken(token, new TokenValidationParameters
{
    ValidAudience = "api1",
    ValidIssuer = "https://test.com",
    IssuerSigningKey = issuerSigningKey,
    TokenDecryptionKey = tokenDecryptionKey //This results in an error because it is not able to decrypt A256GCM.
});
```

**Comment by dvsekhvalnov** [comment]
Hi @josh-monreal ,

not sure i got the question correctly, what did you mean by "create a SecurityKey" ?

If you know the key (A256GCM assumes shared symmetric key) you can use library to decrypt A256GCM JWE for sure.

**Comment by josh-monreal** [comment]
Thank you @dvsekhvalnov, I found a way to do it. I'll close this now.
