### ISSUE TITLE
521 instead of 512

### ISSUE THREAD

**Issue by davidwhitingnicecxone** [dvsekhvalnov/jose-jwt#250]
https://github.com/dvsekhvalnov/jose-jwt/blob/44d2a08b2ba4329df4445b9dab302743f345684f/jose-jwt/jws/netstandard1_4/EcdsaUsingSha.cs#L92

This Case on line 92 shows "521"
I assume this is a typo and should say "512" given this is for a SHA-512 algorithm.

**Comment by dvsekhvalnov** [comment]
Hi @davidwhitingnicecxone ,

it's definitely not a typo :) asked many times,  P 521 key size if of 65-66 bytes long.
