### ISSUE TITLE
Jwt class is named differently in JOSE-JWT and JOSE-PCL

### ISSUE THREAD

**Issue by xperiandri** [dvsekhvalnov/jose-jwt#26]
In JOSE-JWT it is named `JWT` and in JOSE-PCL it is named `Jwt`.
Could you align to a single style. `Jwt` is preferable

**Comment by dvsekhvalnov** [comment]
Hi @xperiandri ,

i'd love to, but it's now part of public api. Once published on nuget - it's forever. Don't want to introduce incompatible change for just 2 capital letters.

Probably in future if we have more incompatible changes between releases.

**Comment by xperiandri** [comment]
Not a big deal! Just increase a version number :)

**Comment by xperiandri** [comment]
> Probably in future if we have more incompatible changes between releases.

I ment exactly such a case

**Comment by dvsekhvalnov** [comment]
closing as too old.
