### ISSUE TITLE
Sign AND encrypt token

### ISSUE THREAD

**Issue by vaindil** [dvsekhvalnov/jose-jwt#31]
**EDIT:** I may have found a bug in my code, just a moment!

I'm trying to sign and then encrypt a token. I saw #15, but that method doesn't appear to be working. Any ideas?

If I only sign the token, no encryption, the token is valid.

Generating the token:

```csharp
var signedToken = Jose.JWT.Encode(payload, Globals.JwtSigningKey, Jose.JwsAlgorithm.HS256);
var encryptedToken = Jose.JWT.Encode(signedToken, Globals.JwtEncryptionKey, Jose.JweAlgorithm.DIR, Jose.JweEncryption.A256GCM);
return encryptedToken;
```

Decoding the token:

```csharp
var decryptedToken = Jose.JWT.Decode(token, Globals.JwtEncryptionKey, Jose.JweAlgorithm.DIR, Jose.JweEncryption.A256GCM);
var decodedJson = Jose.JWT.Decode(decryptedToken, Globals.JwtSigningKey);
return decodedJson;
```

The generated token looks like this:

> eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..BCS3zCOB6GoY92cF.6mgN34S6aGzOGzQ9ye_jL6ee3Ez8UrvdVnLzCY3N0EfDoZXzEBAUjZc6DfMsuES3K9J8FsU7NbrsIEAfi5Kh4YcvSZ0c28bly6PmbWtk5wzZhgX95n1ovMnuJsVfGyg7gKqw5ZOJ_MJIWKDEX1UrN93wWl95q4SDF98dTF4-g_a7SGzgqfLIVK3q7-Gkm6NCNhVmp46_t97DMMhleWHzqNoOB6_FeyJ6PrFlS_toHSgrq-1ysPh4l8OO9D4C--QrEu2PE4-m3Rt4-PvAtnZl-bPINgv073DArN3ZSB8EfEi-zBYcU7s8RXXs_6uawRS0z3c3L2z3I-kTBLH-_Lkawb7GyEFqNp8fx-hKvLXMx6M.3b2jBZKQYUQ1gde11b_DzA

**Comment by dvsekhvalnov** [comment]
Hi @vaindil ,

what error are you getting?

**Comment by vaindil** [comment]
I'm very sorry, this was a problem on my end and not with the library. Thank you, this library is awesome!

**Comment by dvsekhvalnov** [comment]
You welcome.
