### ISSUE TITLE
JwsAlgorithm.RS256 Signing Failed in .NET Framework 4.6+

### ISSUE THREAD

**Issue by ryanelian** [dvsekhvalnov/jose-jwt#32]
![jose-notsupported](https://cloud.githubusercontent.com/assets/8892187/17609740/f61fba80-6061-11e6-9ab6-bf80f4c608bd.PNG)

Then I saw this MSDN:

https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsa.decryptvalue(v=vs.110).aspx

NotSupportedException: This method call is not supported. This exception is thrown starting with the .NET Framework 4.6. 
Remarks: In the .NET Framework 4.5.2 and earlier versions of the .NET Framework, this method was abstract. However, the only implementation by a derived class, RSACryptoServiceProvider.DecryptValue, also threw a NotSupportedException exception.

**Comment by dvsekhvalnov** [comment]
Hi @ryanelian ,

just tried, both RS256 signing and decoding working pretty well on my .NET Framework 4.6.1.

Would you mind attach minimal unit test or may be upload/attach VS solution (like console app) which shows problem, so i can try it?

**Comment by ryanelian** [comment]
I don't mind but it doesn't show when run locally, I should have made this clearer, I apologize.

It doesn't run when the web application is hosted in Azure.

**Comment by dvsekhvalnov** [comment]
Are you sure it is using .NET Framework 4.6 at all?

**Comment by ryanelian** [comment]
![passport-azure](https://cloud.githubusercontent.com/assets/8892187/17615771/81c0db54-609a-11e6-9d75-1fde3998bbc4.PNG)

Yes I am sure.

This is the code snippet that caused the failure:

![screenshot 2016-08-12 14 39 48](https://cloud.githubusercontent.com/assets/8892187/17615801/b9e21674-609a-11e6-8f1c-49af9cd28f7c.png)

Before you burn me for not using dictionary for serializing the data to JSON, I'm using Newtonsoft JSON for the job:

```c#
public class JoseNewtonsoftMapper : IJsonMapper
    {
        public string Serialize(object obj)
        {
            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };

            return JsonConvert.SerializeObject(obj, Formatting.Indented, settings);
        }

        public T Parse<T>(string json)
        {
            var settings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };

            return JsonConvert.DeserializeObject<T>(json, settings);
        }
    }
```

**Comment by dvsekhvalnov** [comment]
Do you know is any kind of specific .net version? .net 4.6.x?  May be some Azure specific .net version?

`RSAPKCS1SignatureFormatter` class have been there since .net framework 1.1.  I have no idea why it is calling `RSA.Decrypt` internally and why it is `NotImplemented`.

What type if `Key.GetCrypto()` returns in your code?

I even don't know, i can upgrade to .net framework 4.6.2 and see if there is a bug. Any other thoughts?

**Comment by ryanelian** [comment]
`Key.GetCrypto()` returns RSACng that reads from an XML containing the private key.

> May be some Azure specific .net version?

I actually suspect that this is the case but I am not 100% sure.

**Comment by dvsekhvalnov** [comment]
`RSACng` ? Hm. It is .netcore that expects key of type `RSA` (which is `RSACng`), .net framework expects `RSACryptoProvider`.

Can you try `RSACryptoProvider`?

**Comment by ryanelian** [comment]
Sure thing, hold on.

I've actually read somewhere that RSACng is actually the preferred new way for these businesses, so I decided to used it for brand new application.

**Comment by dvsekhvalnov** [comment]
Can you try this snippet:

```c#
Key.GetCrypto().SignData(new byte[]{...any thing here},  HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
```

to see if it failing with any exception?

**Comment by ryanelian** [comment]
Amazing, the token signing is actually successful when used with `RSACryptoProvider`. You're the best. :+1: 

> Key.GetCrypto().SignData(new byte[]{...any thing here},  HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

No error when used with `RSACng`.

**Comment by dvsekhvalnov** [comment]
Ok, thank you. Feel free to close if you are unblocked ).

I think i will start aligning .net 4.6 and .netcore little bit more in terms of keys, because they are really closer than older version. Eventually you probably can use both types of keys with .net 4.6.. but will take some time.

**Comment by ryanelian** [comment]
> I think i will start aligning .net 4.6 and .netcore little bit more in terms of keys, because they are really closer than older version. Eventually you probably can use both types of keys with .net 4.6.. but will take some time.

That's nice to hear. Although, I'd imagine that all you need to do for updating the API is to first do a simple [is check](https://msdn.microsoft.com/en-us/library/scekt9xw.aspx) before using the key, to check whether it's the `RSACryptoServiceProvider` or the `RSACng`. 
(So the .NET 4.6 library is still backward compatible to the older technique too!)

Alrighty I'll close this issue. Thank you so much for the help. :+1:
