### ISSUE TITLE
Project.json dependencies

### ISSUE THREAD

**Issue by leastprivilege** [dvsekhvalnov/jose-jwt#35]
It would be cleaner to list your dependencies explicitly - otherwise you are referencing way to many assemblies (that you don't need).

This references the whole netstandard lib:
https://github.com/dvsekhvalnov/jose-jwt/blob/master/jose-jwt/project.json#L69

**Comment by dvsekhvalnov** [comment]
is is considered a bad practice?

**Comment by brockallen** [comment]
Somewhat; Microsoft recommends for library developers to cull the dependency list to only those things you need.

**Comment by leastprivilege** [comment]
yes.

**Comment by dvsekhvalnov** [comment]
ok, i'll review, np.

**Comment by sandersaares** [comment]
If that is done, care must be taken to ensure that changes to references/versions/dependencies do not cause the list to go out of sync, though. I personally found with some of my libraries that it was too much effort and introduced too much risk for mistakes to maintain a manual list.

Anyway, I vaguely recall that in the next version of the tooling, there was supposed to be some automation in the packaging tooling for this, though I cannot find the reference. Perhaps the context under discussion was VS "15".

**Comment by leastprivilege** [comment]
Sure - at least the top level dependencies.

But until this "smart" tool from MS is available - manual trimming is needed - otherwise this happens:

![screenshot 2016-08-17 10 15 52](https://cloud.githubusercontent.com/assets/1454075/17729296/c5e79030-6463-11e6-9468-549dc8089b61.png)

**Comment by nathan-alden** [comment]
Thanks for pointing this out, Dominick. This is something I've missed in my own class libraries.

**Comment by nathan-alden** [comment]
@leastprivilege How do you go about determining what NuGet packages need to be referenced for a particular class? This is what I'm struggling with in trying to avoid referencing `NETStandard.Library`. The Microsoft documentation for these namespaces does not appear to include what NuGet package should be referenced.

**Comment by leastprivilege** [comment]
trial and error.

**Comment by dvsekhvalnov** [comment]
trial and error works for me :)

@leastprivilege if you around, would you mind to review: https://github.com/dvsekhvalnov/jose-jwt/commit/87bfa53b82b6a7564be79f5a805c413ff8dbfb30

**Comment by dvsekhvalnov** [comment]
released to nuget.org
