### ISSUE TITLE
Get CngKey from X509Certificate2

### ISSUE THREAD

**Issue by sreejithvijayann** [dvsekhvalnov/jose-jwt#36]
I have an .Net Core1.0 application and  was trying to decode the JWT token using Jose.Decode() method. I am having a X509Certificate2 type certificate against which the token should be validated.
Most of the samples decodes the token using the below code:
   `var publicKey = new X509Certificate2(@"certs\certificate_pub.crt", "", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet).PublicKey.Key;

 var decodedToken = JWT.Decode(token, publicKey);`

When I tried the same code it seems like there is no PublicKey.Key property, instead the PublicKey.EncodedKeyValue is available. What should I do to make the Decode working? How the certificate should be manipulated for getting the required key?
![image](https://cloud.githubusercontent.com/assets/19497807/17733610/2007d30a-6495-11e6-89ce-c39abed6e41f.png)
Any help would be appreciated.

**Comment by sandersaares** [comment]
I would suggest the `X509Certificate2.GetRSAPublicKey()` extension method for this purpose, though I have not checked that it functions as expected on .NET Core. This extension method should be available starting from .NET Standard 1.3.

**Comment by dvsekhvalnov** [comment]
Hi @sreejithvijayann , what @sandersaares  said.

Checkout tests: https://github.com/dvsekhvalnov/jose-jwt/blob/master/UnitTests/TestSuite.cs#L2284

**Comment by sreejithvijayann** [comment]
Hi @sandersaares , @dvsekhvalnov
Thank you for the reply
When I tried 
`var publicKey = (RSA)certificate2.GetRSAPublicKey() ;
                    string decodedToken = Jose.JWT.Decode(token, publicKey, JwsAlgorithm.ES384);
`
it throws the below error
![image](https://cloud.githubusercontent.com/assets/19497807/17735152/63e4b0e4-649e-11e6-9142-7c550fece50c.png)

**Comment by sandersaares** [comment]
Ah, you use ECDSA? Then You will probably want `GetECDsaPublicKey()` instead.

**Comment by sreejithvijayann** [comment]
GetECDsaPublicKey() also raises the same exception..

**Comment by dvsekhvalnov** [comment]
Ah.. ECDSA. 

Well, `jose-jwt` currently not expecting key of type `ECDsa`  . Though it sounds like good enhancement. I'll add.

For now you can only pass `CngKey`, how about https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificateextensions.getcngprivatekey(v=vs.110).aspx ?

**Comment by sreejithvijayann** [comment]
That extension seems to be no more available
https://social.msdn.microsoft.com/Forums/vstudio/en-US/b690a2ce-1f1f-4de8-8ab5-76800044640c/where-is-hascngkey?forum=netfxbcl

**Comment by dvsekhvalnov** [comment]
Ok, then until i add support for `ECDsa` you stuck with `EccKey.New(x,y,d)` helper. 

You can extract x and y values from PEM encoded ECDSA key, but i don't have enough details to show working sample.

**Comment by sreejithvijayann** [comment]
I googled about extracting the said values, but could not figure it out.

**Comment by sreejithvijayann** [comment]
@dvsekhvalnov Are you planning to add the support in near time?

**Comment by dvsekhvalnov** [comment]
@sreejithvijayann , yep, will be next `2.1` release. But i don't have any ETA right now.

**Comment by sreejithvijayann** [comment]
thank you @dvsekhvalnov looking forward to the release

**Comment by dvsekhvalnov** [comment]
While i'm on it.. have you checked https://docs.microsoft.com/en-us/dotnet/core/api/system.security.cryptography.ecparameters#System_Security_Cryptography_ECParameters ?

It seems you can just get it from `ECDsa` object via `https://docs.microsoft.com/en-us/dotnet/core/api/system.security.cryptography.ecdsa#System_Security_Cryptography_ECDsa_ExportParameters_System_Boolean_` call.

**Comment by sreejithvijayann** [comment]
I could not check on that. Will do ASAP.
Thank you.

**Comment by dvsekhvalnov** [comment]
@sreejithvijayann , i've added `ECDsa` key support under ES-* signing algorithms. 

Not yet on nuget.org but you can checkout master branch and try. Docs and samples are updated.

**Comment by dvsekhvalnov** [comment]
Currently in `master`. Will be released as of v2.2 to nuget.org

**Comment by dvsekhvalnov** [comment]
released to nuget.org
