### ISSUE TITLE
[BUG] - RS256 Invalid algorithm specified

### ISSUE THREAD

**Issue by huyttq** [dvsekhvalnov/jose-jwt#40]
#Env:
- jose-jwt 2.0.1 
- .NET framework 4.6.1
- Use jwt-2048.p12 pem file in UnitTest project

Calling to this method:
```
var payload = new Dictionary<string, object>()
            {
                { "sub", "mr.x@contoso.com" },
                { "exp", 1300819380 }
            };

var privateKey = new X509Certificate2(@"C:\path\to\jwt-2048.p12", "1", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet).PrivateKey as RSACryptoServiceProvider;

string token = Jose.JWT.Encode(payload, privateKey, JwsAlgorithm.RS256);
```
          

Throwing this exception

**Unhandled Exception: System.Security.Cryptography.CryptographicException: Invalid algorithm specified.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash, Int32 cbHash, ObjectHandleOnStack retSignature)
   at System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   at System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, Int32 calgHash)
   at System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(Byte[] rgbHash)
   at Jose.RsaUsingSha.Sign(Byte[] securedInput, Object key)
   at Jose.JWT.EncodeBytes(Byte[] payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders)
   at Jose.JWT.Encode(String payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders)
   at Jose.JWT.Encode(Object payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders)**

**Comment by huyttq** [comment]
FYI: Finally I can resolve the issue

The error happened because the default CSP does not support SHA2 version (i.e SHA256, SHA384, SHA512) algorithm (see details [here](http://hintdesk.com/c-how-to-fix-invalid-algorithm-specified-when-signing-with-sha256/))

Suggesting that the jwt-2048.p12 file should includes "Microsoft CSP Name: Microsoft Enhanced RSA and AES Cryptographic Provider"

Please closed this issue

**Comment by dvsekhvalnov** [comment]
Hi @huyttq ,

glad you resolve this. Actually this is mentioned in the docs: https://github.com/dvsekhvalnov/jose-jwt#rs--and-ps--family

There are number of ways to get rid of this, simplest probably just re-import if environment allows. Or force to use "enchanced" CSP. Or the one you mentioned will work as well.

I probably should update docs to include more info on it. Thanks for the link.

**Comment by dvsekhvalnov** [comment]
Will keep open, until docs update.

**Comment by huyttq** [comment]
Cool, it will be even better if there are some guidelines for creating self signed X509Cert

**Comment by dvsekhvalnov** [comment]
docs added.

**Comment by 0xcfff** [comment]
@dvsekhvalnov I see that the bug is marked as closed but still want to rise a question regarding difference in MS JwtSecurityTokenHandler implementation and Jose one. It happened that both components are used in the same project with the same set of keys. MS version works fine whereas Jose fails with this error. I investigated this a bit deeper and found how MS does this. They implemented a trick that is similar to re-importing CSP, but it does not require Export permissions for private key, here is the link to the code: https://github.com/Microsoft/referencesource/blob/master/System.IdentityModel/System/IdentityModel/Tokens/X509AsymmetricSecurityKey.cs#L54.
I'd propose to implement the same trick in Jose, at least for those platforms where it is possible. If you support this idea, I could prepare PR for it.

**Comment by dvsekhvalnov** [comment]
Hi @0xcfff ,

well first of all tricks documented here: https://github.com/dvsekhvalnov/jose-jwt#rsacryptoserviceprovider :)

second, we get rid of all re-export keys code from `jose-jwt`. And the reason it is not responsibility of library to deal with it. If you want to re-export/fix CSP or something else do it before library call.

If you on .Net46+ or .NetCore you can simply use new extensions to get private key without re-export hassle https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions.getrsaprivatekey(v=vs.110).aspx

See https://github.com/dvsekhvalnov/jose-jwt#rs--and-ps--family for details.
