### ISSUE TITLE
Error while loading assembly: A strongly-named assembly is required

### ISSUE THREAD

**Issue by vcarluer** [dvsekhvalnov/jose-jwt#44]
Hello,

I cannot used jose-jwt in my Asp.net 4.5.2 signed web application because it is requiring a signed assembly for jose-jwt.
If I remove signature on my web app it works.
Can you please sign your assembly for us to be able to use it?
Or maybe there is another way to do it?

Thank you.

**Comment by dvsekhvalnov** [comment]
Hi @vcarluer ,

please see https://github.com/dvsekhvalnov/jose-jwt/issues/5  

feel free to take same route (e.g. use StrongNameSigner)

**Comment by vcarluer** [comment]
Ok thank you, will try this.

Le 29 sept. 2016 12:59 PM, "dvsekhvalnov" <notifications@github.com> a
écrit :

**Comment by dvsekhvalnov** [comment]
Hi @vcarluer ,

happy with StrongNameSigner? Can we close this ticket?

**Comment by vcarluer** [comment]
Didn't try it yet because we have postpone the lib usage but read the
StrongNameSigner Doc and it is ok for us. You can close the ticket.

**Comment by dvsekhvalnov** [comment]
Thank you for update.
