### ISSUE TITLE
Question: Encrypted tokens with ASP.NET core

### ISSUE THREAD

**Issue by raghur** [dvsekhvalnov/jose-jwt#54]
So I think this might be more of a ASP.NET core question than jose-jwt - but I configured the asp.net core with `UseJwtBearerAuthentication` as in the front page. This works fine if I send in a unencrypted, signed token but fails when I send in an encrypted token. I've tried

```
String encryptionKey = "hex string here";
byte[] key = encryptionKey.ToByteArray();
tokenValidationParams.TokenDecryptionKey = new SymmetricSecurityKey(key);

```

but this just ends in `IDX10600: Decryption failed. There are no security keys for decryption.`

Is there an example showing how to use encrypted tokens?

**Comment by dvsekhvalnov** [comment]
Hi @raghur , the guide was contributed by https://github.com/ryanelian 

Would you mind if i connect you together and probably @ryanelian can answer your questions better than me? :)

**Comment by ryanelian** [comment]
Hi!

Unfortunately, I haven't tried encrypted tokens. Maybe the ASP.NET Security Team at https://github.com/aspnet/Security can better answer your question, as I am quite busy with my IRL responsibilities at the moment.

It is an interesting question though. You should contribute to the README if you managed to know how. ;D

**Comment by raghur** [comment]
NP - I've meanwhile figured out what works :). So the error that I posted comes up as my token was encrypted with A128_GCM using nimbusds-jose-jwt. Apparently the .NET stack doesn't support this and hence the error.
Since I have control on the token generation too, I changed the encryption algo to A128CBC-HS256 - and this works fine on the .NET side (there's no need to set the algo or anything - you just need to have the same shared key provided as a `TokenDecryptionKey = new SymmetricSecurityKey(<key byte[]>)

**Comment by andre-ss6** [comment]
@raghur sorry for necroing this, but I'm trying to use encrypted tokens with asp.net core (I have control on token generation as well) but I haven't figured out how to do it properly. I tried encrypting the token with A128CBC-HS256 as well (using this https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet), but ASP.NET JwtBearer middleware won't recognize the token.

Also, I don't get something. TokenValidationParametersTokenDecryptionKey only accepts a SecurityKey. I guess I should set here the key used for encryption with AES128. But what about the HMAC auth key? 

Can you please give me some light on how you managed to accomplish this?

**Comment by dvsekhvalnov** [comment]
Andre,

AES128CBC-HS256 expecting 256 bit key (array of bytes of 32 length), first
128 bits used as HMAC key, second 128 bits as AES key.  Same is holding
true for other variations (384, 512 bits).

Would help if you can provide more error description you getting from
ASP.NET.

**Comment by andre-ss6** [comment]
@dvsekhvalnov Yea I was actually doing something wrong (it wasn't really respecting the JWE Compact standard). The error message was simply that it couldn't find a token validator for my token (not really helpful :-1: ). Anyway, I ended up just using your library instead of doing it by hand using Azure AD's. Thanks for the help anyway! :smile:
