### ISSUE TITLE
NotSupportedException 

### ISSUE THREAD

**Issue by johnkiddjr** [dvsekhvalnov/jose-jwt#56]
I'm getting NotSupportedException with the message "Method is not supported." when running an application using the jose-jwt library on any computer other than my development computer. It works perfectly on the development computer. The entire build directory contents is being placed on the test computer, but is still generating the error.

Below is the code generating the error (some things have been changed like the payload contents since they contain sensitive information).

```
DateTimeOffset expiration = new DateTimeOffset(DateTime.Now);

var payload = new Dictionary<string, object>()
{
    { "sub", "test@test.com" },
    { "exp", expiration.ToUnixTimeSeconds() }
};
RSA pKey = new X509Certificate2(@"C:\directory\comb.pfx").GetRSAPrivateKey();
return Jose.JWT.Encode(payload, pKey, Jose.JwsAlgorithm.RS256);
```

**Comment by dvsekhvalnov** [comment]
Hi @johnkiddjr ,

need some details:

1. full stack trace
2. .net or netcore version 
3. operating system 
4. what is app you are building? is it asp.net application, console app, windows application, e.t.c.

thank you.

**Comment by johnkiddjr** [comment]
Hi @dvsekhvalnov ,

1. 
```
at System.Security.Cryptography.RSA.DecryptValue(Byte[] rgb)
   at System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(Byte[] rgbHash)
   at Jose.RsaUsingSha.Sign(Byte[] securedInput, Object key)
   at Jose.JWT.EncodeBytes(Byte[] payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders)
   at Jose.JWT.Encode(String payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders)
   at Jose.JWT.Encode(Object payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders)
   at AdobeEnterpriseSync.JWTManage.GetJWTToken() in d:\documents\visual studio 2015\Projects\AdobeEnterpriseSync\AdobeEnterpriseSync\JWTManage.cs:line 50
```
2. .net4.6.1
3. Windows Server 2012 R2
4. 2.1, got it from NuGET
5. Console app - specifically to sync accounts from Adobe Enterprise with AD

**Comment by dvsekhvalnov** [comment]
hm.. don't have 2012 R2 at the moment. But working for me on 2012. 

Are you sure you are not trying to run Debug build of your app on other computer?

**Comment by johnkiddjr** [comment]
The build is set to Release.

I tried on a 2016 server and it works fine there..

**Comment by dvsekhvalnov** [comment]
Ah, i have an idea:  you getting key by calling `.GetRSAPrivateKey();` extensions method on`X509Cetificate2` which is not what library expecting.

You need to pass `RSACryptoProvider` instance. 

Can you try it and tell if it will work?

The fastest (not the best) way to get it from `X509Certificate2` is something like:

```        private RSACryptoServiceProvider PrivKey(X509Certificate2 x509)
        {
            var key = (RSACryptoServiceProvider)x509.PrivateKey;

            RSACryptoServiceProvider newKey = new RSACryptoServiceProvider();
            newKey.ImportParameters(key.ExportParameters(true));

            return newKey;
        }
```

**Comment by johnkiddjr** [comment]
With that code I got "Key not valid for use in specified state."

Stacktrace:
```
System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ExportKey(SafeKeyHandle hKey, Int32 blobType, Object cspObject)
   at System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(Boolean includePrivateParameters)
   at AdobeEnterpriseSync.JWTManage.PrivKey(X509Certificate2 x509) in d:\documents\visual studio 2015\Projects\AdobeEnterpriseSync\AdobeEnterpriseSync\JWTManage.cs:line 78
   at AdobeEnterpriseSync.JWTManage.GetJWTToken() in d:\documents\visual studio 2015\Projects\AdobeEnterpriseSync\AdobeEnterpriseSync\JWTManage.cs:line 51

```

**Comment by dvsekhvalnov** [comment]
Can you show me code snippet? Are you signing or verifying JWT token?

**Comment by johnkiddjr** [comment]
Other than Encoding it via the library as shown, no other manipulation is happening to the JWT. I am not currently verifying it before sending it, but the exception is happening on the line that is Encoding it, so I never get a finished product to verify.

**Comment by dvsekhvalnov** [comment]
Ok, here we go, you need something like this:

```
X509Certificate2 cert = new X509Certificate2("your-cert.pfx", "password-for-pfx", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet);
```

**Comment by johnkiddjr** [comment]
@dvsekhvalnov That did the trick!

I do still find it interesting that this code:

```
RSA pKey = new X509Certificate2(@"C:\directory\comb.pfx").GetRSAPrivateKey();
return Jose.JWT.Encode(payload, pKey, Jose.JwsAlgorithm.RS256);
```
Works fine on Windows 10 and Server 2016 (that I've tested) but doesn't work on 2012 R2.

Either way, thanks for the help!

**Comment by dvsekhvalnov** [comment]
Sorry about this, `RSACryptoProvider` was in earlier .net version, now in 4.6 keys are much more aligned with netcore, so i'm slowly working on unify that and eventually on .net 4.6 you'll be able to use both types of keys.. but you know time if always against us

**Comment by dvsekhvalnov** [comment]
Better support for keys coming in v2.2, will keep issue open till release.

**Comment by dvsekhvalnov** [comment]
released to nuget.org
