### ISSUE TITLE
To the repo maintainer(s): Can you create a GitHub release for v2.0.2?

### ISSUE THREAD

**Issue by nathan-alden** [dvsekhvalnov/jose-jwt#57]
First of all, thank you so much for this robust JWT library! I was, probably like many others, a reluctant user of `System.IdentityModel.Tokens.Jwt` in the past, but that library seems to be no longer maintained.

I work for a company that has a very strict OSS rules. We are not allowed to use NuGet packages that cannot be tied back to a specific GitHub release. We're currently using jose-jwt 2.0.2 from nuget.org. Do you think it's possible that you could create an official release on GitHub so that we can continue to use your great library? I noticed you have branches for a few different versions but, unfortunately, that won't satisfy our gatekeepers. :(

**Comment by dvsekhvalnov** [comment]
Hi @nathan-alden , 

help me understand what exactly are you looking for. Do you want me to build and upload .dll(s) somewhere on github? It's definitely doable.

**Comment by dvsekhvalnov** [comment]
@nathan-alden , is this what are you looking for? https://github.com/dvsekhvalnov/jose-jwt/releases/tag/v2.0.2

**Comment by dvsekhvalnov** [comment]
I also added latest v2.1.0 release: https://github.com/dvsekhvalnov/jose-jwt/releases/tag/v2.1.0

**Comment by nathan-alden** [comment]
Yes! You are a lifesaver. :) That's exactly what my company requires in order for us to use OSS packages officially.

**Comment by dvsekhvalnov** [comment]
Ok, i'll keep it consistent with nuget.org release for future version :)

Feel free to close if all good.

**Comment by nathan-alden** [comment]
Thank you!
