### ISSUE TITLE
Is jose-jwt safe from invalid curve attack?

### ISSUE THREAD

**Issue by sandersaares** [dvsekhvalnov/jose-jwt#59]
I noticed an article claiming that many JOSE libraries are vulnerable to some sort of cryptographic attack: http://blog.intothesymmetry.com/2017/03/critical-vulnerability-in-json-web.html

Is jose-jwt also affected?

**Comment by dvsekhvalnov** [comment]
Hi @sandersaares ,

nope, jose-jwt is not affected, no action needed. 

I was in a loop with Antonio (security researcher) before it was disclosed. To be on the safe side appropriate unit tests were added as a proof, check it out: https://github.com/dvsekhvalnov/jose-jwt/blob/master/UnitTestsNet46/SecurityVulnerabilitiesTest.cs

Feel free to close ;)

**Comment by sandersaares** [comment]
Thanks for fast confirmation!
