### ISSUE TITLE
RS256 - Verify with a public key

### ISSUE THREAD

**Issue by jahead** [dvsekhvalnov/jose-jwt#60]
Sorry this a dumb question. 
Can we use a file containing a public cert only to verify that the key is valid?

scenario:
services have only access to the public key, and auth server has access to the public/private key.
auth server signs and hands out jwt tokens, clients use them on services which services verify using the public cert. 

I would assume that this a common problem. But your docs say 

Encode
```
var payload = new Dictionary<string, object>()
{
    { "sub", "mr.x@contoso.com" },
    { "exp", 1300819380 }
};

var privateKey=new X509Certificate2("my-key.p12", "password", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet).PrivateKey as RSACryptoServiceProvider;

string token=Jose.JWT.Encode(payload, privateKey, JwsAlgorithm.RS256);
```

Decode
```
var payload = new Dictionary<string, object>()
{
    { "sub", "mr.x@contoso.com" },
    { "exp", 1300819380 }
};

var privateKey=new X509Certificate2("my-key.p12", "password", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet).PrivateKey as RSACryptoServiceProvider;

string token=Jose.JWT.Encode(payload, privateKey, JwsAlgorithm.RS256);
```

both of which I understand is using the private key? or is the doc not correct.
I'm just looking to confirm we can use the public cert to decode and verify. 
I'd try myself but we aren't using .p12 files, so there is extra work involved in loading the .key /.cert files

**Comment by dvsekhvalnov** [comment]
Hi @jahead , 

https://github.com/dvsekhvalnov/jose-jwt#verifying-and-decoding-tokens

docs saying  private/public is symmetric to what you've been using when encoding. If you do encryption you usually encode with public and decode with private (so only intended recipient can view it). If you do signing, you sign with private and verify with public (so everybody can proof that messages was signed by holder of private key)

Here is example you probably looking for for verifying signed tokens:

```C#
string token = "eyJhbGciOiJFUzI1NiIsImN0eSI6InRleHRcL3BsYWluIn0.eyJoZWxsbyI6ICJ3b3JsZCJ9.EVnmDMlz-oi05AQzts-R3aqWvaBlwVZddWkmaaHyMx5Phb2NSLgyI0kccpgjjAyo1S5KCB3LIMPfmxCX_obMKA";

var publicKey=new X509Certificate2("my-key.p12", "password").GetRSAPublicKey();

string json = Jose.JWT.Decode(token, publicKey);
```

**Comment by dvsekhvalnov** [comment]
Also you can just convert you pem public key to .p12 not to mess with loading it programmatically:

`openssl pkcs12 -export -out public_certificate.p12 -in public.crt`

**Comment by jahead** [comment]
@dvsekhvalnov thanks, I figured as much, i just wanted to confirm before I went through with the implementation. Not seeing it as an example to confirm my assumption just made me uneasy. 

True, while that may not be an option for the implementation, i probably could of done that to test my assumption. Sorry for inconvenience. 

If there's anything i do to help, let me know.

**Comment by j0zeft** [comment]
This might be a dumb follow up question...
I need also to extract a public key from a certificate file, which I can extract as an array of bytes, and I want to use that to verify a signed JWT token.
I know I should be using this 

` string json = Jose.JWT.Decode(token, publicKey); `

But the point is that I don't have a password to use for extracting the public key, I just read the certificate file to a variable, then I get the public key out of it, like this

`            string Certificate = @"c:\Development\tokens and keys\SomeCertificate.cer";`
`            X509Certificate cert = X509Certificate.CreateFromCertFile(Certificate);`
`            byte[] publicKey = cert.GetPublicKey();`

I tried that, and received an exception in runtime telling me that I should be using an Asymmetrical key, which I find quite strange as the token was signed with a private key, and I'm trying to use the Asymmetrical (public) key for verification yet it's failing.

What am I doing wrong and am I on the right track or way off?
Thanks in advance for your time.
