### ISSUE TITLE
Unable to load DLL 'bcrypt.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by fuquanli** [dvsekhvalnov/jose-jwt#62]
jose-jwt integrated project running on linux + nginx will have such a problem.
I do not know what to do；please help me ,please!

**Comment by dvsekhvalnov** [comment]
Hi @fuquanli ,

can you provide little bit more info? Are you running .netcore project on linux? Stacktrace probably?

I really doubt bcrypt.dll available on *nix systems.

**Comment by fuquanli** [comment]
yes.

I run the .net core project on linux.

Every time you run to JWT.Encode (), it throws an exception;

Error:Unable to load DLL 'bcrypt.dll': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)

**Comment by dvsekhvalnov** [comment]
@fuquanli you probably attempting to decode some of unsupported algorithms on Linux.

If you post example of your JWT token i can say more precisely. 

Also check out this: https://github.com/dvsekhvalnov/jose-jwt/issues/45

**Comment by fuquanli** [comment]
![default](https://cloud.githubusercontent.com/assets/25790404/24837395/b3b4c5d4-1d65-11e7-8f6b-b9955dadb965.PNG)
thank ，I went to read it

**Comment by fuquanli** [comment]
![image](https://cloud.githubusercontent.com/assets/25790404/24837426/4d7c7608-1d66-11e7-92af-45506c476b05.png)
thank you! 
I went to read it.

**Comment by dvsekhvalnov** [comment]
@fuquanli , A256GCMKW - is not supported on linux, because AES GCM is not in corefx yet.

**Comment by fuquanli** [comment]
ok,thank you for your help.

**Comment by dvsekhvalnov** [comment]
@fuquanli , ok to close?

**Comment by fuquanli** [comment]
ok

**Comment by KiranKumar7834** [comment]
Hi, i am getting similar issue in pivotal cloud foundry. It is working fine in local .Net core 2.0 but throwing exception in Pcf. 

Is this compatibility included?

**Comment by dvsekhvalnov** [comment]
Hi @KiranKumar7834 ,

would you mind open separate issue and provide more information about your error? Stack trace, OS version, .NET or .NETCORE version, possible some sample code that not working. It will be easier to troubleshoot than in closed ticket :)

**Comment by baharestani** [comment]
.Net 3.1 has in-built support for AES/GCM which works cross platform. Can we customize the algorithm so that it relies on .net rather than windows bcrypt.dll?

**Comment by dvsekhvalnov** [comment]
Hi @baharestani , yes obviously possible, we have separate ticket somewhere to make. But hard to find free time for the project, i'm always welcome PRs and ready to discuss design / whatever.  But can't promise any ETA at the moment.
