### ISSUE TITLE
Ability to customise algorithm and encryption mappings

### ISSUE THREAD

**Issue by freeman** [dvsekhvalnov/jose-jwt#63]
Hello,

We use a vendor provided authentication solution where the JWT do not correctly implement the specifications. Namely the `alg` and `enc` headers are not set to the correct value.

Currently the mapping between the header values and the algorithm used is static and seems not modifiable by user of the library.

It seems there is some code for aiming in this direction in [JWT.cs](https://github.com/dvsekhvalnov/jose-jwt/blob/27beaff995bdd1385d58846062999e39d5b773a9/jose-jwt/JWT.cs#L71) but it does not seem to be publicly accessible.

Would you be interested in a PR allowing to customize the mappings ?

**Comment by dvsekhvalnov** [comment]
Hi @freeman ,

always interested in PRs :) What you asking sounds very similar to https://github.com/dvsekhvalnov/jose-jwt#customizing-algorithm-implementations
 that was in latest v2.3.0 release.

If this is not what you had in mind, would you mind to provide some details?

**Comment by freeman** [comment]
My understanding is that what you are referring to allows to customise the algorithm implementation. My issue is far simpler :)

I have JWT tokens that do not comply exactly with the spec. For example instead of `alg=RSA-OAEP-256` as [specified](https://tools.ietf.org/html/rfc7518#section-4.1), I have tokens which have `alg=RSA_OAEP_256`. These are clearly not compliant but my PR would allow jose-jwt to decode them none the less (and maybe create them ?)

What do you think ?

**Comment by dvsekhvalnov** [comment]
@freeman , you are asking about aliases? E.g. `RSA_OAEP_256` to be an alias for `RSA-OAEP-256` when decoding?  What about encoding? You also would like to put alias alg name to header?

**Comment by freeman** [comment]
Yes exactly. My initial need is only around decoding. Not sure what the correct way would be for encoding, any suggestions ?

**Comment by dvsekhvalnov** [comment]
Need to think about encoding little bit.

Well, for now i'd say `JwtSettings` is right place to do it. I'd suggest `JwtSettings.RegisterAlias(string alias, JweEncryption alg)` to be consistent with rest of API.

If you interested to do PR, i'm perfectly fine with it.

**Comment by dvsekhvalnov** [comment]
released to nuget.org v2.4
