### ISSUE TITLE
Netcore Linux: Specified padding mode is not valid for this algorithm.

### ISSUE THREAD

**Issue by twatson83** [dvsekhvalnov/jose-jwt#68]
Hi,

Im working with .net core in Ubuntu and am having trouble decoding tokens.  Here is the code im using.
```c#
var x509Cert = new X509Certificate2(key);
var publicKey = x509Cert.GetRSAPublicKey();
var token = JWT.Decode(tokenEncrypted, publicKey, JwsAlgorithm.PS256);
```

The following exception is thrown

Message: "Specified padding mode is not valid for this algorithm."
Stacktrace: "   at System.Security.Cryptography.RSAOpenSsl.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)\n   at System.Security.Cryptography.RSA.VerifyData(Byte[] data, Int32 offset, Int32 count, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)\n   at System.Security.Cryptography.RSA.VerifyData(Byte[] data, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)\n   at Jose.JWT.DecodeBytes(String token, Object key, Nullable`1 expectedJwsAlg, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings)\n   at Jose.JWT.Decode(String token, Object key, JwtSettings settings)\n   at ConsoleApplication.Program.Main(String[] args) in Program.cs:line 21"

The following code works with .net 4.5 on Windows.
```c#
var publicKey = new X509Certificate2(Convert.FromBase64String(key)).PublicKey.Key as RSACryptoServiceProvider;
var token = JWT.Decode<Dictionary<string, object>>(tokenEncrypted, publicKey, JwsAlgorithm.PS256);
```

**Comment by dvsekhvalnov** [comment]
Hi @twatson83 ,

can you show test jwt token? Just to make sure nothing wrong here.
Also you don't have to specify expected algorithm to `JWT.Decode` call (not necessary).

But in general i'm afraid this is state of .netcore cryptography support on linux nowadays, and most likely PS just not supported as many other things. So you'd probably stick to HS/RS/ES signing.

**Comment by dvsekhvalnov** [comment]
closed due inactivity. feel free to re-open if needed.
