### ISSUE TITLE
Content type for Nested JWT

### ISSUE THREAD

**Issue by AtlasFrank** [dvsekhvalnov/jose-jwt#7]
First, my compliments on the library.  It's extremely useful and saved me a ton of time.

When a JWE contains a nested JWT, per the spec https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32 the cty: header parameter is required and must be "JWT".  There appears to be no way to adjust the JOSE header to include the content type parameter in this library.

A small nit to be sure but would be great to have an optional parameter or overload that supports this.

Thanks again for the great contribution.

**Comment by dvsekhvalnov** [comment]
Indeed.. there is even no 'typ' for JWE (but there is for JWS)... where was my head.

Thanks for reporting, i'll schedule to add support for additional headers.

**Comment by dvsekhvalnov** [comment]
@AtlasFrank, can you review latest doc: https://github.com/dvsekhvalnov/jose-jwt#adding-extra-headers

, and see if it provides suitable interface for your case? And if all good, i'll push update to nuget.

Thanks.

**Comment by AtlasFrank** [comment]
Very sorry for the delayed response here.  

Yes, this looks great.  Provides a very simple way to add whatever headers are needed and is nice and flexible so it can accommodate revisions in the standard if they occur.

Thanks!

**Comment by dvsekhvalnov** [comment]
@AtlasFrank thanks. Also added support for 2 phase validation.

Pushed to NuGet as v1.9.0.
