### ISSUE TITLE
JWT ECDSA encode without working CngKey implementation

### ISSUE THREAD

**Issue by kode54** [dvsekhvalnov/jose-jwt#77]
Is there any way to import a key from a PEM to the object needed by JWT Encode API, without a working CngKey implementation? I am trying to build with either Mono or .NET Core 2.0, neither of which implement CngKey.

I already have BouncyCastle PemReader, which imports the param.Parameters.G.AffineXCoord.GetEncoded, AffineYCoord.GetEncoded, and D.ToByteArrayUnsigned, which would be sufficient for passing to new EccKey, but EccKey doesn't exist here, either.

I'd also rather not have to buy a license for Chilkat, I want to stay strictly zero cash investment. That also means I'd be willing to write an implementation from scratch, if that's what it takes.

**Comment by dvsekhvalnov** [comment]
Hi @kode54 ,

on the .NET Core or .NET4.6.1+ you can pass either `ECDsa` or `CngKey` types of keys. Unfortunately i can't say anything about mono at this point.

`ECDsa` should work on linux (i hope, 🤞 ).

Also check out this ticket, it contains some information about importing keys from .pem files (not in the library yet, but working on support).
https://github.com/dvsekhvalnov/jose-jwt/issues/25

**Comment by kode54** [comment]
CngKey.cs is this in both Mono and .NET Core:

https://github.com/mono/mono/blob/master/mcs/class/referencesource/System.Core/System/Security/Cryptography/CngKey.cs

Basically, all the functions just throw NotImplementedException.

**Comment by kddlb** [comment]
Well, I have a ```p8``` key obtained from Apple Developer that I want to use to sign tokens with. 

```c#
private static void TokenGet()
{

    TimeSpan t = DateTime.UtcNow - new DateTime(1970, 1, 1);
    long secondsSinceEpoch = (long)t.TotalSeconds;

    if ((_stampOfLastToken <= (secondsSinceEpoch + 120)) && _token != "")
    {
        Program.Log("We don't need a new token, the previous one will still work (hopefully.)");
        return;
    }


    var claimsPayload = new Dictionary<string, object> {
        {"iss", "[[should be your Apple Developer's Team ID]]" },
        {"iat", secondsSinceEpoch },
        {"exp", secondsSinceEpoch + 120 }
    };

    CngKey privateKey;

    using (var reader = File.OpenText("[[private key file for sign, p8 format]]"))
    {
        var param = (ECPrivateKeyParameters)new PemReader(reader).ReadObject();
        privateKey = EccKey.New(
            param.Parameters.G.AffineXCoord.GetEncoded(),
            param.Parameters.G.AffineYCoord.GetEncoded(),
            param.D.ToByteArrayUnsigned());

    }

    _token = Jose.JWT.Encode(claimsPayload, privateKey, Jose.JwsAlgorithm.ES256,
        new Dictionary<string, object> { { "kid", "[[private key ID]]" } });
    Program.Log("New JWT token.");

    _stampOfLastToken = secondsSinceEpoch;

}
```

**Comment by dvsekhvalnov** [comment]
@kode54 , @kddlb  why do you guys want to use CngKey at all? All algos on .NET Core perfectly supports `ECDsa`key. 

You need convert your pcsk8 private key to .p12 file with openssl:

`openssl pkcs12 -export -out key.p12 -inkey privateKey.pem -in certificate.crt`

then just use it:

```c#
var privateKey=new X509Certificate2("key.p12", "password").GetECDsaPrivateKey();
```

Is it make sense?

**Comment by kddlb** [comment]
I tried doing that, but I didn't realize I needed to convert the key 😂 

We'll let you know if that works for us 👍

**Comment by dvsekhvalnov** [comment]
I'd like to include helpers to load popular keys format directly. But it will take some time, not yet there.

**Comment by kode54** [comment]
I can't convert to pkcs12 without a certificate, and I don't have one.

**Comment by dvsekhvalnov** [comment]
Sure you can. Since you owning private key you can generate any kind of
certificate you want. And combine them both to .p12

**Comment by kode54** [comment]
The most I can do with a private key is generate a certificate signing request. Or are you suggesting I also generate my own CA certificate and private key to fulfill the signing request, just so I can create a .p12 file with a certificate I don't even need? This is getting too complicated.

**Comment by dvsekhvalnov** [comment]
@kode54 ,

`openssl req -new -x509 -days 1826 -key privateKey.pem -out my-certificate.crt`

then

`openssl pkcs12 -export -out key.p12 -inkey privateKey.pem -in my-certificate.crt`

will make it.

**Comment by kode54** [comment]
Thank you very much, this works!
