### ISSUE TITLE
strong name

### ISSUE THREAD

**Issue by xclayl** [dvsekhvalnov/jose-jwt#8]
Can you release this with a strong name?
We've had issues in the past with the wrong versions of DLLs being deployed and we use strong names to ensure that the right versions of DLLs are deployed.  That's not so much an issue with your DLL, but if your DLL is not strong named, it'll mean we have to turn off strong names in our assemblies.
Cheers,
Clay

**Comment by dvsekhvalnov** [comment]
Hi @xclayl ,

there was same question in the past, can you take a look at: https://github.com/dvsekhvalnov/jose-jwt/issues/5 and see if same approach will work for you?

**Comment by xclayl** [comment]
OK thanks

**Comment by dvsekhvalnov** [comment]
@xclayl , if StrongNameSigner works for you case, feel free to close ticket.
