### ISSUE TITLE
NetCore 2.0 support

### ISSUE THREAD

**Issue by dvsekhvalnov** [dvsekhvalnov/jose-jwt#82]
Update library to work with .netcore v2 release.

Initial support have been provided by @dalexsoto  in `netcore20` branch.

**Comment by dvsekhvalnov** [comment]
@dalexsoto, decided to provide my progress update :)

Installed fresh netcore/vs2017 environment
Learning how to convert back: project.json -> csproj

**Comment by dvsekhvalnov** [comment]
@dalexsoto, was playing around .netcore20 and i don't see anything that not working with netcore 2.0.  Did several samples with nuget version of library and all working without any issues.

May i ask you what was the reason you added `NETSTANDARD2_0` conditional compilation checks? What haven't been working? 

Having extra conditional compilation check doesn't hurt, but i'm trying to figure out how to test it now.

**Comment by davidparker** [comment]
Any news on this one please?   Its the only piece missing in my .net core 2 project at the moment

many thanks

**Comment by dvsekhvalnov** [comment]
Hi @davidparker ,

i'm not really sure what's needed here, i've opened ticket based on @dalexsoto comment. But it working fine within netcore 2.0 projects.

If you can provide any details around what's not working for you or what you'd like to see supported, i'll take a look.

**Comment by davidparker** [comment]
Not that it isn't working.  It's just haven't been comited yet and sent to
nuget as a package for netstandard 2.0 projects.   I read the comments and
saw that it was ready.  In November.  Just wondering when button will be
pressed and nuget packages updated

Thanks

**Comment by dvsekhvalnov** [comment]
Mm, confused. What exactly need to be pushed to nuget? Why can't you reference latest available version?

**Comment by davidparker** [comment]
You mean reference netstandard 1.  Version of the package?   Instead of
version 2 of the package.    I take it this means no.   You won't be
publishing a netstandard 2 version and that version 1 should be referenced?
   I can try it.  But the dependencies may be tricky.  But yeah sure will
give it a go.   I'm on azure functions 2.0.  So only have net standard2.0.

**Comment by dvsekhvalnov** [comment]
I mean try to reference jose-jwt v2.4.0 in your project and see how it goes.

Right now i'm just not sure what exactly to change in code or in package.json, if you can layout it out to me for dumbs would be nice :)

**Comment by dvsekhvalnov** [comment]
Hey @davidparker , got success with v2.4.0 ? Or lib requires some updates?

**Comment by davidparker** [comment]
Hi yes sorry.  seems to be okay on build but haven't yet created a token
but it should be just fine from what I can tell

**Comment by tnovau** [comment]
Hi, we´re using AspNetCore 2.0. We´re having some troubles with the Jose.JWT.Encode method:

When we try to encode using:

**PBES2 using HMAC SHA with AES Key Wrap key management family of algorithms**

With the sample code in the README.md:
```C#
var payload = new Dictionary<string, object>()
{
    { "sub", "mr.x@contoso.com" },
    { "exp", 1300819380 }
};  	

string token = Jose.JWT.Encode(payload, "top secret", JweAlgorithm.A256KW, JweEncryption.A256CBC_HS512)
```
It throws an exception with the 

> AesKeyWrap management algorithm expectes key to be byte[] array.
> System.ArgumentException: AesKeyWrap management algorithm expectes key to be byte[] array.

**Comment by dvsekhvalnov** [comment]
Hi @tnovau , 

is it exact code you trying to run? It is saying: `JweAlgorithm.A256KW with JweEncryption.A256CBC_HS512` not `JweEncryption.PBES2_HS256_A128KW`.

Probably issues with documentation. Can you try:
```c#
string token = Jose.JWT.Encode(payload, "top secret", JweAlgorithm.A256KW, JweEncryption.PBES2_HS256_A128KW)
```

and let me know how it goes?

**Comment by tnovau** [comment]
Hi @dvsekhvalnov ,
Yes, it is the exact code.

We´re checking but _JweEncryption_ enum doesn't have **PBES2_HS256_A128KW** value.

``` C#
public enum JweEncryption
    {
        A128CBC_HS256, //AES_128_CBC_HMAC_SHA_256 authenticated encryption using a 256 bit key.
        A192CBC_HS384, //AES_192_CBC_HMAC_SHA_384 authenticated encryption using a 384 bit key.
        A256CBC_HS512, //AES_256_CBC_HMAC_SHA_512 authenticated encryption using a 512 bit key.
        A128GCM,
        A192GCM,
        A256GCM
}
```

Is that right?
Thanks, for the quickly response

**Comment by dvsekhvalnov** [comment]
Hey @tnovau , yeah, looks good to me. Sorry don't remember all enumerations and sdk by heart :)

i'll update doc page with correct example.

**Comment by dvsekhvalnov** [comment]
fixed.

**Comment by tnovau** [comment]
Thanks @dvsekhvalnov!
