### ISSUE TITLE
Verify a signed RS256 JWT token using only a certificate/public key

### ISSUE THREAD

**Issue by j0zeft** [dvsekhvalnov/jose-jwt#83]
This might be a dumb follow up question...
I need to extract a public key from a certificate file, which I can extract as an array of bytes, and I want to use that to verify a signed JWT token.
I know I should be using this

`string json = Jose.JWT.Decode(token, publicKey);`

But the point is that I don't have a password to use for extracting the public key, I just read the certificate file to a variable, then I get the public key out of it, like this

`string Certificate = @"c:\Development\tokens and keys\SomeCertificate.cer";`
`X509Certificate cert = X509Certificate.CreateFromCertFile(Certificate);`
`byte[] publicKey = cert.GetPublicKey();`

I tried that key directly, and received an exception in runtime telling me that I should be using an Asymmetrical key, which I find quite strange as the token was signed with a private key, and I'm trying to use the Asymmetrical (public) key for verification yet it's failing.

What am I doing wrong and am I on the right track or way off?
and if it is possible, would you be able to elaborate a bit about the parameter passed, like "password" for example? 

Thanks in advance for your time.

**Comment by dvsekhvalnov** [comment]
Hi @j0zeft ,

you are passing `byte[]` as public key, which is not what RSA signing algorithm expecting. It is expecting `RSA` type (`RSACryptoServiceProvider` or `RSACng` for instance).

Library itself doesn't provide way to read .cer files directly (though it is most popular question). Therefore you have to rely on standard .net tools to do the job.

The easiest way is to convert your key from .cer format to .p12 and read directly with `X509Certificate` as shown in examples in documentation.

**Comment by j0zeft** [comment]
But in this case, I will have to ship the private key (which I use to sign my tokens, and should be stored locally on my server) along within the certificate.

What I'm trying to do here is install the certificate on the end user's machine, then my application should use the certificate to verify the signature on the signed tokens sent from my server.

I can already unpack the jwt payload using this:
`string payload = Jose.JWT.Payload(token);`

Currently I want to verify the integrity of the content by verifying the signature using the certificate installed on the end user's machine.

Thanks in advance :)

**Comment by dvsekhvalnov** [comment]
@j0zeft ,

you are not required to distribute your private key in .p12, just import your certificate alone.

`openssl pkcs12 -export -nokeys -in ./my-certificate.cer -out my-certificate.p12`

**Comment by dvsekhvalnov** [comment]
Hi @j0zeft , 

how things going, did you able to resolve your issue and convert public key to .p12? More questions on it?

**Comment by j0zeft** [comment]
I converted my certificate into .p12 using OpenSSL console, but to verify, I had to perform few changes to the code example (just had my first successful build less than 30 minutes ago) and I am not sure if what I did is legitimate or not...
Here is my working code:

`X509Certificate2 CerT = new X509Certificate2(@"C:\certs\MyCertificate.p12",`
 `"pazzword", `
` X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable);`

`var certt = CerT.PublicKey.Key as RSACryptoServiceProvider;`  

` string json = Jose.JWT.Decode(token, certt);`

**Comment by dvsekhvalnov** [comment]
Looks good to me. Working?

**Comment by j0zeft** [comment]
Perfectly.. Thanks a lot for your time and help :)
