### ISSUE TITLE
ECDH bug

### ISSUE THREAD

**Issue by guyulmaz** [dvsekhvalnov/jose-jwt#85]
"Microsoft CNG implementation of BCryptSecretAgreement/NCryptSecretAgreement contains a bug for calculating Elliptic Curve Diffie-Hellman secret agreement on keys higher than 256 bit "

is this bug solved at microsoft side? do they now about this problem?

**Comment by dvsekhvalnov** [comment]
Hi @guyulmaz ,

i've been contacted twice by microsoft. They all got all tech details and tests. I've never heard back after.

Also i haven't verified on recent windows versions if it was fixed (my wild guess it wasn't).

**Comment by dvsekhvalnov** [comment]
@guyulmaz i'll close this one. If you need more information or want to continue discussion feel free to re-open.
