### ISSUE TITLE
Hi, how to set the token  expired time and how to  check the token is expired?

### ISSUE THREAD

**Issue by grissomlau** [dvsekhvalnov/jose-jwt#86]

**Comment by dvsekhvalnov** [comment]
Hi @grissomlau , `jose-jwt` - is low level lib. It let's you sign/encrypt and verify integrity/decrypt using jose standard. 

If you looking for typical JWT Token  - you can easily build any semantic you want yourself on top of it. Just create class with typical jwt claims and use it as payload (or you can go even with IDictionary as well).

Does it make sense?

**Comment by grissomlau** [comment]
Hi @dvsekhvalnov , got it, thank you for your patient explanation.
