### ISSUE TITLE
RSACryptoServiceProvider FixCSP issue

### ISSUE THREAD

**Issue by fevieiraleite** [dvsekhvalnov/jose-jwt#88]
Hi! I'm having issues enforcing the correct CSP in my project. I'm using .NET MVC. When I use the "re-import RSAParameters" approach it works fine. However since that is not recommended for production I'm trying to get the other one working.

One thing that is different in my code from the examples is that RSACryptoServiceProvider doesn't have a definition for "PrivateKey" so I'm just using the object as the private key. It does work for the other approach though so idk if that's the issue.

Here's my code, with the part that doesn't work commented out.

`public ActionResult SamplePSPDFPage(int companyId, int fileId)
        {
            var fileModel = fileRepostitory.getFileData(companyId, fileId);
            string documentId = fileRepostitory.postFileToPSPDF(fileModel);
            var path = System.Web.Hosting.HostingEnvironment.MapPath("~/Content/certificates/pspdfcertificate.p12");

            var payload = new Dictionary<string, object>() {
                { "exp", ToUnixTime(DateTime.Now.AddHours(2)) },
                { "document_id", documentId },
                { "permissions", "all" },
                { "user_id", ProfileCommon.CurrentUser.UserId.ToString() }
            };
            var privateKey = new X509Certificate2(path, "notActualPassword", X509KeyStorageFlags.Exportable | X509KeyStorageFlags.MachineKeySet).PrivateKey as RSACryptoServiceProvider;
            privateKey = FixCSP(privateKey);
            string token = Jose.JWT.Encode(payload, privateKey, JwsAlgorithm.RS256);
            var sampleViewModel = new SamplePSPDFViewModel { documentId = documentId, jwtToken = token };

            return View(sampleViewModel);
        }

        public static RSACryptoServiceProvider FixCSP(RSACryptoServiceProvider key)
        {
            RSACryptoServiceProvider newKey = new RSACryptoServiceProvider();
            newKey.ImportParameters(key.ExportParameters(true));
            return newKey;
            
            //CODE THAT IS RECOMMENDED FOR PRODUCTION BUT ISN'T WORKING BELOW
            //var enhCsp = new RSACryptoServiceProvider().CspKeyContainerInfo;
            //var cspParams = new CspParameters(enhCsp.ProviderType, enhCsp.ProviderName, privKey.CspKeyContainerInfo.KeyContainerName);
            //return new RSACryptoServiceProvider(cspParams);
        }`

**Comment by dvsekhvalnov** [comment]
Hi @fevieiraleite , 

by chance can't you use new .NET4.6 or .netcore  methods:`X509Certificate2. GetRSAPrivateKey()` ?

**Comment by dvsekhvalnov** [comment]
Hi @fevieiraleite , 

any update to far? Are you able to run things with .net4.6 or stuck with earlier version?

**Comment by fevieiraleite** [comment]
Hi @dvsekhvalnov, sorry for the delay. I updated to .net4.6 and used that same code and still got the same error. Do I need to use this "GetRSAPrivateKey", or was that just for .netcore?

**Comment by dvsekhvalnov** [comment]
@fevieiraleite ,

you don't need fix CSP with .net4.6.  Just do:

```C#
var privateKey=new X509Certificate2("my-key.p12", "password").GetRSAPrivateKey();
```

here is reference: https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions.getrsaprivatekey(v=vs.110).aspx

**Comment by fevieiraleite** [comment]
@dvsekhvalnov 

Thank you so much!

After using the "GetRSAPrivateKey" method it all worked perfectly.

**Comment by dvsekhvalnov** [comment]
You welcome @fevieiraleite :)

**Comment by dwarak123** [comment]
Hello Guys 

Am wondering if you could help me with a similar issue I am trying to use this function in a c# dll with framework 4.0 which I cannot change I am trying to resolve an issue where the error generated is "System could not find the file" if I use the RSACryptoServiceProvider and if I use GetRSAPrivateKey it is not recognized I am new to all this can anyone please help. I am first implementing it in visual studio from which I will build a dll as a reference to use in a test automation project

**Comment by dvsekhvalnov** [comment]
Hi @dwarak123 ,

have you read: https://github.com/dvsekhvalnov/jose-jwt#dealing-with-keys ?
