### ISSUE TITLE
Decode without Verify

### ISSUE THREAD

**Issue by AtlasFrank** [dvsekhvalnov/jose-jwt#9]
More of a question than an issue.  I use the Issuer claim (iss) in the incoming jwt to pull a shared secret from a local DB for signature verification.  I'd like to use Decode for this but it doesn't have a path that bypasses signature verification.  So a couple of questions:

1. Is there a reason I shouldn't do this?  We're not encrypting here, just verifying signature in the end but I work with multiple partners.  Yes key pairs would be better but not an option right now.

2. If doing this is ok, is a non-verifying overload of Decode something to consider or should I just GetString the payload part of the token directly?

Thanks in advance.
Frank

**Comment by dvsekhvalnov** [comment]
@AtlasFrank checkout latest v1.9 version. And there is new section in doc about two-phase validation: https://github.com/dvsekhvalnov/jose-jwt/tree/master#two-phase-validation 

this is what you are looking for. In nutshell you need to use Jose.JWT.Payload(..) method to examine payload before integrity check.

**Comment by AtlasFrank** [comment]
Thank you.  That is precisely what I need.
