### ISSUE TITLE
Generated signature can't be decrypted?

### ISSUE THREAD

**Issue by Loreno10** [dvsekhvalnov/jose-jwt#90]
Hello,
I have been trying to use one of the examples from README.
Here's the code that I'm running:
```
        private void RS256Test()
        {
            var payload = new Dictionary<string, object>()
            {
                { "sub", "mr.x@contoso.com" },
                { "exp", 1300819380 }
            };

            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "Certificates", "mycert.p12");

            var privateKey = new X509Certificate2(filePath, "qwerty1").GetRSAPrivateKey();

            string token = Jose.JWT.Encode(payload, privateKey, Jose.JwsAlgorithm.RS256);
        }
```

I just generate a token for a simple payload. I created p12 file using openSSL. For reference, here are my keys:

> -----BEGIN PRIVATE KEY-----
> MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC1POH7o5s/QiaL
> z1x4/H/gELqKmsp8Rsvqi09x5A0P0TT6iSHTUj3gznmDjWga2Di54lD4ItSSROSB
> qNMxiKRPPWbRa4Mu0MuMPI0QNwx9tyCE6Lhuih5N053TCgFqNgFUwTgBBxN/ozYb
> hcmiP4yF8WeNuyQB0iwv8ATwbIuyU9F5L/4nZso/Zw6QXU+ys8ltQ3XVKyGaDSm3
> qOvqxMXUuLuCgSeDFXSOzmvTxvOIfZedJFR7qi4/sO3auav47BfsRPQdzdQqTJEM
> LuObUAFpRstm2FZCuPelojId1/IK1tinW/q2HIQNxfjyv1466SqtKi2KGBHCZspw
> GpLIphcvAgMBAAECggEAZIdg0jPt6SjIOMTMhk+InsCouDkkF8stUOv1JTdaB2wD
> 9vQZzx3PNONSg6XsGPfWf0UJpJmtT3TnSwRaIR+qBEoKvh7kpRMr1J3BoTznsNPj
> NdXgd3AlXwYChQ0Hu+I42spSRj+mkSX23U1Yiqa1S5ab2gHz9w6dc/muw61xz3e/
> wl/7defWPkteYjFjITchRGzZmulXpsHyktCW8R5rA3ZYZMBpJT2uwWDTi3rVNT22
> E4jMA70LKbMe5qDQniUG/qoF7GmZnXQ9ImVV9NnnGEkg4JU47AGs21XN6U42BBaM
> GXvi7KTRplFmAHT947Osc1DDgjSA3GwzZKwxYwjgAQKBgQDZAGrsbDvbYp7fwp9S
> Vh7Z6TlB7ysEzP2MhjO1TzjFUXzVfXhCs9nEkznX3FVQCbseWZtmMV5r/N9OzSK6
> nvuVnQ7vqd3TY+SzVUt4H06PSUHz3YITH9F0ECo79WCSKYQlXvQ1tGkTfg1deCDj
> 5XlIz2eXsoxuXCZ58dGZVEizBwKBgQDVzxTb8XRP8i3XC9QJZk/122CGxfrMdlhz
> IakzcM4OslKwMe40Uan4Gh5YnMBIHUY5l9MTKOFJpm/CBtTAO11RYcueb4vnfGSG
> Hk69x2MNQ7xToxjJcANIVlnssxXNRb3am0dYGfwD3P7Ul7mIIbUtT1twTMjplw+G
> 6OEoOHYomQKBgEYc+28uPVzSDZEwufeJeehgka57D0Q604Vu6xAe67HddV8pbgzn
> PWplQ2A6gZodusbAnxQyyVZM2v4EC7+OlK0vlN7c3J5rfT5wRbUnMGPdgKDBpkB1
> nGBKxMqgqrYvEdJdTrx3cSfqJ3lW0hGwWDKtSMRb3UHfJlNqTZWkBOVLAoGAfmv+
> unpPuwHI5xHgY1pyxz3bGnWv8Pu9Gv55TKhTvs7kI7iyT49GACR5cw3kh/9/SYij
> Tv3qECFwjXp6i9vONtOrkVgFkm+0BLWg+4gM4of9sDqM6nboCfq9Gz9dEc4+Dyen
> jMl4gVRH/a5lDsBXn53/xCwy1CP1E2FZ2O1huGkCgYAhi0ehREmVFG7juXTQpc36
> qj7ge+Kpa0pSrnNCA6fqYxzglQmHZ9dGlGn3ES5ZPGps/Q4lWXEdjJ0Un5tw+s11
> qAVZd4RJ9NEReE3pNS3lDxbZNeJE4TTThVdg0y55sEWrrfyKFjYXhC+lb9EOrrJH
> h/1Jjswr58gFw4tBTwGHyQ==
> -----END PRIVATE KEY-----

> -----BEGIN CERTIFICATE-----
> MIIDtzCCAp+gAwIBAgIJAJevQmN1ULYNMA0GCSqGSIb3DQEBCwUAMHIxCzAJBgNV
> BAYTAlBMMRAwDgYDVQQIDAdsb2R6a2llMQ0wCwYDVQQHDARMb2R6MQ4wDAYDVQQK
> DAVNSklvVDEOMAwGA1UEAwwFTUpJb1QxIjAgBgkqhkiG9w0BCQEWE21hcmNpbmox
> MEBnbWFpbC5jb20wHhcNMTgwNDA4MTMwMTQ5WhcNMTkwNDA4MTMwMTQ5WjByMQsw
> CQYDVQQGEwJQTDEQMA4GA1UECAwHbG9kemtpZTENMAsGA1UEBwwETG9kejEOMAwG
> A1UECgwFTUpJb1QxDjAMBgNVBAMMBU1KSW9UMSIwIAYJKoZIhvcNAQkBFhNtYXJj
> aW5qMTBAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
> tTzh+6ObP0Imi89cePx/4BC6iprKfEbL6otPceQND9E0+okh01I94M55g41oGtg4
> ueJQ+CLUkkTkgajTMYikTz1m0WuDLtDLjDyNEDcMfbcghOi4booeTdOd0woBajYB
> VME4AQcTf6M2G4XJoj+MhfFnjbskAdIsL/AE8GyLslPReS/+J2bKP2cOkF1PsrPJ
> bUN11Sshmg0pt6jr6sTF1Li7goEngxV0js5r08bziH2XnSRUe6ouP7Dt2rmr+OwX
> 7ET0Hc3UKkyRDC7jm1ABaUbLZthWQrj3paIyHdfyCtbYp1v6thyEDcX48r9eOukq
> rSotihgRwmbKcBqSyKYXLwIDAQABo1AwTjAdBgNVHQ4EFgQUE5zCtEjGIcLJPJts
> IeNIkCHOd7wwHwYDVR0jBBgwFoAUE5zCtEjGIcLJPJtsIeNIkCHOd7wwDAYDVR0T
> BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAgzkpM3UBSLmWXbIEbIpuQq0hhc0v
> uiqUsqLuaUKrXb8skV+yBFqvKeR6qQGeZrHmRrFaIfKe49YKHoZ+tDr5bFb99XrU
> ROeEvm1B23IX6vjoF88U7J+67R1dploqF+KIYwZpBvB7p5i5mR2fF7t9Vvq8tIFF
> 0q/Y5m4bqsJPkhNwvj+N48d3+vB2pYq54pRVh12XCw9NHqjHJ2eXMonsEYqqOVCj
> +4QPSONd9kFyfBbNIjm0n4biD/N17R/TXfHV1NkTPfrk31kjfidFHwbV1UVR7SbM
> qUwUjDNhVvsCkOsz2yOoNlmeq7vVrFmtHubmnIfjkJAhb7CF6e/OXjpmxg==
> -----END CERTIFICATE-----

The generated token is:
`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtci54QGNvbnRvc28uY29tIiwiZXhwIjoxMzAwODE5MzgwfQ.CLYtn8gv8J563R2VDWwPhu2F0CARLqdxKsfEoBZc7At4gMqTbJc0LYHP0dZK90V25QJSktWTzi-sjvfHejiqHWWKHWExqBmsejNFnkLi5EnLf3JmQPttZoNQiYQRxxi5VzT4e7A-4AaLhYX6xOH8dPAbms3EJBhg2ZGmL7Ml9PUaDFa7dc7cJGpjgrblGcEC2MNdP69yUSO6ZD4Xy3A8w1nqpYe91IO6ovV02zPMNdCqzFpG_gILaKF2w1ppy0JVLQi6V2PhvVQ1Bf6QCJDqICPv-em6G393TrHb3XeZW1yX3GKj8uQPNefAtNxtH5sjSXWPEqbUWZ6yTJuxjsI2-w`

I can't decrypt the signature. I tried this website: https://8gwifi.org/rsafunctions.jsp
Also I just tried jwt.io, there's an option to paste a token and provide the keys. I always get "Invalid Signature".

Do you have any idea what is the problem? I would be very grateful, since I'm fighting this issue since a few days. I really wanted to include JWT in my university project.

As far as I know, Jose just takes the payload (Base64 version of it with a dot) and signs it with my private key, right? Maybe there are also other steps involved that I don't know about?

**Comment by dvsekhvalnov** [comment]
Hi @Loreno10 ,

i don't see anything wrong with your code or token. It's perfectly valid. Verification online on https://jwt.io/ passing for me with your token and certificate :) See attached picture.
<img width="755" alt="jwt-io-test" src="https://user-images.githubusercontent.com/2323986/38490455-d1cfe890-3bf1-11e8-912d-483bac3811a4.png">

I can't comment about https://8gwifi.org/rsafunctions.jsp it doesn't seem to be JWT oriented but rather just raw crypto.

**Comment by dvsekhvalnov** [comment]
Hey @Loreno10 is it still an issue? Do you need any further assistance?

**Comment by Loreno10** [comment]
@dvsekhvalnov 
I'm sorry for not answering so long, a lot on my head this week. I'll back to this topic in the weekend.
Already I'm really thankful for your answer, I'll update this topic as soon as I check this myself.

**Comment by Loreno10** [comment]
Everything's right as you showed me. Thanks for that again. I was just copying my public key without "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----". Turns out it's necessary.

**Comment by anishnath** [comment]
This tool  https://8gwifi.org/rsafunctions.jsp will work for RSA private key in the below format  PEM 
-----BEGIN RSA PRIVATE KEY-----
----- END RSA PRIVATE KEY------
