### ISSUE TITLE
Setting invalid date for claims iat or exp leads to invalid signature exception

### ISSUE THREAD

**Issue by MaxKlotz** [dvsekhvalnov/jose-jwt#96]
I was generating a JWT with the following content:
`var payload = new Dictionary<string, object>`
`            {`
`                {"exp", DateTime.UtcNow.AddHours(3).ToUnixTime()},`
`                {"iat", DateTime.UtcNow.ToUnixTime().ToString()},`
`                {"iss", "MasterOfTheUniverse"},`
`                {"sub", "User"},`
`                {"id", 12345},`
`                {"mail", "foo@bar.com"}`
`            };`

The value for the claim `iat` is not a valid date, since it's a string value.
But when I generate the token everything works fine.
When the token is validated I get an `IntegrityException` with **invalid signature**.
I think this is an misleading  Exception, because the Signature is valid, but a part of the payload is incorrect.

**Comment by dvsekhvalnov** [comment]
Hi @MaxKlotz ,

would you mind sharing full code where you do encoding/decoding of token and getting exception?

Don't see anything wrong currently. What you put to `iat` - is your deal, not library's business. `IntegrityException` - means what it mean, most likely wrong key.

**Comment by dvsekhvalnov** [comment]
Closed due to inactivity, feel free to re-open.
